<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Raccoon Supervised &amp; Expert-Iteration Analysis – Raccoon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6ac2aec46ad7f46b16024ee4409aa65c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Raccoon Supervised &amp; Expert-Iteration Analysis – Raccoon">
<meta property="og:description" content="Distilling GNUBG: pretraining v1–v5, on-distribution DAgger, and consolidation">
<meta property="og:image" content="https://raccoonbg.com/pretraining_analysis_files/figure-html/cell-3-output-1.png">
<meta property="og:site_name" content="Raccoon">
<meta property="og:image:height" content="540">
<meta property="og:image:width" content="1067">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Raccoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-concepts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Concepts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-concepts">    
        <li>
    <a class="dropdown-item" href="./mcts_explained.html">
 <span class="dropdown-text">MCTS Explained</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./architecture.html">
 <span class="dropdown-text">Architecture</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-training" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Training</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-training">    
        <li>
    <a class="dropdown-item" href="./training_parameters.html">
 <span class="dropdown-text">Parameters</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./training_analysis.html">
 <span class="dropdown-text">Self-Play Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pretraining_analysis.html">
 <span class="dropdown-text">Supervised &amp; Expert Iteration</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./gcp_guide.html"> 
<span class="menu-text">Developer</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reference/index.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#summary-the-strength-ladder" id="toc-summary-the-strength-ladder" class="nav-link active" data-scroll-target="#summary-the-strength-ladder">Summary: the strength ladder</a></li>
  <li><a href="#data-and-methodology" id="toc-data-and-methodology" class="nav-link" data-scroll-target="#data-and-methodology">Data and methodology</a></li>
  <li><a href="#v1" id="toc-v1" class="nav-link" data-scroll-target="#v1">v1 — value-only pretraining</a></li>
  <li><a href="#v2" id="toc-v2" class="nav-link" data-scroll-target="#v2">v2 — synthesised policy distillation</a></li>
  <li><a href="#v2b" id="toc-v2b" class="nav-link" data-scroll-target="#v2b">v2b — a stronger teacher</a></li>
  <li><a href="#v3" id="toc-v3" class="nav-link" data-scroll-target="#v3">v3 — a GNUBG 4-ply teacher</a></li>
  <li><a href="#v4" id="toc-v4" class="nav-link" data-scroll-target="#v4">v4 — capacity</a></li>
  <li><a href="#v5" id="toc-v5" class="nav-link" data-scroll-target="#v5">v5 — doubles value coverage, and the limits of search</a></li>
  <li><a href="#feature-ablation" id="toc-feature-ablation" class="nav-link" data-scroll-target="#feature-ablation">Encoder feature ablation — do handcrafted inputs earn their place?</a></li>
  <li><a href="#exp008" id="toc-exp008" class="nav-link" data-scroll-target="#exp008">exp008 — on-distribution DAgger</a></li>
  <li><a href="#consolidation" id="toc-consolidation" class="nav-link" data-scroll-target="#consolidation">Phase A consolidation — retrain from scratch on everything</a></li>
  <li><a href="#exp009" id="toc-exp009" class="nav-link" data-scroll-target="#exp009">exp009 — scaled DAgger</a></li>
  <li><a href="#exp011b" id="toc-exp011b" class="nav-link" data-scroll-target="#exp011b">exp011b — 0-ply value distillation</a></li>
  <li><a href="#exp014" id="toc-exp014" class="nav-link" data-scroll-target="#exp014">exp014 — does a 2-ply teacher fit as well as the 0-ply teacher?</a></li>
  <li><a href="#exp015" id="toc-exp015" class="nav-link" data-scroll-target="#exp015">exp015 — static PR benchmark against BGSage</a></li>
  <li><a href="#exp016" id="toc-exp016" class="nav-link" data-scroll-target="#exp016">exp016 — revisiting old A/B pairs at BGSage power</a></li>
  <li><a href="#exp017" id="toc-exp017" class="nav-link" data-scroll-target="#exp017">exp017 — does 40M 2-ply distillation beat 8M, and fix the race gap?</a></li>
  <li><a href="#exp018" id="toc-exp018" class="nav-link" data-scroll-target="#exp018">exp018 — does the six-outcome head match scalar at 40M, and do ten more epochs help?</a></li>
  <li><a href="#what-weve-learned" id="toc-what-weve-learned" class="nav-link" data-scroll-target="#what-weve-learned">What we’ve learned</a></li>
  <li><a href="#open-questions" id="toc-open-questions" class="nav-link" data-scroll-target="#open-questions">Open questions</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Raccoon Supervised &amp; Expert-Iteration Analysis</h1>
<p class="subtitle lead">Distilling GNUBG: pretraining v1–v5, on-distribution DAgger, and consolidation</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This page documents the <strong>supervised &amp; expert-iteration track</strong> — everything after the <a href="./training_analysis.html">self-play track</a> concluded that pure AlphaZero self-play plateaus hopelessly far from GNUBG at this project’s compute scale. The idea: instead of bootstrapping a network from noise, <strong>seed it from existing backgammon knowledge</strong> — first by regressing on labeled positions (stages v1–v5), then by keeping the GNUBG oracle in the training loop on the learner’s own positions (exp008, consolidation, exp009).</p>
<p>The arc in one paragraph: a calibrated value head alone is useless without a policy prior (v1); synthesised policy labels fix that mechanically (v2); distillation tops out at its teacher’s strength, so teacher quality is the lever (v2b); a GNUBG 4-ply teacher produces the project’s first wins against GNUBG (v3); capacity, eval-time search, and value-label coverage each fail to push past ~−1.6 ppg (v4, v5); the missing ingredient is <em>on-distribution policy</em> data, which live GNUBG labeling of the learner’s own positions supplies (exp008); retraining from scratch on all accumulated labels consolidates those gains (~−0.93 ppg); and scaling the loop (exp009) reaches <strong>~−0.37 ppg</strong> before plateauing ~0.4 ppg short of parity — until <strong>0-ply value distillation</strong> (<a href="#exp011b">exp011b</a>) breaks that wall, reaching <strong>−0.05 vs 0-ply</strong> and <strong>−0.06 vs 2-ply</strong>, the current best. Each section below covers one experiment: motivation, setup, results, interpretation — results computed from the experiment logs at render time.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Current best (2026-08-12)
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="#exp018">exp018</a>’s <code>ep22</code> is the deliverable: 24 epochs of <strong>GNUBG-2-ply</strong> distillation over the full 40M corpus with the six-outcome value head, scoring <strong>PR 0.950</strong> and <strong>rollout-MSE 0.00190</strong> on the BGSage money benchmark (n=14,693 / n≈149k) — past GNUBG-0-ply on both (2.145 / 0.00209) and within 2% of the GNUBG-2-ply teacher’s MSE (0.00187). It is chosen over <a href="#exp017">exp017</a>’s scalar <code>ep12</code> (PR 0.928) on <strong>capability</strong>, not strength: only the six-outcome head emits the win/gammon/backgammon split the cube needs. On checker play the scalar head is in fact slightly ahead — a paired +0.067 PR at their matched ep14 (CI [+0.009, +0.127]) — though the two tie on rollout MSE, and with one unseeded run per arm that gap cannot be attributed to the head rather than to initialisation.</p>
<p>Two caveats on that headline. It is a <strong>static-benchmark</strong> number, so it is not comparable to the ppg figures quoted for earlier nets (<a href="#exp011b">exp011b</a>’s −0.053 ± 0.046 vs GNUBG-0-ply, n=6000, remains the best <em>measured-in-play</em> result); a raw-ppg confirmation at matched search is still outstanding. And <strong>0.950 is a winner’s-curse pick</strong> — the ep15–24 plateau averages 0.994 (SD 0.023), so read the recipe’s true level as ≈0.99. Both training levers behind it are now spent or bounded: epochs are closed (<a href="#exp018">exp018</a>), and beyond that the gap to the teacher’s 0.56 is play-time search and label quality, not undertraining.</p>
</div>
</div>
<section id="summary-the-strength-ladder" class="level2">
<h2 class="anchored" data-anchor-id="summary-the-strength-ladder">Summary: the strength ladder</h2>
<p>The one metric that matters is standalone strength against GNUBG 2-ply (<code>gnubg-nn</code> at <code>level=world</code> — full-width 2-ply, “World class”; see the <a href="./training_analysis.html#how-to-read-the-results">self-play page</a> for eval conventions). Each bar is one experiment’s final checkpoint — or its best, where a run oscillated (exp009 shows its round-6 peak):</p>
<div id="c113753d" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Two caveats on reading the ladder. Evaluation sim counts differ (100 for v1–v5, 50 for the later checkpoints, as labeled) — and <em>more</em> sims measurably <strong>hurts</strong> these networks (see <a href="#v5">v5</a>), so the later bars are not flattered by the lower setting. And 100-game samples carry ±0.3–0.5 ppg of noise; the exp008 round_15 bar pools its original n=100 (−1.19) with a fair n=200 re-benchmark (−1.38).</p>
<p>The full eval record per checkpoint, pooled by opponent and sim count:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 30%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">checkpoint</th>
<th style="text-align: left;">opponent</th>
<th style="text-align: left;">sims</th>
<th style="text-align: left;">result</th>
<th style="text-align: left;">win%</th>
<th style="text-align: left;">ppg</th>
<th style="text-align: left;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">v1 (value-only)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">6-194</td>
<td style="text-align: left;">3%</td>
<td style="text-align: left;">-2.03</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">v1 (value-only)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">0-200</td>
<td style="text-align: left;">0%</td>
<td style="text-align: left;">-2.73</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v2 (0-ply self-teacher)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">22-78</td>
<td style="text-align: left;">22%</td>
<td style="text-align: left;">-1.24</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">v2 (0-ply self-teacher)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">0-100</td>
<td style="text-align: left;">0%</td>
<td style="text-align: left;">-2.59</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v2b (iter_0447 teacher)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">49-51</td>
<td style="text-align: left;">49%</td>
<td style="text-align: left;">-0.04</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">v2b (iter_0447 teacher)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">0-100</td>
<td style="text-align: left;">0%</td>
<td style="text-align: left;">-2.29</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v3 (GNUBG 4-ply teacher)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">83-17</td>
<td style="text-align: left;">83%</td>
<td style="text-align: left;">+1.38</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">v3 (GNUBG 4-ply teacher)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">3-97</td>
<td style="text-align: left;">3%</td>
<td style="text-align: left;">-1.79</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v4 (10×256)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">93-7</td>
<td style="text-align: left;">93%</td>
<td style="text-align: left;">+1.96</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">v4 (10×256)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">5-95</td>
<td style="text-align: left;">5%</td>
<td style="text-align: left;">-1.66</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v4 (10×256)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">16-384</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">-1.84</td>
<td style="text-align: left;">400</td>
</tr>
<tr class="even">
<td style="text-align: left;">v5 (10×256 +doubles)</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">93-7</td>
<td style="text-align: left;">93%</td>
<td style="text-align: left;">+1.98</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">v5 (10×256 +doubles)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">8-92</td>
<td style="text-align: left;">8%</td>
<td style="text-align: left;">-1.59</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">v5 (10×256 +doubles)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">4-96</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">-1.88</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">v5 seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">63-37</td>
<td style="text-align: left;">63%</td>
<td style="text-align: left;">+0.48</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">iter_0447 (self-play best)</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">98-2</td>
<td style="text-align: left;">98%</td>
<td style="text-align: left;">+2.23</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">43-257</td>
<td style="text-align: left;">14%</td>
<td style="text-align: left;">-1.31</td>
<td style="text-align: left;">300</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">8-92</td>
<td style="text-align: left;">8%</td>
<td style="text-align: left;">-1.48</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">v5 seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">186-64</td>
<td style="text-align: left;">74%</td>
<td style="text-align: left;">+0.96</td>
<td style="text-align: left;">250</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">122-78</td>
<td style="text-align: left;">61%</td>
<td style="text-align: left;">+0.45</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">48-152</td>
<td style="text-align: left;">24%</td>
<td style="text-align: left;">-0.93</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">v5 seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">77-23</td>
<td style="text-align: left;">77%</td>
<td style="text-align: left;">+1.16</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">70-30</td>
<td style="text-align: left;">70%</td>
<td style="text-align: left;">+0.74</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">45-155</td>
<td style="text-align: left;">22%</td>
<td style="text-align: left;">-0.96</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">consol 26ch seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">74-26</td>
<td style="text-align: left;">74%</td>
<td style="text-align: left;">+0.81</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">pretrained_v2</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">2-2</td>
<td style="text-align: left;">50%</td>
<td style="text-align: left;">+0.00</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">83-117</td>
<td style="text-align: left;">42%</td>
<td style="text-align: left;">-0.37</td>
<td style="text-align: left;">200</td>
</tr>
</tbody>
</table>
</section>
<section id="data-and-methodology" class="level2">
<h2 class="anchored" data-anchor-id="data-and-methodology">Data and methodology</h2>
<p>Four datasets feed the track — two external corpora, one generated in-house by GNUBG self-play, and one external benchmark used only for scoring:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>Role</th>
<th>License</th>
<th>What it provides</th>
<th>Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://github.com/carsten-wenderdel/wildbg-training">wildbg-training</a></td>
<td>training</td>
<td>CC0</td>
<td>Pre-roll positions with rollout equities (<code>win</code>, <code>win_g</code>, <code>win_bg</code>, <code>lose_g</code>, <code>lose_bg</code>) — value labels only, no moves</td>
<td>~300k positions</td>
</tr>
<tr class="even">
<td><a href="https://github.com/lassehjorthmadsen/bglab">bglab</a> match archive</td>
<td>training</td>
<td>personal match data</td>
<td>Human match positions (raw), and GNUBG 2-ply/4-ply analysis of those matches (<code>analyzed/</code>)</td>
<td>~1777 raw matches → ~238k decisions; ~4319 analysed games → ~164k labeled decisions</td>
</tr>
<tr class="odd">
<td>GNUBG self-play distillation (<code>data/distill/</code>)</td>
<td>training</td>
<td>generated in-house</td>
<td>GNUBG self-play positions labeled by GNUBG itself — cubeless money <code>equity</code> plus the six-outcome distribution, at 0-ply and/or 2-ply</td>
<td>40M positions at 2-ply, 16M at 0-ply</td>
</tr>
<tr class="even">
<td><a href="https://github.com/markbgsage/bgsage">BGSage</a> money benchmark (<code>data/bgsage/</code>)</td>
<td>evaluation only</td>
<td>sibling project</td>
<td>Sage self-play money games with adaptive-precision cubeless-equity references</td>
<td>14,693 checker decisions → ~327k candidate positions</td>
</tr>
</tbody>
</table>
<p>The shared pipeline (<code>raccoon/data/</code>): decode positions into a perspective-relative board, encode with the same tensor encoder the self-play network uses (so any pretrained checkpoint is a drop-in <code>--resume</code> target), and <strong>replay matches move-by-move through OpenSpiel</strong> to recover the legal-action set at every decision. Move matching is robust to notation variants by falling back to a final-board-signature comparison — 99%+ replay success across both the raw and analysed corpora, with per-decision Position-ID verification against the analysed files (0 mismatches). bglab’s own equities are match-cubeful and are never used as targets; value targets come from wildbg rollouts, from a network, or from GNUBG money equities.</p>
<p><strong>The distillation corpus</strong> (<code>data/distill/</code>; <code>data/README.md</code> has the full layout) is the dominant training source from <a href="#exp011b">exp011b</a> onward, and the only one that scales: positions come from GNUBG self-play (<code>scripts/gen_gnubg_selfplay.py</code>), labels from re-querying GNUBG at a chosen ply (<code>scripts/relabel_2ply.py</code>). Shards are organised <strong>by label ply first, then by generation run</strong> — <code>2ply/{run1,run2,run3}</code> totalling <strong>40M</strong> positions (8M + 8M + 24M), <code>0ply/{run1,run2}</code> totalling 16M. <code>run1</code> is the <strong>matched pair</strong>: the same 8M positions labeled at both plies, which is what lets <a href="#exp014">exp014</a> isolate the effect of teacher ply from the effect of which positions were sampled; run2 and run3 are independent samples whose shard filenames only align within a run, so they can’t be paired that way. run3 is 2-ply-only by design — its 0-ply twin was generated, relabeled, and deleted. Which slice each experiment consumed: <a href="#exp011b">exp011b</a> <code>0ply/run1</code> (8M), <a href="#exp014">exp014</a> <code>0ply/run1</code> vs <code>2ply/run1</code> (8M each), <a href="#exp017">exp017</a> all of <code>2ply/</code> (40M).</p>
<p><strong>The BGSage benchmark</strong> (<code>data/bgsage/money_benchmark/benchmark.json.gz</code>) is scoring-only — nothing on this page trains on it. 500 Sage-3P self-play money games, 17,535 decisions of which 14,693 are checker decisions, each adjudicated at one of three reference tiers (rollout &gt; 3-ply-team &gt; 3-ply) by BGSage’s adaptive-precision scheme. Being external to every engine scored against it is what makes it usable as a primary metric rather than a proxy; the full scoring protocol and its caveats are in <a href="#exp015">exp015</a>.</p>
<p>Two further <em>derived</em> caches sit alongside the experiments that made them: the bglab 4-ply and policy caches (<code>data/bglab/cache/</code>, via <code>scripts/synthesize_gnubg_dataset.py</code> and <code>synthesize_policy_dataset.py</code>) behind <a href="#v2">v2</a>–<a href="#v5">v5</a>, and the on-distribution DAgger caches (<code>experiments/&lt;exp&gt;/caches/</code>) of learner-generated positions labeled live by GNUBG, behind <a href="#exp008">exp008</a> and <a href="#exp009">exp009</a>.</p>
<p>Eval conventions match the <a href="./training_analysis.html#how-to-read-the-results">self-play page</a>: ppg under cubeless money scoring, arena matches at equal MCTS sims, GNUBG benchmark vs 2-ply. Where a benchmark was logged in chunks or replicated, tables on this page pool all rows for the same (checkpoint, opponent, sims). From <a href="#exp015">exp015</a> onward the headline metric is instead the static BGSage score — PR over all 14,693 checker decisions, and value-head R²/MSE on the rollout tier (n≈149k) — which resolves near-parity comparisons that raw ppg cannot at any feasible n.</p>
</section>
<section id="v1" class="level2">
<h2 class="anchored" data-anchor-id="v1">v1 — value-only pretraining</h2>
<p><strong>Motivation.</strong> The cheapest possible seed: regress the value head onto wildbg’s ~300k rollout equities and see how far a calibrated value function alone goes.</p>
<p><strong>Setup.</strong> 20 epochs on the default 6×128 net (<code>pretrain-wildbg-v1</code>). The policy head receives no gradient and stays random.</p>
<p><strong>Results.</strong></p>
<div id="9b7f84da" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Final val MSE: 0.0021</code></pre>
</div>
</div>
<p>The fit succeeds (val MSE ≈ 0.002 on a [−1, 1] target). The player does not: as a standalone engine it lost 6-194 (−2.03 ppg) to the best self-play checkpoint (iter_0447) and 0-200 (−2.725) to GNUBG — <em>worse</em> than iter_0447 itself against GNUBG.</p>
<p><strong>Interpretation.</strong> <strong>A calibrated value head is not a player.</strong> With a uniform-ish policy prior, 100-sim MCTS spreads its budget over too many moves to find the lines the value head would reward. The policy prior is load-bearing; supplying one became the next step.</p>
</section>
<section id="v2" class="level2">
<h2 class="anchored" data-anchor-id="v2">v2 — synthesised policy distillation</h2>
<p><strong>Motivation.</strong> wildbg has no move labels. Manufacture them: replay the bglab human matches, and at each decision do a 0-ply lookahead — static value evaluation of each candidate move, GNUBG’s convention (TD-Gammon calls it 1-ply) — with v1’s value head, one-hotting the best child as the policy target (~238k decisions).</p>
<p><strong>Setup.</strong> Fine-tune both heads from v1 (<code>pretrain-wildbg-v2</code>): policy cross-entropy plus value distillation against the teacher’s own V(s), which keeps the value head calibrated while the trunk learns the dice channels (wildbg positions are all pre-roll).</p>
<p><strong>Results.</strong></p>
<div id="0784ee4e" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A large improvement — vs iter_0447 it went from v1’s 3% wins to 22% (+0.79 ppg) — but still a clear loss (22-78, −1.24), and still 0-100 vs GNUBG (−2.59).</p>
<p><strong>Interpretation.</strong> The mechanism works: synthesised policy labels produce a usable prior, confirming v1’s diagnosis. But the teacher — a 0-ply argmax under a GNUBG-weak value head — is itself weak, and the student cannot exceed it.</p>
</section>
<section id="v2b" class="level2">
<h2 class="anchored" data-anchor-id="v2b">v2b — a stronger teacher</h2>
<p><strong>Motivation.</strong> If the teacher is the ceiling, raise the teacher: re-synthesise the same policy targets using the strongest value function available — exp005’s iter_0447 — for the 0-ply lookahead. Same matches, same pipeline, better labels.</p>
<p><strong>Setup.</strong> As v2, with iter_0447 as both the lookahead value function and the value-distillation target (<code>pretrain-wildbg-v2b</code>).</p>
<p><strong>Results.</strong></p>
<div id="6d7bf32d" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>By fitting metrics v2b looks <em>worse</em> than v2 — top-1 ~28% vs ~38%, value MSE ~2× higher. By strength it is far better: <strong>49-51 vs iter_0447 (−0.04 ppg) — statistical parity with the best self-play net</strong>, in long balanced games rather than v2’s quick collapses. Vs GNUBG: 0-100, −2.29.</p>
<p><strong>Interpretation.</strong> Two lessons. <strong>You cannot distill past your teacher</strong> — parity is exactly the expected ceiling when iter_0447 <em>is</em> the teacher — but you can compress it: v2b matches ~290 GPU-hours of self-play with ~21 CPU-hours of supervised training. And <strong>fitting metrics across different teachers are incomparable</strong>: 28% agreement with a strong teacher beats 38% agreement with a weak one. Strikingly, MCTS at eval time recovers full strength from a prior that agrees with its own labels only ~28% of the time — search only needs the prior to be directionally right.</p>
</section>
<section id="v3" class="level2">
<h2 class="anchored" data-anchor-id="v3">v3 — a GNUBG 4-ply teacher</h2>
<p><strong>Motivation.</strong> The way past iter_0447’s level is a teacher stronger than any network we own. The bglab archive ships one: GNUBG 4-ply analysis of the same matches — world-class labels, for free.</p>
<p><strong>Setup.</strong> Read GNUBG’s labels directly off the analysed files at every non-doubles decision (<code>pretrain-gnubg-v3</code>): a <strong>soft</strong> policy target <code>softmax(money_equities / T)</code> over GNUBG’s candidate moves (near-ties taught as near-ties), and a money-equity value target — never GNUBG’s match-cubeful equity. ~139k positions. Doubles decisions (~18%) are dropped: OpenSpiel splits a doubles play into two decision nodes while GNUBG scores the whole move, so the first-half action is ambiguous. Same 6×128 net, warm from v1.</p>
<p><strong>Results.</strong></p>
<div id="099e2bd2" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Decisive on both fronts. <strong>v3 crushes iter_0447: 83-17, +1.38 ppg</strong> — with 42 gammons and 20 backgammons won — the first checkpoint in the project to beat it. And <strong>v3 wins the project’s first games against GNUBG: 3-97, −1.79 ppg</strong> — every prior checkpoint, self-play or supervised, had gone 0-for-all. GNUBG’s backgammon count against us collapsed (64 → 17 per 100 games).</p>
<p><strong>Interpretation.</strong> The teacher-quality thesis confirmed at scale: no new search, no bigger net, no self-play — only better labels, and the ceiling lifts <em>above</em> every player the project had produced. This was the first hard evidence the GNUBG gap is closable by supervised means. Top-1 agreement is still only ~28%: the student captures a fraction of its 4-ply teacher, which relocates the binding constraint from the teacher to the student.</p>
</section>
<section id="v4" class="level2">
<h2 class="anchored" data-anchor-id="v4">v4 — capacity</h2>
<p><strong>Motivation.</strong> With the teacher fixed at world class, the student’s shortfall has two candidate axes: capacity and coverage. v4 isolates capacity — same teacher, same ~139k cache, network scaled 6×128 → <strong>10×256</strong> (2.5M → 11.9M parameters).</p>
<p><strong>Setup.</strong> Single-stage training from random init on the GNUBG cache (<code>pretrain-gnubg-v4-10x256</code>) — the cache carries value targets, so v1’s warm-start is no longer needed. 10 epochs, ~5.6 h on the iMac CPU.</p>
<p><strong>Results.</strong></p>
<div id="36f29541" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The bigger net fits the teacher better (top-1 28 → 31%, value MSE 0.0075 → 0.0066) and converts it fully against the internal bar: <strong>93-7 vs iter_0447, +1.96 ppg</strong> (zero backgammons conceded). Against GNUBG: <strong>5-95, −1.66 ppg</strong> — vs v3’s 3-97, −1.79. That +0.13 ppg is inside the ±0.43 95% CI: statistically no change.</p>
<p><strong>Interpretation.</strong> The split <em>is</em> the finding: capacity converts to strength against opponents near the training distribution, and does nothing against GNUBG steering the game into positions the human-match archive doesn’t cover. That is the signature of a coverage/generalisation gap, not a parameter-count gap.</p>
</section>
<section id="v5" class="level2">
<h2 class="anchored" data-anchor-id="v5">v5 — doubles value coverage, and the limits of search</h2>
<p><strong>Motivation.</strong> Attack the most concrete coverage hole: the ~18% of decisions dropped as doubles. Their <em>policy</em> is ambiguous under OpenSpiel’s move-splitting, but their <em>value</em> is not — the best candidate’s money equity stands regardless of how the move is split.</p>
<p><strong>Setup.</strong> Re-synthesise the cache with each doubles decision as a <strong>value-only</strong> example (policy masked out): +25k examples, cache 139k → 164k (<code>pretrain-gnubg-v5-10x256-dbl</code>). Same 10×256 single-stage recipe, 20 epochs.</p>
<p><strong>Results.</strong> Fit improves on both heads (top-1 33.0%, value MSE 0.0061 — now including the doubles). Strength: <strong>93-7 vs iter_0447 (+1.98)</strong> — dead level with v4 — and <strong>8-92, −1.59 ppg vs GNUBG</strong>, the best external number of the pretraining stages but within noise of v4’s −1.66. What did shift is the loss profile: GNUBG’s gammons against us fell 55 → 37.</p>
<p>Two follow-up measurements defined the next experiment:</p>
<ul>
<li><strong>More search hurts.</strong> At 800 sims instead of 100, v4 scores −1.84 (n=400) and v5 −1.88 (n=100) — both <em>worse</em> than at 100 sims. Deeper MCTS lets miscalibrated value backups override the distilled GNUBG policy prior more aggressively, walking further into unfamiliar territory instead of out of it.</li>
<li><strong>The per-decision error profile</strong> (<code>scripts/error_profile.py</code>, scoring every v5 decision in the 800-sim game log against a GNUBG 0-ply oracle):</li>
</ul>
<pre><code>side     bucket       decisions  mean loss  loss/game   share
raccoon  total             2675     0.0811      2.170   100%
raccoon  non-doubles       1971     0.0669      1.319    61%
raccoon  doubles            704     0.1208      0.850    39%
gnubg    total             3330     0.0051      0.171   (baseline)</code></pre>
<p>Doubles are ~1.8× worse per decision — the policy head’s structural blindness is real — but non-doubles are the larger absolute leak (61% of equity lost). Even a perfect doubles fix leaves ~1.3 ppg on the table.</p>
<p><strong>Interpretation.</strong> The third student-side lever in a row moves the external gap by less than noise: after capacity (v4), eval-time search (v4@800), and value-coverage (v5), the gap sits at <strong>~−1.6 ppg no matter what</strong>. The diagnosis sharpens: more value labels of the same kind can’t teach <em>move selection</em> on the lines GNUBG forces, and the human-match archive structurally does not contain those lines. What’s missing is <strong>on-distribution policy data</strong> — and the error profile adds that the value head misleads search even off-doubles, so both targets need fixing. A fixed archive cannot supply either; a live oracle can.</p>
</section>
<section id="feature-ablation" class="level2">
<h2 class="anchored" data-anchor-id="feature-ablation">Encoder feature ablation — do handcrafted inputs earn their place?</h2>
<p><strong>Motivation.</strong> The encoder carries nine handcrafted broadcast channels (pip counts, blots, anchors, contact) added wholesale in commit <code>23463f0</code> and never tested. They are deterministic functions of the board — a large net could re-derive them — so their value, if any, is an inductive-bias shortcut in data-limited regimes. Are they helping or hurting?</p>
<p><strong>Setup.</strong> Paired ablation in a deliberately small regime: 50k wildbg positions, 15 epochs, 6×128, two seeds per condition (same seed ⇒ same split). Yardstick: held-out value MSE, split into wildbg’s race vs contact files — pip count should help races most. Value-only training, so no play-strength numbers (v1’s lesson: they’d be meaningless).</p>
<p><strong>Results.</strong></p>
<div id="25defbfc" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>The features were silently mis-scaled.</strong> The base planes live in [0, 1] by construction; the handcrafted channels were emitted raw — pip count ~95–230, roughly 100× larger. Adding raw pip count alone <em>raised</em> val MSE by ~88% (0.0058 vs 0.0031): the input convolution reads every channel through one weight scale, so the giant channels dominate the gradient. A live regression, hiding since the commit that added the features.</p>
<div id="d846b764" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>feature                     raw           Fix-N (norm)           Fix-B (inbn)
-----------------------------------------------------------------------------
base     0.0031 (0.0038/0.0028) 0.0031 (0.0038/0.0028) 0.0034 (0.0034/0.0034)
pip      0.0058 (0.0040/0.0068) 0.0029 (0.0021/0.0032) 0.0028 (0.0021/0.0031)
blots                         - 0.0027 (0.0028/0.0027) 0.0031 (0.0036/0.0029)
anchors                       - 0.0029 (0.0029/0.0030) 0.0032 (0.0031/0.0032)
contact                       - 0.0027 (0.0026/0.0028) 0.0030 (0.0032/0.0029)
all                           - 0.0022 (0.0018/0.0024) 0.0026 (0.0023/0.0027)

cells: overall (race / contact); 2-seed mean of each run's best epoch</code></pre>
</div>
</div>
<p>Both candidate fixes repair the blowup: <strong>Fix-N</strong> (divide each channel by a fixed constant in the encoder) and <strong>Fix-B</strong> (a BatchNorm over the raw input). Fix-N wins on every feature group, and Fix-B slightly <em>hurts</em> the already-normalised base — standardising clean channels just injects per-batch noise. Once scaled, the full 26-channel encoder reaches val MSE <strong>0.0022 vs base 0.0031</strong> (−29%, and −53% on races, exactly where a pip count should help) and hits base’s floor in 4 epochs instead of 15. No single feature group is decisively justified on its own (individual gaps sit inside the seed-to-seed spread); the robust effects are the full set and the race-side gain.</p>
<p><strong>Interpretation.</strong> Input scaling is load-bearing: any new channel must enter at the base planes’ scale. Fix-N became the encoder default (commit <code>c493714</code>), and the normalised 26-channel encoder became one arm of the <a href="#consolidation">consolidation A/B</a>. The caveat is built into the design — this measures a small-data inductive bias; at full data a big net may simply re-derive the features (the consolidation tests exactly that).</p>
</section>
<section id="exp008" class="level2">
<h2 class="anchored" data-anchor-id="exp008">exp008 — on-distribution DAgger</h2>
<p><strong>Motivation.</strong> Two results pinned down the design. The archive stages topped out at ~−1.6 ppg with on-distribution <em>policy</em> as the diagnosed gap (<a href="#v5">v5</a>); and <a href="./training_analysis.html#exp007">exp007</a> showed pure self-play from the v5 seed erases it. Expert iteration threads the needle: generate positions with the <em>current net’s own play</em> (fixing the distribution gap), but label them with a <em>fixed strong oracle</em> (fixing the signal-quality trap). The installed <code>gnubg-nn</code> engine — the benchmark opponent itself — can label arbitrary positions programmatically.</p>
<p><strong>Setup.</strong> 15 DAgger rounds, warm-started from v5 (10×256, 17-channel encoder). Each round: the current net plays temperature-sampled games; every visited position is labeled live by GNUBG at 2-ply (soft policy over candidates + money-equity value; ~30–48k labels/round, capped at 10 h); the round cache is merged with the 4-ply archive plus the last 4 rounds’ caches; fine-tune 4 epochs at lr 3×10⁻⁴; evaluate. Pure supervised distillation throughout — no MCTS targets, no terminal outcomes — so neither exp007 failure mode can recur by construction. Hands-off on the iMac CPU, 2026-06-27 → 07-06.</p>
<p>The on-dist data is a genuinely different distribution where it matters: v5’s error against the generated labels is far higher than against the archive (value MSE 0.016 vs 0.006; top-1 25% vs 49%), and the generated positions are heavier in hitting sequences (on-bar 46% vs 29%) and doubles (27% vs 15%) — the regions the error profile flagged.</p>
<p><strong>Results.</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">round</th>
<th style="text-align: left;">vs v5 seed</th>
<th style="text-align: left;">vs iter_0447</th>
<th style="text-align: left;">vs GNUBG 2-ply</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">55-45 +0.16</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">53-47 +0.14</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">57-43 +0.29</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">57-43 +0.37</td>
<td style="text-align: left;">95-5 +2.07</td>
<td style="text-align: left;">7-93 -1.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">55-45 +0.22</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">54-46 +0.11</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">56-44 +0.36</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">55-45 +0.11</td>
<td style="text-align: left;">96-4 +2.24</td>
<td style="text-align: left;">9-91 -1.42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">59-41 +0.40</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">55-45 +0.26</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">54-46 +0.20</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">65-35 +0.60</td>
<td style="text-align: left;">95-5 +2.06</td>
<td style="text-align: left;">10-90 -1.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">60-40 +0.48</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">57-43 +0.23</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">63-37 +0.48</td>
<td style="text-align: left;">98-2 +2.23</td>
<td style="text-align: left;">17-83 -1.19</td>
</tr>
</tbody>
</table>
<p>(100 games per cell, 50 eval sims; GNUBG benchmarked every 4th round)</p>
<p>Three verdicts, in order of importance:</p>
<ol type="1">
<li><strong>The regression trap is gone.</strong> Where exp007 fell to 10-90 against the v5 seed in 50 self-play iterations, exp008 <em>climbs</em> — to 63-37 (+0.48 ppg) by round 15. Pooling the last four rounds: 245/400 vs the seed, z ≈ 4.5 — unambiguous improvement over the strongest supervised checkpoint, the first method to achieve that.</li>
<li><strong>The external gap narrowed</strong>: 7% → 17% wins, −1.65 → −1.19 ppg between rounds 4 and 15 (two-proportion p ≈ 0.03). (The fair n=200 re-benchmark of round_15, run later, puts it at −1.38 — see the <a href="#consolidation">consolidation</a> below.)</li>
<li><strong>iter_0447 is now beaten 98-2</strong> (+2.23), up from the seed’s 93-7.</li>
</ol>
<p>A same-conditions re-check at 100 sims confirms the ordering (v5 −1.72, round_15 −1.48, n=100 each) — and reproduces the “more sims hurt” pattern from <a href="#v5">v5</a>: both nets score worse at 100 sims than at 50, so value-head calibration under search remains the standout bottleneck.</p>
<p><em>Infrastructure aside:</em> the run surfaced a 10× CPU-training slowdown — weights drifting into subnormal floats, hitting the FPU slow path. <code>torch.set_flush_denormal(True)</code> fixed it (measured 10.24× on the degraded weights) and retroactively explains exp007’s mysterious SGD slowdown; together with <code>OMP_WAIT_POLICY=PASSIVE</code> (idle OpenMP threads otherwise busy-spin under desktop contention) it is now standard for CPU training.</p>
<p><strong>Interpretation.</strong> The diagnosis from v5 was correct and the fix works: on-distribution states plus a fixed strong expert for <em>both</em> targets improves on the seed where self-play destroyed it. The return is modest per round (~0.4–0.5 ppg over 15 rounds / ~200 CPU-hours), and the loop’s ceiling is its teacher — GNUBG 2-ply — by construction. Both facts shaped what came next: consolidate the accumulated labels properly, then scale the loop.</p>
</section>
<section id="consolidation" class="level2">
<h2 class="anchored" data-anchor-id="consolidation">Phase A consolidation — retrain from scratch on everything</h2>
<p><strong>Motivation.</strong> exp008 left two loose ends. Its checkpoint was the product of 15 successive warm fine-tunes over shifting data mixes — was strength left on the table versus simply <em>retraining from scratch on all accumulated labels</em>? And the <a href="#feature-ablation">feature ablation</a> validated a normalised 26-channel encoder at small scale but the production lineage was still 17-channel — the retrain is the natural A/B point. Both questions gate the seed choice for exp009.</p>
<p><strong>Setup.</strong> (<code>experiments/pipeline_consolidate.sh</code>, 2026-07-08 → 07-10.) Merge the 4-ply archive (164k) with all 15 exp008 on-dist round caches (~680k) into one ~844k-example cache; re-encode a copy losslessly to 26 channels. Train a fresh random-init 10×256 on each cache (12 epochs, lr 10⁻³, best-val-epoch checkpoint selection). Evaluate each arm vs the v5 seed, vs exp008 round_15 (the incumbent), and vs GNUBG 2-ply (4×50 games) — plus a fair n=200 GNUBG re-benchmark of round_15 itself, all at 50 sims.</p>
<p><strong>Results.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">checkpoint</th>
<th style="text-align: left;">opponent</th>
<th style="text-align: left;">sims</th>
<th style="text-align: left;">result</th>
<th style="text-align: left;">win%</th>
<th style="text-align: left;">ppg</th>
<th style="text-align: left;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">v5 seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">186-64</td>
<td style="text-align: left;">74%</td>
<td style="text-align: left;">+0.96</td>
<td style="text-align: left;">250</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">122-78</td>
<td style="text-align: left;">61%</td>
<td style="text-align: left;">+0.45</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">consol 17ch</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">48-152</td>
<td style="text-align: left;">24%</td>
<td style="text-align: left;">-0.93</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">v5 seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">77-23</td>
<td style="text-align: left;">77%</td>
<td style="text-align: left;">+1.16</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">exp008 round_15</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">70-30</td>
<td style="text-align: left;">70%</td>
<td style="text-align: left;">+0.74</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">consol 26ch</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">45-155</td>
<td style="text-align: left;">22%</td>
<td style="text-align: left;">-0.96</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">consol 26ch seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">74-26</td>
<td style="text-align: left;">74%</td>
<td style="text-align: left;">+0.81</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">pretrained_v2</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">2-2</td>
<td style="text-align: left;">50%</td>
<td style="text-align: left;">+0.00</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp009 round_06 (best)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">83-117</td>
<td style="text-align: left;">42%</td>
<td style="text-align: left;">-0.37</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp008 round_15 (fair re-benchmark)</td>
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">26-174</td>
<td style="text-align: left;">13%</td>
<td style="text-align: left;">-1.38</td>
<td style="text-align: left;">200</td>
</tr>
</tbody>
</table>
<p>Both arms beat everything before them: the 17ch arm reaches <strong>−0.93 ppg (24% wins, n=200)</strong> against GNUBG 2-ply and the 26ch arm −0.96 (22%) — statistically indistinguishable from each other, and a large step past the incumbent. Both beat round_15 head-to-head (+0.45 and +0.74 ppg pooled). Meanwhile round_15’s own fair n=200 benchmark lands at <strong>−1.38</strong>, well below its documented −1.19: the n=100 number was an optimistic draw (±0.5-ppg-wide CIs make that routine).</p>
<p>The run also priced deeper teachers for future rounds (<code>scripts/bench_gnubg_ply.py</code>, 30 positions):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>GNUBG ply</th>
<th>s/decision</th>
<th>labels/h/core</th>
<th>vs 2-ply</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0.003</td>
<td>~1.4M</td>
<td>—</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.305</td>
<td>~11.8k</td>
<td>1×</td>
</tr>
<tr class="odd">
<td>3</td>
<td>16.2</td>
<td>~220</td>
<td>53×</td>
</tr>
<tr class="even">
<td>4</td>
<td>262</td>
<td>~14</td>
<td>861×</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation.</strong> Three conclusions. <strong>Consolidated retraining beats incremental fine-tuning by ~+0.4 ppg</strong> on the identical label pool — the DAgger loop’s warm fine-tunes had accumulated real sub-optimality (recency-window mixes, per-round overfitting). <strong>Measure at n≥200</strong>: the −1.19 → −1.38 correction is a standing reminder that 100-game GNUBG evals carry ±0.5 ppg. And <strong>the handcrafted features appeared to wash out at scale</strong> — at 844k labels the 26ch arm showed no edge over 17ch on this n=200 GNUBG match (consistent with the ablation’s small-data framing); the 26ch arm was nonetheless adopted as the exp009 seed for encoder consistency going forward (it also beat the incumbent by more head-to-head, +0.74 vs +0.45, though that difference is itself within noise). <em>(Update: this n=200 read was underpowered, not a null result — <a href="#exp016">exp016</a> re-scores these same two checkpoints on the high-power BGSage benchmark and finds a clear, significant edge for the 26ch arm on both PR and rollout MSE.)</em></p>
</section>
<section id="exp009" class="level2">
<h2 class="anchored" data-anchor-id="exp009">exp009 — scaled DAgger</h2>
<p><strong>Motivation.</strong> exp008 showed on-distribution DAgger works but returns only ~0.4–0.5 ppg over 15 slow rounds, and the <a href="#consolidation">consolidation</a> showed the accumulated labels held more than the incremental fine-tunes had extracted. exp009 restarts the loop from the consolidation 26ch arm to push the gains further and stress-test the method at scale, with four upgrades from the exp008 post-mortem.</p>
<p><strong>Setup.</strong> (<code>experiments/pipeline_exp009.sh</code>, 2026-07-10 → 07-21, GCP T4 VM.) 25 DAgger rounds warm-started from the consolidation 26ch seed, GNUBG 2-ply teacher, 50 eval sims. The upgrades: <strong>parallel label synthesis</strong> (14 worker processes shard each round — the ~10 h synth cap drops to ~4 h even at a 2× larger budget), <strong>doubles policy labels</strong> (the half-move labels <code>candidate_equities</code> already computes were discarded in exp008; the error profile priced that leak at ~0.85 ppg/game — now ~26% of each round’s labels carry policy targets, none discarded), <strong>best-val-epoch selection</strong> (every exp008 round overfit past epoch 1), and a <strong>2× round budget</strong> (120k labels/round). GNUBG benchmarked every 2nd round (n=100), milestone n=200 at rounds 6/18/25.</p>
<p><strong>Results.</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">round</th>
<th style="text-align: left;">vs seed (arena)</th>
<th style="text-align: left;">vs GNUBG 2-ply</th>
<th style="text-align: left;">n (GNUBG)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">62-38 +0.49</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">51-49 +0.14</td>
<td style="text-align: left;">28-72 -0.69</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">64-36 +0.51</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">70-30 +0.60</td>
<td style="text-align: left;">30-70 -0.62</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">63-37 +0.48</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">76-28 +0.78</td>
<td style="text-align: left;">83-117 -0.37</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">71-29 +0.78</td>
<td style="text-align: left;">36-64 -0.52</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">72-28 +0.72</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">70-30 +0.59</td>
<td style="text-align: left;">33-67 -0.65</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">57-43 +0.24</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">67-33 +0.52</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">63-37 +0.49</td>
<td style="text-align: left;">25-75 -0.81</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">67-33 +0.51</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">64-36 +0.44</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">70-30 +0.61</td>
<td style="text-align: left;">70-130 -0.50</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">67-33 +0.55</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">64-36 +0.45</td>
<td style="text-align: left;">31-69 -0.66</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">21</td>
<td style="text-align: left;">66-34 +0.51</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">22</td>
<td style="text-align: left;">70-30 +0.70</td>
<td style="text-align: left;">36-64 -0.51</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">23</td>
<td style="text-align: left;">71-29 +0.59</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">25</td>
<td style="text-align: left;">162-38 +1.49</td>
<td style="text-align: left;">70-130 -0.48</td>
<td style="text-align: left;">200</td>
</tr>
</tbody>
</table>
<p>(arena = 100 games vs the frozen consolidation 26ch seed; GNUBG every 2nd round, n=100, milestone n=200 at rounds 6/18/25; 50 eval sims. Blank cells are evals skipped when a VM preemption resumed past a completed round.)</p>
<div id="2c42dbf2" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Three readings:</p>
<ol type="1">
<li><strong>A large early gain, then a plateau.</strong> The gap to GNUBG halves in six rounds — −0.96 (seed) → <strong>−0.37 (round 6, n=200)</strong>, 41% wins — the project best, ~60% of the remaining gap to parity closed. But no later round beats it: rounds 8–25 oscillate in a −0.5 to −0.8 band, and the other two n=200 milestones (round 18 −0.50, round 25 −0.48) sit within ~1 SE of round 6. The doubles-policy fix plus the bigger budget bought the early jump; the loop then stopped compounding.</li>
<li><strong>The head-to-head keeps climbing even as the external gap doesn’t.</strong> Against the frozen seed the arena rises to +0.5–0.9 ppg by the late rounds — the net keeps beating its own history at 50 sims while its standing against GNUBG bounces. “Beats its predecessor” and “closes the external gap” are different claims.</li>
<li><strong>iter_0447 is buried 99-1 (+2.41 ppg)</strong> by the final round — the strongest self-play checkpoint now loses essentially every game.</li>
</ol>
<p><em>Ops aside.</em> The run spanned 11 days on a preemptible VM in a capacity-crunched zone — ~9 preemptions, all auto-recovered by a local watchdog, plus a spot-price spike that put the Phase A+B bill at ~kr.880 (~$128), 2–4× the estimate, most of it spent on the post-round-6 plateau. That motivated per-round cost projection + clean round-boundary budget/plateau stopping (<code>scripts/pipeline_budget.py</code>) for future runs.</p>
<p><strong>Interpretation.</strong> Scaling the loop confirmed the method and set a new best, but exposed its shape: DAgger with a warm-started, <em>ungated</em> loop makes its biggest correction early (here, the doubles-policy fix), then oscillates around a plateau rather than converging monotonically — nothing gates a round on <em>improving</em>, so the checkpoint advances even through regressions and the best (round 6) is a peak the run wandered away from. Two lessons carry forward: <strong>gate on eval</strong> (keep-best, not last) and the consolidation’s <strong>measure at n≥200</strong> (the n=100 rounds are individually too noisy to rank). The plateau ~0.4 ppg short of parity, teacher fixed at 2-ply, is the teacher-ceiling signal that motivates <a href="./training_analysis.html#what-happened-next">exp010</a>’s TD self-play.</p>
</section>
<section id="exp011b" class="level2">
<h2 class="anchored" data-anchor-id="exp011b">exp011b — 0-ply value distillation</h2>
<p><strong>Motivation.</strong> Two independent methods had stalled at the <em>same</em> place: <a href="#exp009">exp009</a> DAgger (−0.37 vs GNUBG-2-ply) and <a href="./training_analysis.html#exp010">exp010</a> TD self-play both plateaued ~0.3 ppg short of even 0-ply, and exp010 exposed <em>why</em> — the distilled nets predict equity well enough for MCTS but play <strong>0-ply badly</strong> (their value isn’t accurate at the margin between sibling moves). Is that plateau <strong>volume/fidelity-bound</strong> — the net <em>can</em> represent GNUBG’s value but was never given enough clean labels — or <strong>capacity-bound</strong>, a limit of the 10×256 architecture? Cloning GNUBG-<strong>0-ply</strong>’s value at a volume DAgger never reached separates the two.</p>
<p><strong>Setup.</strong> GNUBG plays itself at 0-ply — greedy, since the dice already fan out coverage — and every pre-roll position is recorded with GNUBG’s 0-ply outcome probabilities (<code>scripts/gen_gnubg_selfplay.py</code>); play <em>is</em> the label, so generation is net-free and cheap (~8M positions in ~7 h). <strong>Value-only</strong> (the value head is the whole player: 0-ply move selection, no policy head), a <strong>confound-free two-arm A/B</strong> from random init on the identical positions (<code>scripts/train_distill.py</code>): a <strong>scalar</strong> head (MSE against equity) vs a <strong>six-outcome</strong> softmax head (win/gammon/bg × win/lose — the multi-component target GNUBG and TD-Gammon use). Both arms trained the full <strong>3 epochs on a T4</strong>, keeping a per-epoch <code>ep{N}.pt</code> checkpoint and selecting the winner offline at n=1000. <em>(A first attempt — “exp011” — hit a 15 h iMac-CPU wall mid-first-epoch and was re-run to completion here. Artifacts: <code>experiments/exp011b-distill/</code>, benchmarked in <code>experiments/exp012b-benchmark/</code>.)</em></p>
<p><strong>Results.</strong> Both arms (epoch 3) benchmarked against GNUBG at 0- and 2-ply:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>net (ep3)</th>
<th>vs GNUBG-0-ply (n=6000)</th>
<th>vs GNUBG-2-ply (n=1000)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>six-outcome</strong></td>
<td><strong>−0.053 ± 0.046</strong></td>
<td>−0.064 ± 0.11</td>
</tr>
<tr class="even">
<td><strong>scalar</strong></td>
<td><strong>−0.050 ± 0.046</strong></td>
<td>−0.133 ± 0.11</td>
</tr>
</tbody>
</table>
<p>The two value heads are <strong>tied</strong> — cleanly at 0-ply (−0.050 vs −0.053, well inside ±0.046). At 2-ply the n=1000 estimates are too noisy (±0.11 each) to separate them: the −0.064 vs −0.133 gap sits inside the combined CI, not a real difference. (The six-outcome head was the marginally-selected winner; its n=1000 selection “+0.001” was winner’s-curse-inflated — honest 0-ply value −0.053.)</p>
<p><strong>Interpretation.</strong></p>
<ol type="1">
<li><strong>Near 0-ply parity — volume-bound, not capacity-bound.</strong> −0.053 clears the ~−0.3 wall that held across exp009 and exp010 decisively: the 10×256 architecture <em>can</em> represent GNUBG’s value; it just needed clean labels at volume. But it lands <strong>~0.05 short of parity</strong> (the n=6000 CI [−0.099, −0.007] excludes zero), and pure 0-ply distillation <strong>cannot go past its teacher</strong> (<a href="#v2b">you cannot distill past your teacher</a>). The residual is value precision at the margin between sibling moves, <em>not</em> missing coverage — the greedy generator’s dice already fan out the position space.</li>
<li><strong>The two heads tie — neither target distils better.</strong> So the six-outcome head is preferred downstream <strong>for the win/gammon/bg distribution it carries (needed for the cube), not because it plays stronger</strong> — measurably, it doesn’t. (This is the clean A/B the truncated first attempt couldn’t give.)</li>
<li><strong>2-ply search buys GNUBG little here.</strong> The 2-ply gap (−0.064) is only ~0.01 worse than the 0-ply gap (−0.053): at static 0-ply play this net is nearly as close to GNUBG-2-ply as to 0-ply.</li>
</ol>
<p><strong>What’s next.</strong> Going <em>past</em> the 0-ply teacher needs a signal <em>stronger</em> than 0-ply. <strong>TD self-play from this near-parity seed</strong> (<a href="./training_analysis.html#exp013">exp013</a>) has since been run: greedy TD showed no detectable movement over 39 batches, but the test wasn’t powered for the realistic ~0.05 ppg effect size — so exp010’s ~−0.3 attractor is ruled out (this seed never fell toward it) without the climb-vs-flat question being fully closed. Two levers remain: <strong>temperature&gt;0 TD</strong> (untested exploration) and <strong>2-ply distillation</strong> — run next as <a href="#exp014">exp014</a>.</p>
</section>
<section id="exp014" class="level2">
<h2 class="anchored" data-anchor-id="exp014">exp014 — does a 2-ply teacher fit as well as the 0-ply teacher?</h2>
<p><strong>Motivation.</strong> <a href="#exp011b">exp011b</a>’s 0-ply-distilled net lands <strong>~0.05 ppg short of GNUBG-0-ply parity</strong> and, by construction, 0-ply distillation cannot exceed its own teacher. The obvious lever is a stronger teacher: re-label the identical positions at GNUBG-<strong>2-ply</strong> (cache already generated and format-validated, <a href="./2ply_label_generation.html">2-ply label generation</a>) and distil that instead.</p>
<p><strong>Why fit quality, not ppg.</strong> The realistic 2-ply-over-0-ply margin is small: the same net measured <strong>−0.053 vs 0-ply and −0.064 vs 2-ply</strong> (<a href="#exp011b">exp011b</a>) — only ~0.011 ppg apart — and the 2-ply vs 0-ply <em>labels</em> on identical positions differ by just ~0.017 ppg mean-absolute. (That −0.053 figure is itself a solid, well-powered result — one checkpoint vs.&nbsp;a fixed external reference at n=6000, CI ±0.046, excluding zero. What’s <em>not</em> well-powered at feasible n is a <strong>paired comparison</strong> — resolving a difference this size <em>between two checkpoints</em>, which needs combining two independent SEs. <a href="./training_analysis.html#exp013">exp013</a> already showed that: n=6000 resolves such a paired δ≥0.05 at only ~33% power, and even n=24000 is marginal at the low end of this range.) That paired comparison is exactly what an 0-ply-vs-2-ply ppg test would be, so the <strong>primary metric here is deliberately a proxy, not raw play</strong>: can the scalar net fit 2-ply labels about as well as it fits 0-ply labels? GNUBG-2-ply being the stronger player is an external fact, not something this experiment measures — fitting it equally faithfully would indicate the 2-ply-distilled net is at least as strong, i.e.&nbsp;this proxy targets the <strong>sign</strong> of the effect, not its ppg magnitude. This is a deliberate, reasoned exception to the “primary metric must be unbiased raw play” convention, made explicit for that reason.</p>
<p><strong>Setup.</strong> Same recipe as <a href="#exp011b">exp011b</a>’s scalar arm (10×256, 3 epochs, lr=1e-3, batch 512, <code>scripts/train_distill.py</code>), trained <strong>twice from random init</strong> — once on <code>cache/</code> (0-ply labels), once on <code>cache_2ply/</code> (2-ply labels) — rather than warm-started, so the A/B stays confound-free exactly like exp011b’s own two-arm design. Both caches hold the <em>same</em> 8M self-play positions with byte-identical observations (verified), only the label ply differs. A fixed, seeded 25% holdout (<code>raccoon.data.cache_split.held_out_mask</code>, seed 14) is applied identically to both arms, so both train on the same 6M positions and are scored on the same held-out 2M.</p>
<p><strong>Primary metric (fixed up front):</strong> each net’s held-out R² against the labels it was actually trained on, n≈2M, at ep3 — the epoch <a href="#exp011b">exp011b</a> selected.</p>
<p><strong>Results.</strong> Held-out/train R² against each net’s own training labels, ep3:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>net (ep3)</th>
<th>target labels</th>
<th>held-out R² (n≈2M)</th>
<th>train R² (n=200k)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-ply-trained</td>
<td>0-ply</td>
<td><strong>0.9983</strong></td>
<td>0.9984</td>
</tr>
<tr class="even">
<td>2-ply-trained</td>
<td>2-ply</td>
<td><strong>0.9983</strong></td>
<td>0.9984</td>
</tr>
</tbody>
</table>
<p>Target-swap (held-out rows, scored against the <em>other</em> arm’s labels):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>net (ep3)</th>
<th>target labels</th>
<th>held-out R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-ply-trained</td>
<td>2-ply</td>
<td>0.9979</td>
</tr>
<tr class="even">
<td>2-ply-trained</td>
<td>0-ply</td>
<td>0.9981</td>
</tr>
</tbody>
</table>
<p>Supporting per-epoch curve (held-out R² against each net’s own training labels, subsampled to 200k rows for speed — not the headline):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>epoch</th>
<th>0-ply arm</th>
<th>2-ply arm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.9933</td>
<td>0.9942</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.9956</td>
<td>0.9981</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.9984</td>
<td>0.9983</td>
</tr>
</tbody>
</table>
<p>Held-out R² against each net’s own training labels is <strong>tied to 4 decimal places</strong> (0.9983 vs 0.9983); both improve monotonically and both select ep3. Train vs.&nbsp;held-out R² are equal for both arms (0.9984 vs 0.9983) — no detectable gap. Each net generalizes slightly less well to the <em>other</em> arm’s target labels than to its own (0.9979, 0.9981 vs.&nbsp;0.9983 against its own labels) — the expected direction, confirming both nets learned label-set-specific structure rather than a generic fit.</p>
<p><strong>Methodology check: train/holdout leakage.</strong> The holdout is a per-position coin flip, not per-game (<code>held_out_mask</code>), so no game is cleanly on one side: checked directly in one 500k-row shard, <strong>all 9,014 detected games have positions on both sides</strong>. This is not necessarily invalid — backgammon positions are Markovian, so a smooth value function generalizing to a same-game neighbor is legitimate, the same as generalizing to a similar position from a different game. A sharper case is <strong>exact duplicate positions</strong>: ~8% of held-out rows in that shard have a byte-identical twin in training (dominated by the fixed starting position, which recurs thousands of times). Checked directly whether this inflates R²: it does not — the duplicate subset actually scores <em>lower</em> (R²=0.9972) than the genuinely-novel subset (R²=0.9984), because it’s concentrated in a low-variance, early-game slice of the target distribution (equity std 0.13 vs.&nbsp;0.31); in absolute-error terms the model is if anything <em>more</em> accurate there (implied RMSE 0.007 vs.&nbsp;0.012). Whatever residual leakage remains applies identically to both arms (same games, same split), so it cannot bias the paired 0-ply-vs-2-ply comparison above — it only tempers any <em>absolute</em> “the net generalizes well” claim.</p>
<p><strong>Supporting sanity check (guards against a silently-broken net, not part of the hypothesis; <code>scripts/eval_gnubg0.py</code>, <code>scripts/eval_netarena.py</code>):</strong></p>
<ul>
<li>2-ply-trained net vs GNUBG-0-ply, raw ppg, n=3000: <strong>−0.0193</strong> (95% CI ±0.064)</li>
<li>2-ply-trained net vs 0-ply-trained net, head-to-head raw ppg, n=3000: <strong>+0.0290</strong> (2-ply’s POV; 95% CI ±0.064)</li>
</ul>
<p>Both intervals comfortably include zero — n=3000 isn’t powered for the ~0.05-scale effect discussed above, so neither result is a significant confirmation. But neither is a red flag either: both point estimates land in the expected direction (near-parity vs.&nbsp;GNUBG-0-ply; a small edge over the 0-ply-trained net head-to-head), and the net plays sensibly, not broken.</p>
<p><strong>Conclusion.</strong> <em>Can the scalar net fit 2-ply labels about as well as 0-ply labels?</em> → <strong>Yes</strong>: the 2-ply-trained net’s held-out R² against 2-ply labels (0.9983, n≈2M) equals the 0-ply-trained net’s held-out R² against 0-ply labels (0.9983, n≈2M), tied to 4 decimals — and the raw-ppg sanity checks (n=3000 each, underpowered but consistent) show no sign this is a broken or weaker net. Since GNUBG-2-ply is externally known to be the stronger player, this supports — but does not size — the 2-ply-distilled net being at least as strong as the 0-ply-distilled one.</p>
<p><strong>What’s next.</strong> Train the deliverable 2-ply net on the full 8M (no holdout) for maximum strength, to seed downstream work past whatever ceiling the 0-ply-distilled net had.</p>
</section>
<section id="exp015" class="level2">
<h2 class="anchored" data-anchor-id="exp015">exp015 — static PR benchmark against BGSage</h2>
<p><strong>Motivation.</strong> <a href="#exp014">exp014</a>’s held-out R² result (0.9983 vs 0.9983) shows the 2-ply-distilled net fits its teacher as well as the 0-ply-distilled net fits its own — evidence for the <em>sign</em> of a strength difference, not its size, and explicitly not a raw-play confirmation. Resolving that difference with raw ppg needs a <strong>paired</strong> comparison between the two checkpoints, and <a href="./training_analysis.html#exp013">exp013</a> already measured that kind of test at only ~33% power for a δ≈0.05 effect at n=6000 (n=24000 is marginal even at the low end). A static, per-decision benchmark against an external, high-precision reference sidesteps that noise floor entirely — the same reason human players and commercial bots (XG, GNUBG) report skill as a per-decision Performance Rating (PR) rather than raw match results. The BGSage money-game benchmark (500 Sage-3P vs Sage-3P self-play games, analysed by Sage at adaptive precision; a sibling repo, not part of this project) gives exactly that: a fixed, noise-free position set with a reference stronger than any engine under test.</p>
<p><strong>Why PR, not raw ppg, as the primary metric.</strong> This is a deliberate exception to the “primary metric must be raw play” convention, made explicit for that reason (mirroring <a href="#exp014">exp014</a>’s R² exception). It differs from the project’s previously-dropped “error-rate ppg” proxy: that one converted a per-decision error rate into a ppg estimate using a self-referential control variate (the evaluated net’s own pre-roll value against its own 1-ply lookahead), and that self-consistency failure is what made it biased. Here the reference (Sage rollout / 3-ply-team / 3-ply) is wholly external to every engine being scored and PR is reported in its own native units — no ppg conversion is attempted. The trade-off: PR measures move-selection skill on a fixed position set, not outcomes of complete games, so it is a <strong>proxy for playing strength</strong>, not playing strength itself; it is used here precisely because it is unbiased <em>and</em> far lower-variance than raw ppg for this comparison, not as a replacement for the raw-ppg standard elsewhere on this page.</p>
<p><strong>Setup.</strong> <code>scripts/eval_benchmark_pr.py</code> scores each engine on every checker decision in the benchmark: encode all candidate moves from the opponent’s (next-to-move) perspective, take the engine’s argmax, and score <code>error = max(0, best_cubeless_eq − chosen_cubeless_eq)</code> against Sage’s <code>cubeless_equity</code> reference (never Sage’s cubeful equity, which would penalize cubeless engines for a cube they don’t carry). PR = mean(error) × 500, GNUBG’s convention. Cube decisions are skipped (all engines here are cubeless). Four engines: GNUBG 0-ply and 2-ply (via <code>gnubg-nn</code>), and the two existing distilled checkpoints from this page — <strong>exp011b’s outcomes6/ep3</strong> (the head kept downstream per <a href="#exp011b">exp011b</a>) and <strong>exp014’s scalar_2ply/ep3</strong> (the confound-free A/B arm, <em>not</em> the still-untrained full-8M deliverable <a href="#exp014">exp014</a> flagged as its own next step — that remains open). The benchmark corpus: 500 games, 17,535 total decisions (14,693 checker + 2,842 cube); BGSage’s adaptive-precision scheme assigns each of the corpus’s 16,889 non-trivial decisions a reference tier — rollout (5,977), 3-ply-team/3T (3,260), or 3-ply/3P (7,652) — costlier tiers going to closer, more contested decisions. <em>(That corpus-wide tally covers checker + cube decisions together; the R² breakdown below reports checker-only candidate positions by tier, a different, larger denominator — see the counts in that table.)</em></p>
<p><em>(Correction, 2026-07-31: the original run behind this section actually scored <code>best.pt</code> for both distilled checkpoints, not <code>ep3.pt</code> as the paragraph above always intended — <code>best.pt</code> is an artifact of <code>train_distill.py</code>‘s noisy in-loop n=40-game selector (for the outcomes6 arm it happened to freeze at essentially the <code>ep1.pt</code> state and never update), not the properly cross-validated checkpoint that <a href="#exp011b">exp011b</a> and <a href="#exp011b">exp012b</a> actually select and every other section on this page reports against. Caught while <a href="#exp016">exp016</a> was re-deriving these same checkpoints’ numbers from scratch and couldn’t reproduce this section’s PR/MSE at all; confirmed by reproducing the original numbers exactly off <code>best.pt</code> on a subsample. The numbers below are now the correct <code>ep3.pt</code> re-run, saved with <code>--output</code> this time so the raw per-decision JSON is reproducible going forward — see <code>experiments/exp015-benchmark/results/</code>.)</em></p>
<p><strong>Results.</strong> Move selection, PR = mean(error) × 500 over all 14,693 checker decisions (lower is better), plus a per-game-plan breakdown:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Engine</th>
<th>PR</th>
<th>n</th>
<th>Blunders</th>
<th>purerace</th>
<th>racing</th>
<th>attacking</th>
<th>priming</th>
<th>anchoring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNUBG 2-ply</td>
<td>0.56</td>
<td>14,693</td>
<td>11</td>
<td>0.05</td>
<td>0.80</td>
<td>0.50</td>
<td>0.47</td>
<td>0.76</td>
</tr>
<tr class="even">
<td>GNUBG 0-ply</td>
<td>2.14</td>
<td>14,693</td>
<td>95</td>
<td>0.16</td>
<td>2.72</td>
<td>2.15</td>
<td>2.66</td>
<td>2.32</td>
</tr>
<tr class="odd">
<td>exp014 (2-ply dist)</td>
<td>2.16</td>
<td>14,693</td>
<td>96</td>
<td>1.13</td>
<td>2.32</td>
<td>1.97</td>
<td>2.68</td>
<td>2.44</td>
</tr>
<tr class="even">
<td>exp011b (0-ply dist)</td>
<td>2.75</td>
<td>14,693</td>
<td>149</td>
<td>0.85</td>
<td>3.15</td>
<td>2.65</td>
<td>3.46</td>
<td>3.02</td>
</tr>
</tbody>
</table>
<p>(n per game plan: purerace 1,816, racing 3,120, attacking 4,111, priming 2,453, anchoring 3,193.)</p>
<p>Eval accuracy — R² / MSE of each engine’s raw value estimate against Sage’s <code>cubeless_equity</code>, across all 327,451 candidate post-move positions from the same 14,693 checker decisions, split by the reference tier of the parent decision:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Engine</th>
<th>R² (rollout)</th>
<th>MSE</th>
<th>n</th>
<th>R² (3T)</th>
<th>MSE</th>
<th>n</th>
<th>R² (3P)</th>
<th>MSE</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNUBG 2-ply</td>
<td>0.9969</td>
<td>0.0019</td>
<td>149,113</td>
<td>0.9948</td>
<td>0.0017</td>
<td>61,917</td>
<td>0.9988</td>
<td>0.0003</td>
<td>116,421</td>
</tr>
<tr class="even">
<td>GNUBG 0-ply</td>
<td>0.9965</td>
<td>0.0021</td>
<td>149,113</td>
<td>0.9939</td>
<td>0.0019</td>
<td>61,917</td>
<td>0.9919</td>
<td>0.0022</td>
<td>116,421</td>
</tr>
<tr class="odd">
<td>exp014 (2-ply dist)</td>
<td>0.9927</td>
<td>0.0044</td>
<td>149,113</td>
<td>0.9850</td>
<td>0.0048</td>
<td>61,917</td>
<td>0.9814</td>
<td>0.0051</td>
<td>116,421</td>
</tr>
<tr class="even">
<td>exp011b (0-ply dist)</td>
<td>0.9935</td>
<td>0.0039</td>
<td>149,113</td>
<td>0.9870</td>
<td>0.0042</td>
<td>61,917</td>
<td>0.9839</td>
<td>0.0044</td>
<td>116,421</td>
</tr>
</tbody>
</table>
<p><strong>Comparability note.</strong> These PR numbers are not directly comparable to BGSage’s own published figures (Sage 3T ≈ 0.21 PR): this run scores checker decisions only against <code>cubeless_equity</code>, while BGSage’s own figures are cubeful and include cube decisions. The 3P reference tier is Sage 3-ply — a different engine from our GNUBG teacher, used here only as one of three adaptive-precision reference tiers.</p>
<p><strong>Interpretation.</strong> Two distilled nets against an external, static reference give a genuinely two-metric read, not a clean reproduction of <a href="#exp014">exp014</a>’s ordering. On <strong>move selection</strong>, exp014 (2-ply-distilled) beats exp011b (0-ply-distilled) — PR 2.16 vs 2.75 — and comes within noise of GNUBG-0-ply itself (PR 2.14), a much closer read than fit-quality alone suggests. But per-plan, that aggregate near-parity is driven by racing/attacking/priming/anchoring, where exp014 sits roughly on par with (racing, attacking: even fractionally <em>better</em> than) GNUBG-0-ply’s own PR; <strong>pure-race positions remain a stark, specific weak point for both distilled nets</strong> (exp014 1.13, exp011b 0.85) — 5–7× GNUBG-0-ply’s race PR (0.16) — even though races have no contact and should be the easiest category for a value function, an open puzzle called out below. On raw <strong>value-fit to the rollout reference</strong> (R²/MSE), the ordering actually <strong>flips</strong>: exp011b edges out exp014 (R² 0.9935 vs 0.9927, MSE 0.0039 vs 0.0044) — the 0-ply-distilled net fits the <em>external</em> rollout equity slightly better than the 2-ply-distilled net does, despite training on a weaker teacher. This doesn’t contradict exp014’s own held-out R² result (which compared each net to its <em>own</em> training target, tied at 0.9983 vs 0.9983) — it’s a different quantity, fit against a reference neither net trained on — but it demonstrates cleanly that global calibration (R²/MSE) and within-decision move-selection (PR) measure different things and can disagree, echoed by <a href="#exp016">exp016</a>’s value-head panel.</p>
<p><strong>Conclusion.</strong> <em>Does the 2-ply-distilled net actually play better than the 0-ply-distilled net, independent of exp014’s R² proxy?</em> → <strong>Yes on move selection, no on rollout fit-quality</strong>: exp014 outscores exp011b on PR (2.16 vs 2.75, and near GNUBG-0-ply’s own 2.14) — the metric that actually measures what the hypothesis asks (does it <em>play</em> better) — but exp011b fits the external rollout reference slightly better (R² 0.9935 vs 0.9927, MSE 0.0039 vs 0.0044). The two metrics disagree on which net is “better,” a genuine finding rather than noise (both scored on identical n=14,693 decisions / n=149,113 rollout positions): PR settles the playing-strength question this section asked, but the R²/MSE reversal means exp014’s held-out-R² sign claim doesn’t transfer cleanly to an external reference — an open tension, not a clean confirmation. The raw-ppg <em>size</em> of either gain — like the full-8M deliverable training — is still open.</p>
</section>
<section id="exp016" class="level2">
<h2 class="anchored" data-anchor-id="exp016">exp016 — revisiting old A/B pairs at BGSage power</h2>
<p><strong>Motivation.</strong> <a href="#exp015">exp015</a> showed the BGSage static benchmark resolves comparisons at far higher power than raw ppg, at zero play cost. Two earlier A/B pairs on this page were called <em>ties</em> by underpowered play metrics: exp011b’s scalar-vs-six-outcome value head (tied on GNUBG-0-ply ppg, n=6000, ±0.046) and the <a href="#feature-ablation">feature ablation</a>’s handcrafted channels, re-tested at production scale in the <a href="#consolidation">consolidation</a> (tied on an n=200 GNUBG match, ±0.5 ppg). <strong>One hypothesis:</strong> does the BGSage rollout tier resolve a real difference in either pair that the underpowered play metric left as a tie?</p>
<p><strong>Setup.</strong> Two single-seed, production-scale (10×256) pairs, each differing in exactly one factor, re-scored on the full BGSage benchmark (<code>scripts/eval_benchmark_pr.py --dump-dir</code>, extended this experiment to also dump per-candidate predictions for paired analysis):</p>
<ul>
<li><strong>Panel A — exp011b value head</strong>: <code>scalar/ep3.pt</code> vs <code>outcomes6/ep3.pt</code> (both 26ch).</li>
<li><strong>Panel B — handcrafted features</strong>: the consolidation A/B, <code>17ch/pretrained_v2.pt</code> (base-only) vs <code>26ch/pretrained_v2.pt</code> (all 26 channels), both trained on the identical 844k-example label pool.</li>
</ul>
<p>Two co-headline metrics (<code>scripts/exp016_paired_mse.py</code>), each reported as a delta between the two checkpoints with a bootstrap 95% CI (B=10,000) — resampling the data with replacement thousands of times and recomputing the delta each time shows how much it wobbles, i.e.&nbsp;whether the difference is real or could be noise. The wrinkle: each decision has 2–773 candidate moves sharing one board, so those candidates aren’t independent — resampling at the candidate level would treat 149,113 correlated rows as if they were independent and understate the noise. The fix is to resample whole <strong>decisions</strong> (all of a decision’s candidates move together), giving 5,695 independent units instead. As a more conservative cross-check, a second bootstrap resamples whole <strong>games</strong> (475 of them, since decisions within a game are sequential too) — reported alongside, and it confirms the decision-level result:</p>
<ol type="1">
<li><strong>Rollout-tier value MSE</strong>, candidate-weighted (n=149,113 candidates / 5,695 decisions).</li>
<li><strong>PR</strong> (move-selection error × 500, all tiers, n=14,693) — objective-neutral, since rollout-MSE is literally the scalar head’s own training loss and would structurally favor a scalar-headed arm on fit quality alone. <strong>A strength difference is only claimed when MSE and PR agree in sign.</strong></li>
</ol>
<p><strong>Panel A — exp011b value head</strong> (n=5695 rollout decisions / 149113 candidates, PR over n=14693 decisions):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 25%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">scalar</th>
<th style="text-align: right;">outcomes6</th>
<th style="text-align: right;">Δ (A−B)</th>
<th style="text-align: left;">95% CI (decision)</th>
<th style="text-align: left;">excl. 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rollout MSE</td>
<td style="text-align: right;">0.0058</td>
<td style="text-align: right;">0.0039</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: left;">[+0.0017, +0.0023]</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">PR (all tiers)</td>
<td style="text-align: right;">2.62</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: left;">[-0.25, -0.00]</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
<p><strong>Panel B — handcrafted features (consolidation A/B)</strong> (n=5695 rollout decisions / 149113 candidates):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 27%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">17ch</th>
<th style="text-align: right;">26ch</th>
<th style="text-align: right;">Δ (A−B)</th>
<th style="text-align: left;">95% CI (decision)</th>
<th style="text-align: left;">excl. 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rollout MSE</td>
<td style="text-align: right;">0.1205</td>
<td style="text-align: right;">0.0748</td>
<td style="text-align: right;">0.0457</td>
<td style="text-align: left;">[+0.0401, +0.0512]</td>
<td style="text-align: left;">yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">PR (all tiers)</td>
<td style="text-align: right;">28.98</td>
<td style="text-align: right;">21.59</td>
<td style="text-align: right;">7.39</td>
<td style="text-align: left;">[+6.42, +8.37]</td>
<td style="text-align: left;">yes</td>
</tr>
</tbody>
</table>
<p>Per-game-plan breakdown (supporting; decision-level bootstrap only, narrower n per plan so wider CIs):</p>
<p>Panel B by game plan (17ch − 26ch):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 9%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">plan</th>
<th style="text-align: left;">n (roll/all)</th>
<th style="text-align: right;">MSE Δ</th>
<th style="text-align: left;">MSE CI</th>
<th style="text-align: right;">PR Δ</th>
<th style="text-align: left;">PR CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">purerace</td>
<td style="text-align: left;">1153/1816</td>
<td style="text-align: right;">0.0538</td>
<td style="text-align: left;">[+0.0315, +0.0780]</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: left;">[-1.31, +3.07]</td>
</tr>
<tr class="even">
<td style="text-align: left;">racing</td>
<td style="text-align: left;">1229/3120</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: left;">[+0.0334, +0.0596]</td>
<td style="text-align: right;">9.6</td>
<td style="text-align: left;">[+7.35, +11.92]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attacking</td>
<td style="text-align: left;">1121/4111</td>
<td style="text-align: right;">0.0575</td>
<td style="text-align: left;">[+0.0483, +0.0670]</td>
<td style="text-align: right;">8.09</td>
<td style="text-align: left;">[+6.08, +10.19]</td>
</tr>
<tr class="even">
<td style="text-align: left;">priming</td>
<td style="text-align: left;">739/2453</td>
<td style="text-align: right;">0.0718</td>
<td style="text-align: left;">[+0.0597, +0.0841]</td>
<td style="text-align: right;">12.88</td>
<td style="text-align: left;">[+10.18, +15.61]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">anchoring</td>
<td style="text-align: left;">1453/3193</td>
<td style="text-align: right;">0.0144</td>
<td style="text-align: left;">[+0.0089, +0.0200]</td>
<td style="text-align: right;">3.79</td>
<td style="text-align: left;">[+2.38, +5.19]</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation.</strong> <strong>Panel A is not jointly resolved.</strong> MSE and PR disagree in sign: outcomes6 has <em>lower</em> rollout MSE than scalar (0.0039 vs 0.0058, the opposite of the expected training-objective bias, since scalar trains directly against equity-MSE), but scalar has <em>lower</em> (better) PR (2.62 vs 2.75). Both deltas individually clear their bootstrap CIs — this is a real, higher-power-detected difference, not noise — but the two metrics point in opposite directions on which head “plays better,” so per the pre-registered rule this pair stays undecided; the practical choice (outcomes6, for its win/gammon/bg distribution) is unaffected either way. <strong>Panel B is cleanly resolved</strong>: 26ch beats 17ch on both MSE (0.0748 vs 0.1205) and PR (21.6 vs 29.0), both deltas an order of magnitude past their CIs — the “washes out at scale” call from the consolidation section was a real effect hiding under an n=200 play-metric’s noise floor, not a null result. Per-plan, the MSE gap is significant in every game plan including pure races (smallest of the five, but still excludes zero) — so the handcrafted channels (which include a pip-count feature specifically motivated by races) help fit quality even in the category they were meant for — but the PR gap is <em>not</em> significant for purerace or racing specifically, only for attacking/priming/anchoring; the aggregate PR win is driven by contact-heavy positions, not races.</p>
<p><strong>Conclusion.</strong> <em>Does BGSage rollout power resolve either pair’s underpowered tie?</em> → <strong>Panel A (value head): no</strong> — MSE and PR now disagree in sign at high power, an open tension rather than a resolved winner. <strong>Panel B (handcrafted features): yes</strong> — 26ch clearly beats 17ch on both value-fit and move-selection at production scale (MSE 0.0748 vs 0.1205, PR 21.6 vs 29.0, n=149,113/14,693), reversing the “features wash out at scale” read; the gain concentrates in contact-heavy plans on PR, though the value-fit gain holds even in pure races.</p>
</section>
<section id="exp017" class="level2">
<h2 class="anchored" data-anchor-id="exp017">exp017 — does 40M 2-ply distillation beat 8M, and fix the race gap?</h2>
<p><strong>Motivation.</strong> <a href="#exp015">exp015</a> scored <a href="#exp014">exp014</a>’s 2-ply-distilled net — trained on <strong>8M</strong> GNUBG-2-ply value labels — at <strong>PR 2.16 / rollout-MSE 0.0044</strong>, against the GNUBG-2-ply teacher’s 0.56 / 0.0019. That 2.3× rollout-MSE gap is the signature of a net still <strong>underfitting</strong> its (harder) 2-ply target, not one sitting at a representational wall: the same 10×256 architecture already reached near-0-ply parity on 8M 0-ply labels (<a href="#exp011b">exp011b</a>), so capacity is not the obvious ceiling. The obvious lever is <strong>more of the same labels</strong> — this run distils the full <strong>40M</strong> 2-ply corpus (5× the data: run1 plus the 32M <em>new</em> self-play positions of run2/run3, all 2-ply — see <a href="#data-and-methodology">data</a>) and asks whether the extra data buys a stronger evaluator.</p>
<p>The primary question is a <strong>plateau</strong> question: is BGSage error still descending at the last epoch (→ more epochs/data are worth it) or has it flattened (→ the bottleneck is capacity or the scalar target, not data)? The secondary question is <strong>specific</strong>: <a href="#exp015">exp015</a>‘s per-plan breakdown flagged pure races as both distilled nets’ worst category (exp014 1.13 vs GNUBG-0-ply’s 0.16). But a race fix is only real if it does not come <strong>at the expense of the contact plans</strong> — so the read below is the <em>full five-plan PR profile per epoch</em>, not pure-race alone; a genuine improvement lowers pure-race PR while racing / attacking / priming / anchoring hold or improve.</p>
<p><strong>Setup.</strong> The same recipe as <a href="#exp014">exp014</a>’s scalar arm (10×256, scalar value head, lr 1e-3), on the 40M cache. The run was budgeted at 20 epochs / 72 h cumulative wall on a T4 spot VM and stopped on the <strong>72 h cap after 14 complete epochs</strong> (<code>ep1</code>–<code>ep14</code>); every epoch checkpoint is scored on the full BGSage benchmark by <code>experiments/score_exp017.sh</code> → <code>experiments/exp017-benchmark/results/</code>, and the run’s own shard-level training log (<code>experiments/exp017-distill/logs/distill_log.jsonl</code>) supplies the supporting loss curve. The <strong>anchor</strong> is exp014’s 8M <code>scalar_2ply/ep3</code> (the same checkpoint <a href="#exp015">exp015</a> scored — re-scored here as a pipeline check), and the GNUBG 0-/2-ply and exp011b rows are carried verbatim from <a href="#exp015">exp015</a>’s results so the tables extend the identical ladder. Pre-registered selection: <strong>best epoch = minimum overall PR</strong> (n=14,693); rollout-MSE (n≈149k) is reported alongside, and per <a href="#exp015">exp015</a>/<a href="#exp016">exp016</a> a strength claim is only clean when PR and MSE agree in sign.</p>
<p><strong>Results.</strong></p>
<p><em>Move selection</em> — PR = mean(error) × 500 over 14,693 checker decisions (lower is better), with the per-game-plan breakdown; reference rows carried from <a href="#exp015">exp015</a>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Engine</th>
<th style="text-align: right;">PR</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Blunders</th>
<th style="text-align: right;">purerace</th>
<th style="text-align: right;">racing</th>
<th style="text-align: right;">attacking</th>
<th style="text-align: right;">priming</th>
<th style="text-align: right;">anchoring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNUBG 0-ply</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: right;">2.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp014 (8M, 2-ply)</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">2.68</td>
<td style="text-align: right;">2.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp011b (0-ply)</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">2.65</td>
<td style="text-align: right;">3.46</td>
<td style="text-align: right;">3.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp017 ep12 (best PR)</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp017 ep14 (last)</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.23</td>
</tr>
</tbody>
</table>
<p><em>Eval accuracy</em> — R² / MSE of each engine’s raw value estimate vs Sage’s <code>cubeless_equity</code>; rollout tier is the headline (n≈149k), 3T / 3P alongside:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Engine</th>
<th style="text-align: right;">R² (rollout)</th>
<th style="text-align: right;">MSE (rollout)</th>
<th style="text-align: right;">R² (3T)</th>
<th style="text-align: right;">MSE (3T)</th>
<th style="text-align: right;">R² (3P)</th>
<th style="text-align: right;">MSE (3P)</th>
<th style="text-align: right;">n (roll)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: right;">0.9969</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9948</td>
<td style="text-align: right;">0.0017</td>
<td style="text-align: right;">0.9988</td>
<td style="text-align: right;">0.0003</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNUBG 0-ply</td>
<td style="text-align: right;">0.9965</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">0.9939</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9919</td>
<td style="text-align: right;">0.0022</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp014 (8M, 2-ply)</td>
<td style="text-align: right;">0.9927</td>
<td style="text-align: right;">0.0044</td>
<td style="text-align: right;">0.985</td>
<td style="text-align: right;">0.0048</td>
<td style="text-align: right;">0.9814</td>
<td style="text-align: right;">0.0051</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp011b (0-ply)</td>
<td style="text-align: right;">0.9935</td>
<td style="text-align: right;">0.0039</td>
<td style="text-align: right;">0.987</td>
<td style="text-align: right;">0.0042</td>
<td style="text-align: right;">0.9839</td>
<td style="text-align: right;">0.0044</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp017 ep12 (best PR)</td>
<td style="text-align: right;">0.9966</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">0.9938</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.9947</td>
<td style="text-align: right;">0.0015</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp017 ep14 (last)</td>
<td style="text-align: right;">0.9967</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.9942</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9953</td>
<td style="text-align: right;">0.0013</td>
<td style="text-align: right;">149113</td>
</tr>
</tbody>
</table>
<p><em>Per-epoch curve</em> — the plateau and the race-vs-contact trade-off in numbers (overall + per-plan PR, rollout MSE, ep1 → ep14):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">epoch</th>
<th style="text-align: right;">PR</th>
<th style="text-align: right;">purerace</th>
<th style="text-align: right;">racing</th>
<th style="text-align: right;">attacking</th>
<th style="text-align: right;">priming</th>
<th style="text-align: right;">anchoring</th>
<th style="text-align: right;">rollout MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">0.0027</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.33</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">0.0023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">0.0023</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">0.0023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.0021</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.0022</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.0021</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.26</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">0.0021</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.002</td>
</tr>
</tbody>
</table>
<p>The same curve as a figure — <strong>top panel</strong>: each game plan’s PR per epoch, with that plan’s 8M anchor as a dotted line in the same colour, so a curve sitting below its own dotted line means 40M improved that plan, and a race fix bought at the contact plans’ expense would show one curve crossing back above; <strong>middle panel</strong>: rollout value-fit MSE against the GNUBG teacher references; <strong>bottom panel</strong> (supporting, not a strength metric): the run’s own training loss — mean MSE against its 2-ply labels across each epoch’s ~86 shard records, log scale — which says whether <em>optimisation</em> was still making progress, a separate question from whether the benchmark was.</p>
<div id="37a0047a" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong></p>
<p><em>Pipeline check.</em> The exp014 8M anchor re-scores to PR 2.16 / rollout-MSE 0.0044 — identical to <a href="#exp015">exp015</a>, so both runs’ numbers sit on one ladder.</p>
<p><em>Headline.</em> 40M is a transformation, not a nudge. The best epoch, <strong>ep12</strong>, scores overall <strong>PR 0.93</strong> against the anchor’s 2.16 — past GNUBG-0-ply’s own 2.14, and 77% of the way from the anchor to the GNUBG-2-ply teacher’s 0.56. Rollout-tier MSE bottoms at <strong>0.00190</strong> (ep11, with ep8 tied to three significant figures), against 0.0044 for 8M and 0.00209 for GNUBG-0-ply. That is within 2% of the teacher’s 0.00187 — the same 0.0019 at the precision the tables print, though the teacher stays fractionally ahead. So the 8M net was badly <em>underfit</em>, exactly as its 2.3× MSE gap warned, and the 8M PR ≈ GNUBG-0-ply coincidence was never a searchless ceiling.</p>
<p><em>(a) Would more epochs help?</em> <strong>Probably, slightly — and only one of the two curves had actually stopped.</strong> Rollout MSE genuinely is flat: a linear fit over ep6–14 gives −1.6 ×10⁻⁵ per epoch (t = −1.3), and over ep8–14 the sign reverses. But PR is <strong>still descending at the cap</strong> — −0.0082 per epoch over ep6–14 (SE 0.0020, t = −4.0), with mean(ep12–14) = 0.946 against mean(ep6–8) = 0.999. Fitting PR against epoch as a power law above the teacher’s 0.56 (β = 0.38, R² = 0.97) puts ep20 at ≈0.88 and ep40 at ≈0.80: real, but at sharply diminishing returns per GPU-hour. The training loss says the same thing about optimisation — still −25% from ep8 to ep14, and a 15th epoch within 0.3% of ep14, after falling 28.5 → 1.5 ×10⁻⁴ across the run. <em>(The benchmark is a fixed, deterministically-scored position set, so this epoch-to-epoch scatter is real checkpoint-to-checkpoint variation, not measurement noise; a decision-level CI on any single epoch pair needs the paired bootstrap of <a href="#exp016">exp016</a>.)</em></p>
<p>What the run does establish is that the two curves <strong>separated</strong>: the value head’s global calibration stopped improving around ep8 while its move selection kept sharpening. So the epochs after ~ep8 are not buying better equity calibration, and by ep14 the net sits ~12× closer to its training labels (1.5 ×10⁻⁴) than to the rollout reference (19 ×10⁻⁴) — in-sample against out-of-sample, so not like-for-like, but far too wide a ratio for the residual benchmark error to be a failure to fit the labels. Part of what remains is teacher-vs-rollout disagreement plus the 2-ply search GNUBG runs <em>at play time</em> — but, per the conclusion below, that is no longer the <em>whole</em> remainder, since the epoch and data levers both still have measurable travel.</p>
<p><em>(b) Was the race fix paid for elsewhere?</em> No — every plan improves together (ep12 vs anchor: priming −1.67, anchoring −1.24, racing −1.22, attacking −1.14, purerace −0.84). Pure race, <a href="#exp015">exp015</a>’s stark outlier at 1.13 — 7× GNUBG-0-ply’s 0.16, 21× the 2-ply teacher’s 0.05 — falls to <strong>0.29</strong>. That weakness was a data/underfitting artifact resolved by scale, not a structural blind spot. It is, though, the one plan still <em>behind</em> its GNUBG-0-ply reference: racing, attacking, priming and anchoring have all passed theirs (1.11 vs 2.72, 0.82 vs 2.15, 1.00 vs 2.66, 1.19 vs 2.32), while pure race sits at 0.29 against 0.16.</p>
<p><em>(c) Do the two metrics agree?</em> <strong>On the result yes, on convergence no.</strong> Both put 40M far ahead of 8M by a wide margin, unlike <a href="#exp015">exp015</a>/<a href="#exp016">exp016</a> where PR and MSE disagreed in <em>sign</em> — that is what makes the headline clean. But they disagree about whether the run was finished: from ep8 rollout MSE is flat while PR keeps falling (above). Their epoch-to-epoch minima are anti-aligned too — PR’s minimum at ep12 sits on a local MSE bump (0.00206), while MSE’s minimum is ep11 (PR 0.97) — so ep11-vs-ep12 as the deliverable is arbitrary within noise, not a resolved ranking. “The run had converged” is a claim only the MSE curve supports.</p>
<p><strong>Conclusion.</strong> <em>Does scaling 2-ply distillation 8M→40M lower BGSage error and fix pure races without trading off other plans?</em> → <strong>Yes, decisively — and it plateaus.</strong> Best epoch ep12 = <strong>PR 0.93</strong> (from the 8M anchor’s 2.16, below GNUBG-0-ply’s own 2.14) with rollout-MSE bottoming at <strong>0.00190</strong> at ep11, from 0.0044 — within 2% of the GNUBG-2-ply teacher’s 0.00187, and past GNUBG-0-ply’s 0.00209; n=14,693 / n≈149k. All five game plans improve together — pure race 1.13→0.29 — so there is no trade-off and the race anomaly was underfitting, not structure.</p>
<p><strong>But neither lever is spent, and this run does not show that it is.</strong> Rollout MSE flattens by ~ep8; PR does not, still falling −0.0082/epoch over ep6–14 (t = −4.0) when the 72 h cap hit, with a power-law fit putting ep20 at ≈0.88. On the data axis there are only <strong>two points</strong> (8M→2.16, 40M→0.93), which cannot distinguish a curve from a line: extrapolating them puts 80M at ≈0.76 floored at the teacher’s 0.56, or ≈0.65 unfloored. And the two points are themselves <strong>confounded</strong> — <a href="#exp014">exp014</a>’s anchor ran 3 epochs to this run’s 12, so 5× the data arrived with 20× the gradient steps, and “volume was the bottleneck” is not cleanly separated from “optimisation budget was”. A presentation-matched glance favours volume (exp017 ep1, one pass over 40M, scores 1.61 against the anchor’s 2.16 for three passes over 8M — 25% better PR on 1.7× the presentations) but that is suggestive, not a matched test. So the residual 0.93→0.56 gap is <em>part</em> play-time 2-ply search and <em>part</em> untapped epochs and labels, in an unknown split. (Static-benchmark PR/MSE, not raw ppg — the fair-beat ppg confirmation at matched search remains the open finish.)</p>
</section>
<section id="exp018" class="level2">
<h2 class="anchored" data-anchor-id="exp018">exp018 — does the six-outcome head match scalar at 40M, and do ten more epochs help?</h2>
<p><strong>Motivation.</strong> <a href="#exp017">exp017</a> produced the page’s strongest evaluator but with a <strong>scalar</strong> value head: it emits a cubeless equity and nothing else, so it cannot feed cube decisions, which need the win/gammon/backgammon split. That made “no cube-capable head at current scale” the binding blocker rather than more data. The fix costs no new labels — the 2-ply shards already carry <code>outcomes6</code> targets alongside <code>equity</code> — so re-running exp017’s recipe with <code>--value-head outcomes6</code> produces the cube-capable deliverable <em>and</em> settles two questions pre-registered in <code>experiments/pipeline_exp018.sh</code> before the run started:</p>
<ul>
<li><strong>Q1 (head)</strong> — does outcomes6 match scalar at 40M? <a href="#exp016">exp016</a> left this unresolved at 8M, where PR and MSE disagreed.</li>
<li><strong>Q2 (epochs)</strong> — <a href="#exp017">exp017</a> stopped on its 72 h wall cap after 14 epochs with PR still descending (−0.0082/epoch over ep6–14, t = −4.0), <em>not</em> on convergence, so “is 40M enough epochs?” was unanswered. A power-law fit predicted ≈0.09 further PR against an epoch-to-epoch scatter of SD ≈0.016 — powered, if the trend held.</li>
</ul>
<p><strong>Setup.</strong> Identical to <a href="#exp017">exp017</a> in every respect except the value head and the epoch budget (24, against exp017’s 20-capped-at-14): same 40M 2-ply corpus, same 10×256 net, same lr 1e-3, and critically the <strong>same shard order</strong> (<code>--shuffle-seed 20</code>; <code>epoch_order()</code> is deterministic in (seed, epoch)), so exp018 ep<em>k</em> and exp017 ep<em>k</em> saw identical shards in identical order — a matched comparison, not two unrelated runs. The run completed all <strong>24 epochs in 120.4 h</strong> on a T4 spot VM, stopping on the epoch budget rather than the 200 h insurance cap that truncated exp017. Every epoch checkpoint is scored on the full BGSage benchmark by <code>experiments/score_exp018.sh</code> → <code>experiments/exp018-benchmark/results/</code>; GNUBG 0-/2-ply reference rows are carried verbatim from <a href="#exp015">exp015</a> and exp017’s per-epoch rows from <code>experiments/exp017-benchmark/results/</code>, all at identical <em>n</em>, so every number extends one ladder.</p>
<p>Pre-registered readings, applied as written: primary metric <strong>BGSage checker PR</strong> (n=14,693), best epoch = <strong>minimum PR</strong>; rollout-tier MSE (n≈149k) is secondary and read <strong>asymmetrically</strong> for Q1, because it is literally the <em>scalar</em> arm’s own training objective and so favours exp017 at equal strength — outcomes6 winning it is strong evidence, scalar winning it is ambiguous. On the record from the same file: <code>train_distill.py</code> does not seed model init and this is one run per arm, so only a Q1 gap <strong>clearly exceeding the ~0.016 PR scatter</strong> reads as a head effect.</p>
<p><strong>Results.</strong></p>
<p><em>Move selection</em> — PR = mean(error) × 500 over 14,693 checker decisions (lower is better), with the per-game-plan breakdown; reference rows carried from <a href="#exp015">exp015</a> and <a href="#exp017">exp017</a>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Engine</th>
<th style="text-align: right;">PR</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Blunders</th>
<th style="text-align: right;">purerace</th>
<th style="text-align: right;">racing</th>
<th style="text-align: right;">attacking</th>
<th style="text-align: right;">priming</th>
<th style="text-align: right;">anchoring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNUBG 0-ply</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">2.66</td>
<td style="text-align: right;">2.32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp014 (8M, 2-ply)</td>
<td style="text-align: right;">2.16</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">2.68</td>
<td style="text-align: right;">2.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp011b (0-ply)</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">2.65</td>
<td style="text-align: right;">3.46</td>
<td style="text-align: right;">3.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp017 ep12 (scalar, best PR)</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp018 ep22 (outcomes6, best PR)</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">1.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp018 ep24 (outcomes6, last)</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">14693</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">1.35</td>
</tr>
</tbody>
</table>
<p><em>Eval accuracy</em> — R² / MSE of each engine’s raw value estimate vs Sage’s <code>cubeless_equity</code>; rollout tier is the headline (n≈149k). For exp018 the value estimate is the equity implied by the six-outcome distribution, so this row is a like-for-like comparison of what each net would actually play on:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Engine</th>
<th style="text-align: right;">R² (rollout)</th>
<th style="text-align: right;">MSE (rollout)</th>
<th style="text-align: right;">R² (3T)</th>
<th style="text-align: right;">MSE (3T)</th>
<th style="text-align: right;">R² (3P)</th>
<th style="text-align: right;">MSE (3P)</th>
<th style="text-align: right;">n (roll)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: right;">0.9969</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9948</td>
<td style="text-align: right;">0.0017</td>
<td style="text-align: right;">0.9988</td>
<td style="text-align: right;">0.0003</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNUBG 0-ply</td>
<td style="text-align: right;">0.9965</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">0.9939</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9919</td>
<td style="text-align: right;">0.0022</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp014 (8M, 2-ply)</td>
<td style="text-align: right;">0.9927</td>
<td style="text-align: right;">0.0044</td>
<td style="text-align: right;">0.985</td>
<td style="text-align: right;">0.0048</td>
<td style="text-align: right;">0.9814</td>
<td style="text-align: right;">0.0051</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp011b (0-ply)</td>
<td style="text-align: right;">0.9935</td>
<td style="text-align: right;">0.0039</td>
<td style="text-align: right;">0.987</td>
<td style="text-align: right;">0.0042</td>
<td style="text-align: right;">0.9839</td>
<td style="text-align: right;">0.0044</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp017 ep12 (scalar, best PR)</td>
<td style="text-align: right;">0.9966</td>
<td style="text-align: right;">0.0021</td>
<td style="text-align: right;">0.9938</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.9947</td>
<td style="text-align: right;">0.0015</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp018 ep19 (outcomes6, best MSE)</td>
<td style="text-align: right;">0.9968</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9941</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.995</td>
<td style="text-align: right;">0.0014</td>
<td style="text-align: right;">149113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp018 ep24 (outcomes6, last)</td>
<td style="text-align: right;">0.9968</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9941</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.9953</td>
<td style="text-align: right;">0.0013</td>
<td style="text-align: right;">149113</td>
</tr>
</tbody>
</table>
<p><em>Per-epoch curve</em> — the Q2 plateau in numbers, with exp017’s matched scalar epoch alongside for Q1 (ep1 → ep24):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">epoch</th>
<th style="text-align: right;">PR (outcomes6)</th>
<th style="text-align: right;">PR (scalar)</th>
<th style="text-align: right;">purerace</th>
<th style="text-align: right;">racing</th>
<th style="text-align: right;">attacking</th>
<th style="text-align: right;">priming</th>
<th style="text-align: right;">anchoring</th>
<th style="text-align: right;">rollout MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.599</td>
<td style="text-align: right;">1.608</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">1.51</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">1.91</td>
<td style="text-align: right;">0.00302</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.344</td>
<td style="text-align: right;">1.327</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">0.00254</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.202</td>
<td style="text-align: right;">1.195</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">0.00228</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.155</td>
<td style="text-align: right;">1.166</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">0.00217</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.137</td>
<td style="text-align: right;">1.045</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">0.0021</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">1.33</td>
<td style="text-align: right;">0.00225</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1.082</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">1.26</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: right;">0.00201</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">0.983</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">0.00192</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1.077</td>
<td style="text-align: right;">0.989</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">0.00198</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1.064</td>
<td style="text-align: right;">0.991</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.00197</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1.061</td>
<td style="text-align: right;">0.971</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">0.00202</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">0.928</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.00204</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">0.961</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.00191</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">0.948</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.00199</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">1.002</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">0.00193</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.991</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">1.33</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">1.014</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">0.00218</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.983</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.00191</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">1.017</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.966</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.00195</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">1.005</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">0.00202</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.0019</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.993</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.23</td>
<td style="text-align: right;">0.00197</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">1.019</td>
<td style="text-align: right;">nan</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">0.00193</td>
</tr>
</tbody>
</table>
<p>The same curve as a figure — <strong>top panel</strong>: overall PR per epoch for both heads on the identical shard order, so vertical distance at a given epoch <em>is</em> the Q1 head difference and the shape after ep14 <em>is</em> Q2, with exp017’s endpoint marked and exp018’s ep15–24 plateau drawn as a band; <strong>middle panel</strong>: rollout value-fit MSE for both heads against the GNUBG teacher references; <strong>bottom panel</strong>: PR per game plan for exp018, each against its own GNUBG-0-ply reference (dotted, matching colour), so a curve below its dotted line means that plan has passed 0-ply.</p>
<div id="4319688d" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pretraining_analysis_files/figure-html/cell-27-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong></p>
<p><em>Pipeline check.</em> exp018 ep1 scores PR 1.599 against exp017 ep1’s 1.608 — the two heads are indistinguishable on their first pass over identical shards, as they should be before either has learned much, confirming the arms really are matched.</p>
<p><em>(a) Q2 — do epochs 15–24 help?</em> <strong>No, and this is a clean, powered null.</strong> The descent that was still running at exp017’s cap does continue for a few more epochs — exp018’s PR falls −0.0127/epoch over ep6–14 — and then <strong>stops</strong>. Over ep15–24 the slope is <strong>−0.0009/epoch (t = −0.33)</strong>, indistinguishable from flat, and the level sits at mean <strong>0.994 (SD 0.023, n=10 epochs)</strong>. Endpoint to endpoint, ep14 = 1.015 → ep24 = <strong>1.019</strong>: no improvement at all. Against the pre-registered prediction of ≈0.09 further PR this is decisive rather than merely unresolved — 0.09 would have been ~4 SD of the observed plateau scatter, so the test had ample power to see it and did not. The extrapolation was the thing that failed: fitting a power law to a curve that had not yet plateaued predicted travel that was not there.</p>
<p>The plateau also makes <strong>post-hoc best-epoch selection hazardous</strong>, and the pre-registered rule (“minimum PR”) walks straight into it. The minimum over ep15–24 is ep22 at 0.950 — but that is a minimum of ten draws from a distribution with mean 0.994 and SD 0.023, i.e.&nbsp;~1.9 SD below the mean, which is roughly what the minimum of ten draws <em>should</em> be under pure noise. The honest reading is that the run’s converged level is <strong>≈0.99</strong>, and 0.950 is a winner’s-curse estimate; ep22 is a fine checkpoint to ship, but its 0.950 should not be quoted as this recipe’s strength.</p>
<p><em>(b) Q1 — does outcomes6 match scalar?</em> <strong>The difference is real as a measurement and small; whether the <em>head</em> causes it is not established by this design.</strong> Over their three common late epochs scalar averages <strong>0.946 (ep12–14)</strong> against outcomes6’s <strong>1.001</strong>, in scalar’s favour at every epoch from ep5 on. The pre-registered paired test at ep14 (<code>PAIR=14</code>, <code>experiments/exp018-benchmark/results/paired_head_ep14.json</code>; cluster bootstrap, B=10,000 over 5,695 rollout decisions / 475 games) puts the gap at <strong>PR +0.067, 95% CI [+0.009, +0.127]</strong> game-clustered — excluding zero, so on a fresh sample of positions scalar would still be ahead at ep14.</p>
<p>That resolves the <em>measurement</em>, not the <em>attribution</em>. The bootstrap propagates benchmark sampling error only; it says nothing about <strong>initialisation variance</strong>, and since <code>train_distill.py</code> does not seed model init and this is one run per arm, a ~0.067 PR difference between two runs is exactly the size <a href="#exp016">exp016</a> judged inseparable from init noise (it saw 0.13 between arms it could not separate). So “the six-outcome head costs ~0.07 PR” and “this initialisation drew ~0.07 worse” remain observationally equivalent here. Separating them needs several seeds per arm, which this run deliberately did not buy.</p>
<p>The pre-registered asymmetry cuts the other way and keeps the verdict open rather than closing it. On rollout MSE — the metric that structurally favours scalar, being its own training objective — the two are <strong>statistically tied</strong>: candidate-weighted Δ = +2.3×10⁻⁵, CI [−4.6×10⁻⁵, +9.1×10⁻⁵], including zero. Each arm’s best epoch lands on the same <strong>0.00190</strong> (exp018 ep19; exp017 ep8 and ep11), within 2% of the GNUBG-2-ply teacher’s 0.00187 and past GNUBG-0-ply’s 0.00209. Outcomes6 matching <em>despite</em> the handicap is the strongest evidence the heads are equally good evaluators, and the script’s own joint rule reads the pair as <strong>not resolved</strong> — PR favours scalar, MSE ties.</p>
<p>The per-plan breakdown adds a genuine reversal: on <strong>pure race</strong> outcomes6 is significantly <em>better</em>, PR Δ = <strong>−0.12, CI [−0.17, −0.07]</strong>, with rollout MSE agreeing in sign. None of the four contact plans separates (racing +0.10, attacking +0.09, priming +0.13, anchoring +0.07, every CI spanning zero). So the aggregate PR gap is not a uniform head penalty; it is a modest contact-plan deficit set against a clear racing advantage.</p>
<p><em>(c) Does it beat GNUBG 0-ply?</em> <strong>Yes, unambiguously, on both metrics</strong> — the question that actually gates the deliverable. exp018 ep22 scores <strong>PR 0.950 vs 0-ply’s 2.145</strong> with <strong>19 blunders against 95</strong>, and rollout-MSE <strong>0.00190 vs 0.00209</strong> (n=14,693 / n≈149k). Unlike <a href="#exp015">exp015</a>/<a href="#exp016">exp016</a>, where PR and MSE disagreed in sign and no clean claim was possible, here they agree, so the claim is clean. The cube-capable net is not paying for its head with strength against the reference that matters.</p>
<p><em>(d) Per-plan, and the race.</em> <a href="#exp017">exp017</a> left pure race as the one plan still behind its GNUBG-0-ply reference (0.29 vs 0.16). exp018 <strong>passes it</strong>: ep22 scores <strong>0.13 against 0-ply’s 0.16</strong>, so all five plans are now ahead of their 0-ply references (racing 1.09 vs 2.72, attacking 0.95 vs 2.15, priming 1.03 vs 2.66, anchoring 1.22 vs 2.32). Whether the extra 10 epochs or the head did that is not separable here, but the residual race weakness flagged back in <a href="#exp015">exp015</a> is now closed.</p>
<p><em>(e) A diagnostic that does not transfer.</em> <a href="#exp017">exp017</a> read its scalar training loss (MSE against <code>equity/3</code>, ×9 into equity units) as an optimisation-progress signal, and it fell 28.5 → 1.5 ×10⁻⁴ across the run. That reading <strong>cannot</strong> be carried over: the outcomes6 arm trains cross-entropy against a six-outcome distribution, a different objective in different units, and its per-epoch mean sits at <strong>0.845–0.860 with no trend across all 24 epochs</strong>. That flatness is not evidence the fit stalled — a distribution over future outcomes carries large irreducible dice entropy, which dominates the loss and masks the improvement the benchmark clearly measures over ep1–14. For this head the training loss is simply not a convergence diagnostic, and the benchmark curve has to do that work alone.</p>
<p><strong>Conclusion.</strong> <em>Does the six-outcome head match scalar at 40M, and do ten more epochs help?</em> → <strong>Head: close enough to ship — tied on rollout MSE, +0.067 PR behind at ep14 (CI [+0.009, +0.127]), a gap this design cannot attribute to the head rather than to initialisation. Epochs: no — the curve is flat after ~ep14.</strong> Deliverable <code>exp018-distill/ep22</code> = <strong>PR 0.950</strong>, 19 blunders, <strong>rollout-MSE 0.00190</strong> (n=14,693 / n≈149k) — past GNUBG-0-ply on both (2.145 / 0.00209), within 2% of the GNUBG-2-ply teacher’s MSE, with all five game plans now ahead of their 0-ply references including pure race (0.13 vs 0.16). Read the converged level as <strong>≈0.99</strong>, not 0.950: ep15–24 average 0.994 (SD 0.023) and the minimum is a winner’s-curse pick. <strong>This closes the epoch lever</strong> — exp017’s “PR was still descending” was real but nearly spent, worth ~0.02 not the extrapolated ~0.09 — and delivers the <strong>cube-capable net at current best scale</strong>, which was the blocker. It does <em>not</em> close the data lever: what is ruled out is <strong>undertraining on this corpus</strong>, so the residual 0.95→0.56 gap to the 2-ply teacher now divides among play-time search, label <em>quality</em> (teacher ply), and label <em>volume</em> — the last two still untested at this scale.</p>
</section>
<section id="what-weve-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-weve-learned">What we’ve learned</h2>
<ol type="1">
<li><strong>A calibrated value head is not a player</strong> — with a random policy prior, MCTS never searches the moves the value head would reward (<a href="#v1">v1</a>).</li>
<li><strong>Policy labels can be synthesised</strong> by 0-ply lookahead over a position corpus; the policy prior is load-bearing (<a href="#v2">v2</a>).</li>
<li><strong>You cannot distill past your teacher, and teacher quality is the whole game</strong> — swapping the teacher moved the student from −1.24 to parity with iter_0447 with no other change; distillation also <em>compresses</em> (≈290 GPU-hours of self-play into ~21 CPU-hours) (<a href="#v2b">v2b</a>).</li>
<li><strong>A world-class teacher breaks the internal ceiling</strong>: GNUBG 4-ply labels produced the first checkpoint to beat iter_0447 and the first to take games off GNUBG (<a href="#v3">v3</a>).</li>
<li><strong>Capacity, eval-time search, and value-label coverage all fail to move the external gap</strong> — three levers tested in isolation, ~−1.6 ppg regardless; the missing ingredient is on-distribution <em>policy</em> data (<a href="#v4">v4</a>, <a href="#v5">v5</a>).</li>
<li><strong>More search can hurt</strong>: deeper MCTS amplifies a miscalibrated value head, overriding a good distilled prior (<a href="#v5">v5</a>, confirmed again in <a href="#exp008">exp008</a>).</li>
<li><strong>Input scaling is load-bearing</strong> — unnormalised handcrafted channels were an invisible regression; normalise in the encoder, not with an input BatchNorm (<a href="#feature-ablation">ablation</a>).</li>
<li><strong>On-distribution DAgger works where self-play fails</strong>: learner-generated states + oracle labels for both targets improved on the strongest seed and broke the −1.6 wall (<a href="#exp008">exp008</a>).</li>
<li><strong>Consolidated retraining beats incremental fine-tuning</strong> (~+0.4 ppg on the same labels), n=100 GNUBG evals mislead (−1.19 vs −1.38), and the handcrafted features <em>appeared</em> to wash out at 844k labels on an n=200 GNUBG match (<a href="#consolidation">consolidation</a>) — revised by #16 below: a higher-power benchmark shows they do help.</li>
<li><strong>Scaling DAgger sets a new best but plateaus</strong> — the loop’s biggest gain lands early (the doubles-policy fix), then an ungated, warm-started loop <em>oscillates</em> around a plateau instead of converging; the fix is eval-gated keep-best, and the ~0.4-ppg-short-of-parity plateau under a fixed 2-ply teacher is the ceiling that motivates TD self-play (<a href="#exp009">exp009</a>).</li>
<li><strong>Volume, not capacity, was the plateau</strong> — ~8M clean GNUBG-0-ply value labels produced a net that plays 0-ply <strong>near</strong> parity (−0.053 ± 0.046 vs GNUBG-0-ply at n=6000; −0.064 vs 2-ply), clearing the ~−0.3 wall DAgger and TD self-play both stalled at; the 10×256 architecture could always represent the value function, it just needed the labels — though a real ~0.05 handicap remains, so it is <em>near</em> the teacher, not at it. The scalar and six-outcome value heads <strong>tied</strong>, so the six-outcome head is kept downstream for its win/gammon/bg distribution (the cube), not because it plays stronger (<a href="#exp011b">exp011b</a>).</li>
<li><strong>A 2-ply-distilled net fits its (stronger) teacher just as well as the 0-ply-distilled net fits its own</strong> — held-out R² tied at 0.9983 vs 0.9983 (n≈2M), checked directly for train/holdout leakage (none found to inflate the result). Since GNUBG-2-ply is the stronger player, this points to at least as strong a net — the <em>sign</em>, not the ppg magnitude, which raw play can’t resolve at feasible n (<a href="#exp014">exp014</a>).</li>
<li><strong>The board-signature replay layer is reusable infrastructure</strong> — 99%+ match rate across raw and analysed corpora, behind every dataset on this page (<a href="#data-and-methodology">Data and methodology</a>).</li>
<li><strong>A static, external-reference PR benchmark partly confirms, partly complicates exp014’s R² sign</strong>: the 2-ply-distilled net beats the 0-ply-distilled net on move selection (PR 2.16 vs 2.75, and PR comes near GNUBG-0-ply’s own 2.14) — but on raw fit to the external rollout reference, the ordering <strong>flips</strong> (R² 0.9935 vs 0.9927 favors the 0-ply net). Move-selection and value-fit are different skills and can disagree. Both nets are surprisingly weakest on pure-race positions (<a href="#exp015">exp015</a>).</li>
<li><strong>A checkpoint-selection bug can hide in a hand-transcribed result and go undetected</strong> — exp015’s original numbers scored <code>best.pt</code> (a noisy in-loop-selected artifact) instead of the intended <code>ep3.pt</code> for both arms; caught only because <a href="#exp016">exp016</a> tried to reproduce them from scratch and couldn’t. Saving <code>--output</code> and preferring rendered-from-JSON tables over hand transcription (as done from exp016 onward) makes this class of bug visible immediately instead of silently persisting.</li>
<li><strong>The “handcrafted features wash out at scale” call was an underpowered read, not a null result</strong> — the exact same two consolidation checkpoints (17ch vs 26ch), re-scored on the high-power BGSage benchmark instead of an n=200 GNUBG match, show a clear, significant edge for the 26ch arm on both PR and rollout MSE (<a href="#exp016">exp016</a>).</li>
<li><strong>Scaling the 2-ply distillation 8M→40M is transformative</strong> — static-benchmark PR falls from 2.16 to 0.93 and rollout-MSE from 0.0044 to 0.0019 (within 2% of the GNUBG-2-ply teacher’s 0.00187, past GNUBG-0-ply on both), every game plan improving together with no trade-off, and the pure-race weakness (<a href="#exp015">exp015</a>) turning out to be an artifact (1.13→0.29). The 8M net was underfit, not capacity-bound — though it ran 3 epochs to the 40M run’s 12, so <em>volume</em> and <em>optimisation budget</em> both changed and this pair alone can’t apportion the credit. And the run is <strong>not</strong> converged: rollout MSE flattens by ~ep8 but PR is still descending when the wall-clock cap hits, so more epochs and more labels both remain live levers (<a href="#exp017">exp017</a>) — <em>the epoch half of that has since been closed by <a href="#exp018">exp018</a>: it was worth ~0.02 PR, not the extrapolated ~0.09.</em></li>
<li><strong>The six-outcome head costs little enough to ship, so the cube-capable net is now the deliverable</strong> — at 40M on identical shards, outcomes6 <strong>ties</strong> scalar on rollout MSE (paired Δ = +2.3×10⁻⁵, CI spanning zero; each arm’s best epoch at 0.00190) despite that metric being the scalar arm’s own training objective, while trailing on PR by a paired <strong>+0.067, CI [+0.009, +0.127]</strong> at ep14. That PR gap is a solid <em>measurement</em> but not an attribution: the bootstrap covers benchmark sampling error, not initialisation variance, and with one unseeded run per arm it is the same size <a href="#exp016">exp016</a> could not separate from init noise. The gap is also not uniform — outcomes6 is significantly <strong>better</strong> at pure race (Δ = −0.12, CI [−0.17, −0.07]) and no contact plan separates individually. <code>exp018/ep22</code> reaches PR 0.950 / MSE 0.00190, past GNUBG-0-ply on both, with all five game plans now ahead of their 0-ply references — pure race included (0.13 vs 0.16), closing the last per-plan gap <a href="#exp017">exp017</a> left open (<a href="#exp018">exp018</a>).</li>
<li><strong>Training more epochs on 40M is a spent lever, and extrapolating an unplateaued curve overstates it</strong> — <a href="#exp017">exp017</a>’s PR was genuinely still descending at its wall cap, and a power-law fit predicted ≈0.09 more by ep24. Running it produced <strong>+0.004</strong> (ep14 1.015 → ep24 1.019), with the ep15–24 slope flat at −0.0009/epoch (t = −0.33). The descent stopped a few epochs past where the cap had fallen. A corollary worth carrying: on a plateau, “best epoch = minimum PR” is a <strong>winner’s-curse</strong> estimate — ep22’s 0.950 is ~1.9 SD below the ep15–24 mean of 0.994 (SD 0.023, n=10), about what the minimum of ten noise draws should be, so the recipe’s true level is ≈0.99 (<a href="#exp018">exp018</a>).</li>
</ol>
</section>
<section id="open-questions" class="level2">
<h2 class="anchored" data-anchor-id="open-questions">Open questions</h2>
<ul>
<li><p><strong>The strongest net has no cube-capable head</strong> <em>(answered — <a href="#exp018">exp018</a>).</em> Re-running exp017’s recipe with <code>--value-head outcomes6</code> on the same 40M corpus and the same shard order produced the cube-capable net at current best scale: <code>exp018/ep22</code>, <strong>PR 0.950 / rollout-MSE 0.00190</strong> (n=14,693 / n≈149k), past GNUBG-0-ply on both. The matched A/B this question asked for came out <strong>not jointly resolved</strong>: outcomes6 ties scalar on rollout MSE (the metric that structurally favours scalar) but trails on PR by a paired +0.067 (CI [+0.009, +0.127]) at ep14 — a real measurement that this one-run-per-arm design cannot attribute to the head rather than to initialisation, and one that reverses on pure race, where outcomes6 is significantly better. The warm-start shortcut was not needed; from-scratch worked, as <a href="#exp011b">exp011b</a> predicted. <strong>Still open, and unchanged by this run:</strong> outcomes6 is <em>necessary but not sufficient</em> for the cube — cubeful equity and take points sit on top of the distribution, and nothing here validates the <strong>gammon/backgammon split itself</strong>. The BGSage benchmark scores cubeless equity and move choice only, so the calibration that the cube will actually depend on is still unmeasured; that needs a gammon-rate reference, and it is the natural next step on the cube track.</p></li>
<li><p><strong>How much is left in labels?</strong> <em>(the epoch half is answered — <a href="#exp018">exp018</a>.)</em> <strong>On epochs: closed.</strong> exp017 stopped on its wall cap with PR still descending at −0.0082/epoch (t = −4.0), and a power-law fit predicted ≈0.09 more by ep24. <a href="#exp018">exp018</a> ran the full 24 epochs and got <strong>+0.004</strong> (ep14 1.015 → ep24 1.019), with ep15–24 flat at −0.0009/epoch (t = −0.33): the descent stopped a few epochs past where the cap had fallen, and the lever was worth ~0.02, not ~0.09. The general lesson is about the <em>method</em>, not this run — extrapolating a curve that has not yet plateaued measures the fitted form, not the system. <strong>On labels:</strong> the data axis has exactly two points (8M, 40M), and two points fit any two-parameter curve exactly — so the 80M extrapolations (≈0.76 floored at the teacher’s 0.56, ≈0.65 unfloored) come from the assumed form, not from evidence. A ladder of runs on 9M/17M/24M subsets of run3 (verified to share run1’s label and position distribution, so they sit on one curve) would measure the <em>marginal return per doubling</em> near the current scale — the decision-relevant quantity — though four points across a single decade would not settle the functional form or the asymptote. <strong>Worth doing only if generating more labels is a cost we would be paying ourselves</strong>; if a larger corpus can be sourced instead, the ladder’s whole purpose (deciding whether to fund generation) falls away, and the effort belongs on teacher <em>quality</em> instead — a 4-ply teacher moves the 0.56 asymptote itself, where more 2-ply labels only slide us along a curve that ends there. Separately, exp014’s 8M anchor ran 3 epochs to exp017’s 12, so no existing pair separates data volume from optimisation budget; a matched-budget subset ladder would fix that too.</p></li>
<li><p><strong>What counts as beating GNUBG.</strong> The bar is a <em>matched-or-less-search</em> win: our net must beat GNUBG’s deployed 2-ply play either with <strong>no more search</strong> (the gold standard — a static 0-ply net that beats GNUBG-2-ply, i.e.&nbsp;a strictly better evaluator playing <em>cheaper</em>) or at <strong>equal search</strong> (our-net + 2-ply vs GNUBG + 2-ply). Winning only by searching <em>deeper</em> at play time (our-net + 3-ply beats GNUBG-2-ply) does not count — it is GNUBG’s own idea with more inference compute, and it collapses the instant search is held equal. The real distinction is <em>where the compute lives</em>: lookahead baked into the <strong>net</strong> at training time (better labels, self-play) is fair and deploys cheap; lookahead <strong>escalated at play time</strong> is not. This is why the roadmap builds the evaluator first and treats search as the finish, not the crutch.</p></li>
<li><p><strong>The teacher ceiling.</strong> DAgger converges to GNUBG 2-ply by construction, and 3-ply labels cost 53× per label — steep for a teacher we intend to outgrow. exp009 plateaued ~0.4 ppg short of parity, confirming this is now the binding constraint. The leading escape — TD(λ) self-play from the consolidated seed — was tested in <a href="./training_analysis.html#exp010">exp010</a>: it <strong>does</strong> lift a strong seed (the first self-play method here to do so, unlike exp007), but on a pure-greedy recipe it plateaus ~0.3 ppg short of even 0-ply parity. The obvious next candidate lever — distilling <em>to</em> 0-ply parity before self-play — has since been tried: <a href="./training_analysis.html#exp013">exp013</a> reran the same greedy recipe from the exp011b near-parity seed and found no detectable movement, but at a sample size only powered to catch effects several times the realistic ~0.05 ppg ceiling, so this doesn’t close the question. Surpassing 0-ply is still open; candidate levers are exploration/temperature in the TD loop (untested), a much larger confirm run, or the value-head changes below.</p></li>
<li><p><strong>Ranking checkpoints on a plateau.</strong> exp009’s three n=200 milestones (round 6 −0.37, round 18 −0.50, round 25 −0.48) are within ~1 SE, so which is the true best — the deliverable — needs a larger head-to-head (n≥400) or a tie-break arena; the n=100 per-round evals cannot separate them.</p></li>
<li><p><strong>Value calibration under search.</strong> “More sims hurt” has now been measured three times. A value head that search <em>strengthens</em> rather than undermines — possibly via multi-component outputs (win/gammon/bg probabilities, as TD-Gammon and GNUBG use) — is an open design question feeding exp010. It is sharpened by the ply-strength figures below: GNUBG <em>barely</em> improves from 0→2 ply (it is already near-perfect, so search hits diminishing returns) yet never worsens, whereas Raccoon — far from perfect, where search should help most — gets worse. A weak net whose own search degrades it is the clearest single indictment of the value head.</p></li>
<li><p><strong>From near-0-ply to the 2-ply benchmark</strong> <em>(partly answered).</em> <a href="#exp011b">exp011b</a> benchmarked the completed net against <strong>both</strong> references (exp012b): <strong>−0.053 vs 0-ply, −0.064 vs 2-ply</strong> (n=6000 / n=1000) — so its 2-ply standing is now measured, and the searchless 2-ply gap (~0.06) is small (2-ply search buys GNUBG little against it). Still open: arm’s <code>best.pt</code> <strong>under MCTS / 2-ply search</strong> — the value head is, for the first time, calibrated for static play, so this remains the sharpest test of whether “more sims hurt” (below) finally flips into “more sims help.” Note the fair-beat principle: search on our own head is the <em>finish</em>, not the lead — a genuinely better net must win at matched search first.</p></li>
<li><p><strong>Beyond 0-ply needs a stronger signal, not more labels.</strong> Since pure 0-ply distillation caps at the 0-ply teacher, reaching parity <em>ends</em> the value of more 0-ply labels. Per the fair-beat principle above, the priority is a better <em>evaluator</em>, so the routes rank: <strong>(a) TD self-play from the near-parity seed — run as <a href="./training_analysis.html#exp013">exp013</a>.</strong> Greedy TD from the exp011b seed showed no detectable movement over 39 batches (n=6000, ±0.046 each): −0.050 → −0.070 → −0.057, all tied. This rules out exp010’s ~−0.3 plateau as a universal attractor (this seed never fell toward it) but doesn’t establish a climb either — the test’s power (~33%) was too low for the realistic ~0.05 ppg effect. The untested sub-lever is <strong>temperature&gt;0 TD</strong> (this run was pure greedy). <strong>(b) Stronger-teacher distillation — run as <a href="#exp014">exp014</a>, partly answered.</strong> A net distilled on self-generated 2-ply labels fits its teacher exactly as well (held-out R² 0.9983) as the 0-ply-distilled net fits 0-ply, and since 2-ply is the stronger player this points to a genuinely stronger net — but raw ppg (underpowered at feasible n) can’t yet confirm the <em>size</em> of the gain. <a href="#exp015">exp015</a> has since checked the <em>sign</em> independently on a static PR benchmark (2.16 vs 2.75) — move selection agrees with the held-out-R² sign, but rollout-tier R²/MSE on the same benchmark actually flips the ordering, so the two metrics don’t cleanly agree after all. Still open: train the deliverable on the full 8M (exp014 held out 2M for the A/B) and get a raw-ppg read against GNUBG. <strong>(c) Search on the calibrated head</strong> — the <em>finish</em>, not the lead: a genuinely superior net wins at matched search, so the net is load-bearing; search doubles as a cheap diagnostic of whether “more sims hurt” finally flipped. A volume scale-up (fleet generation + GPU training) earns its keep only under (b); a <em>deeper-than-2-ply</em> teacher (rollout / 3–4-ply analysis, e.g.&nbsp;via a Backgammon Galaxy collaboration) is the only external data that could break the 2-ply ceiling, since we can already self-make 2-ply.</p></li>
<li><p><strong>The multi-component head, cleanly</strong> <em>(answered).</em> <a href="#exp011b">exp011b</a> is the clean rematch — both arms trained 3 full epochs from random init, selected at n=1000: scalar and outcomes6 <strong>tie</strong> (ep3 −0.010 vs +0.001, 0.011 apart, well inside the difference-CI). So the six-outcome target doesn’t distil 0-ply <em>better</em> — but it is still wanted for the cube and for a TD value head, so it stays the preferred head on capability grounds.</p></li>
<li><p><strong>The cube.</strong> Everything on this page is cubeless checker play, but the M6 goal (“beat GNUBG at money game”) implies the doubling cube. Reaching parity on the cubeless metric is necessary but not sufficient; either the goal is re-scoped to cubeless explicitly, or cube modelling joins the roadmap.</p></li>
<li><p><strong>Race positions are the distilled nets’ relative weak point.</strong> <a href="#exp015">exp015</a>’s per-game-plan PR breakdown shows both distilled nets doing relatively worst on pure-race positions (exp014 1.13, exp011b 0.85) versus GNUBG’s near-perfect race play (2-ply 0.05, 0-ply 0.16) — 5–7×, the largest relative gap of any game plan, and a surprising one, since races have no contact and should be the easiest category for a value function to get right. <strong>Largely answered by <a href="#exp017">exp017</a>:</strong> scaling the 2-ply labels 8M→40M drops pure-race PR 1.13→0.29 with no trade-off against the other plans, so the gap was mostly an <strong>underfitting / data-volume artifact</strong>, not a structural weakness. At 0.29 it is the only plan still <em>behind</em> its GNUBG-0-ply reference (0.16) — the other four have all passed theirs — so a real residual remains, but it is no longer the stark 5–7× outlier.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/raccoonbg\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Tekst og tal</strong> · CVR 34101302 · Denmark</p>
</div>   
    <div class="nav-footer-center">
<p><a href="mailto:hello@raccoonbg.com">hello@raccoonbg.com</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/lassehjorthmadsen/raccoon">GitHub</a> · <a href="https://github.com/lassehjorthmadsen/raccoon/blob/main/LICENSE">MIT licence</a></p>
</div>
  </div>
</footer>




</body></html>