<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Evaluation Speed – Raccoon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3e9b1289f5f353c49b617ce48ad2bc38.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Evaluation Speed – Raccoon">
<meta property="og:description" content="Every strength result in this project compares engines at matched search depth. At matched time, GNU Backgammon is ahead — by a margin that decides what the engine can do.">
<meta property="og:site_name" content="Raccoon">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Raccoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-concepts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Concepts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-concepts">    
        <li>
    <a class="dropdown-item" href="./mcts_explained.html">
 <span class="dropdown-text">MCTS Explained</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./architecture.html">
 <span class="dropdown-text">Architecture</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-training" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Training</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-training">    
        <li>
    <a class="dropdown-item" href="./training_parameters.html">
 <span class="dropdown-text">Parameters</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./training_analysis.html">
 <span class="dropdown-text">Self-Play Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pretraining_analysis.html">
 <span class="dropdown-text">Supervised &amp; Expert Iteration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./variance_reduction.html">
 <span class="dropdown-text">Variance-Reduced Rollouts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./search.html">
 <span class="dropdown-text">Multi-Ply Search</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./speed.html">
 <span class="dropdown-text">Evaluation Speed</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cube.html">
 <span class="dropdown-text">The Doubling Cube</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./gcp_guide.html"> 
<span class="menu-text">Developer</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reference/index.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#what-one-position-costs" id="toc-what-one-position-costs" class="nav-link active" data-scroll-target="#what-one-position-costs">What one position costs</a></li>
  <li><a href="#it-is-the-network-not-the-code" id="toc-it-is-the-network-not-the-code" class="nav-link" data-scroll-target="#it-is-the-network-not-the-code">It is the network, not the code</a></li>
  <li><a href="#what-it-costs-at-matched-time" id="toc-what-it-costs-at-matched-time" class="nav-link" data-scroll-target="#what-it-costs-at-matched-time">What it costs at matched time</a></li>
  <li><a href="#everyone-else-uses-a-small-network" id="toc-everyone-else-uses-a-small-network" class="nav-link" data-scroll-target="#everyone-else-uses-a-small-network">Everyone else uses a small network</a></li>
  <li><a href="#what-a-smaller-network-would-cost" id="toc-what-a-smaller-network-would-cost" class="nav-link" data-scroll-target="#what-a-smaller-network-would-cost">What a smaller network would cost</a></li>
  <li><a href="#exp028" id="toc-exp028" class="nav-link" data-scroll-target="#exp028">exp028: a small network, measured</a></li>
  <li><a href="#what-this-page-does-not-say" id="toc-what-this-page-does-not-say" class="nav-link" data-scroll-target="#what-this-page-does-not-say">What this page does not say</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Evaluation Speed</h1>
<p class="subtitle lead">Every strength result in this project compares engines at matched search depth. At matched <em>time</em>, GNU Backgammon is ahead — by a margin that decides what the engine can do.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Raccoon’s network is more accurate than GNU Backgammon’s, position for position. On the BGSage benchmark it selects moves better at 0-ply than GNU Backgammon does at 1-ply. That result is real and it is measured.</p>
<p>It is also bought with about three and a half thousand times the computation, and that has never been reported alongside it.</p>
<p>This page measures what one position evaluation costs each engine, checks whether the difference is the implementation or the network, and works out what it means for the searches both engines can afford. The conclusion is that the current architecture cannot be made practical by tuning, and that the choice recorded in <code>goal.md</code>’s first assumption is the thing to revisit.</p>
<section id="what-one-position-costs" class="level2">
<h2 class="anchored" data-anchor-id="what-one-position-costs">What one position costs</h2>
<p>Both figures below come from the same script on the same machine in the same run, so the ratio does not depend on comparing published numbers from different hardware.</p>
<table class="caption-top table">
<caption>Measured on lasse-iMac14-2, 4 cores. MACs are multiply-accumulates in one forward pass, computed from the network shape.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>engine</th>
<th>architecture</th>
<th style="text-align: right;">MACs / position</th>
<th style="text-align: right;">positions / second</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNU Backgammon</td>
<td>250-128-5 MLP (one net per position class)</td>
<td style="text-align: right;">0.033 M</td>
<td style="text-align: right;"><strong>1,476,488</strong></td>
</tr>
<tr class="even">
<td>Raccoon ep22</td>
<td>10x256 ResNet, 11.9 M parameters</td>
<td style="text-align: right;">285 M</td>
<td style="text-align: right;"><strong>426</strong></td>
</tr>
</tbody>
</table>
<p>GNU Backgammon evaluates <strong>3,470 times</strong> as many positions per second, while Raccoon does <strong>8,718 times</strong> the multiply-accumulates per position.</p>
</section>
<section id="it-is-the-network-not-the-code" class="level2">
<h2 class="anchored" data-anchor-id="it-is-the-network-not-the-code">It is the network, not the code</h2>
<p>The two ratios differ, and the direction is worth noting: the arithmetic gap is larger than the measured gap. Raccoon extracts more work per multiply-accumulate than GNU Backgammon does, because a convolutional network evaluated in batches uses wide vector instructions and several cores, while a small network evaluated one position at a time does not.</p>
<p>Raccoon reaches <strong>242 GFLOPS</strong>, against a theoretical peak near 410 for this processor — about 59% of it, which is good for convolutions on a 2x12 board. Its advantage in efficiency per operation is 2.5x; its arithmetic disadvantage is 8,718x.</p>
<p>So there is no implementation problem to fix. Quantisation, better kernels or a faster runtime might buy a factor of two or three. The gap is three to four orders of magnitude, and it is the shape of the network.</p>
</section>
<section id="what-it-costs-at-matched-time" class="level2">
<h2 class="anchored" data-anchor-id="what-it-costs-at-matched-time">What it costs at matched time</h2>
<p>Search cost is evaluation cost multiplied by tree size. Two engines searching to the same depth visit comparable numbers of positions, so a per-position gap of this size becomes a per-decision gap of the same size.</p>
<p>Putting the measured per-decision times next to the benchmark accuracy each configuration achieves:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>configuration</th>
<th style="text-align: right;">time / decision</th>
<th style="text-align: right;">benchmark PR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNU Backgammon, 2-ply</td>
<td style="text-align: right;">0.062 s</td>
<td style="text-align: right;"><strong>0.588</strong></td>
</tr>
<tr class="even">
<td>Raccoon, 0-ply</td>
<td style="text-align: right;">0.049 s</td>
<td style="text-align: right;">1.026</td>
</tr>
<tr class="odd">
<td>Raccoon, depth-2 expectimax</td>
<td style="text-align: right;">28 s</td>
<td style="text-align: right;">0.426</td>
</tr>
</tbody>
</table>
<p>The first two lines take about the same time, and GNU Backgammon wins. The third line is the configuration where Raccoon is clearly stronger, and it costs roughly 450 times as long as the opponent it beats.</p>
<p>Times are measured: GNU Backgammon’s from driving the binary (<code>raccoon/eval/gnubg_cli.py</code>), Raccoon’s 0-ply from the throughput above at about 21 evaluations per decision, and depth-2 from exp021’s recorded 12,016 evaluations per decision. PR figures are exp021’s, on a 2,000-decision sample.</p>
<p><strong>Every comparison this project has published is at matched depth.</strong> exp021’s ladder, exp026’s head-to-head, the benchmark tables: all of them hold search depth fixed and vary the engine. None holds <em>time</em> fixed. At matched time the ordering reverses, and that is the comparison a real game imposes.</p>
</section>
<section id="everyone-else-uses-a-small-network" class="level2">
<h2 class="anchored" data-anchor-id="everyone-else-uses-a-small-network">Everyone else uses a small network</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>engine</th>
<th>network</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TD-Gammon</td>
<td>one hidden layer, handcrafted inputs</td>
</tr>
<tr class="even">
<td>GNU Backgammon</td>
<td>250 → 128 → 5, one per position class</td>
</tr>
<tr class="odd">
<td>BGSage (measured close to eXtreme Gammon)</td>
<td>244 → 200/400 → 5, five to nineteen networks by game plan</td>
</tr>
<tr class="even">
<td>Raccoon</td>
<td>26-channel input, ten residual blocks at 256 channels</td>
</tr>
</tbody>
</table>
<p>The convolutional trunk came from the AlphaZero framing in <code>goal.md</code>. Convolutions assume neighbouring squares are related in a way worth exploiting with shared filters. A backgammon board is 24 points where the relationships that matter are pip distances, contact and blot exposure — quantities Raccoon’s encoder already computes and hands the network directly as channels 17 to 25. It is possible that 285 M multiply-accumulates are being spent partly to rediscover structure the input already contains.</p>
</section>
<section id="what-a-smaller-network-would-cost" class="level2">
<h2 class="anchored" data-anchor-id="what-a-smaller-network-would-cost">What a smaller network would cost</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>architecture</th>
<th style="text-align: right;">MACs / position</th>
<th style="text-align: right;">projected positions / second</th>
<th style="text-align: right;">speed-up</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ResNet 10x256</td>
<td style="text-align: right;">284.553 M</td>
<td style="text-align: right;">426</td>
<td style="text-align: right;">1x</td>
</tr>
<tr class="even">
<td>ResNet 6x128</td>
<td style="text-align: right;">43.186 M</td>
<td style="text-align: right;">2,804</td>
<td style="text-align: right;">7x</td>
</tr>
<tr class="odd">
<td>ResNet 4x64</td>
<td style="text-align: right;">7.437 M</td>
<td style="text-align: right;">16,280</td>
<td style="text-align: right;">38x</td>
</tr>
<tr class="even">
<td>ResNet 2x64</td>
<td style="text-align: right;">3.898 M</td>
<td style="text-align: right;">31,059</td>
<td style="text-align: right;">73x</td>
</tr>
<tr class="odd">
<td>MLP 250x128</td>
<td style="text-align: right;">0.033 M</td>
<td style="text-align: right;">3,709,532</td>
<td style="text-align: right;">8,718x</td>
</tr>
<tr class="even">
<td>MLP 250x400</td>
<td style="text-align: right;">0.102 M</td>
<td style="text-align: right;">1,187,050</td>
<td style="text-align: right;">2,790x</td>
</tr>
</tbody>
</table>
<p>These rows scale the measured throughput by arithmetic cost. <strong>They say what an architecture would cost, not what it would score.</strong> A cheaper network is only useful if it stays accurate enough, and that requires training one and measuring it.</p>
<p>The measurement worth making is accuracy against speed, not accuracy alone. exp017 established that scaling from 8 M to 40 M training positions took PR from 2.16 to 0.93 at the current size, and the size itself was never varied against the same data. The 40 M-position cache is on disk and <code>scripts/train_distill.py</code> already does the work, so distilling it into progressively smaller networks — including a plain network over the existing handcrafted features — is a matter of compute rather than new machinery.</p>
<p>A cheaper network reaching, say, PR 1.2 at forty times the speed would beat ep22 outright at equal time, because it could afford the depth-2 search ep22 cannot.</p>
</section>
<section id="exp028" class="level2">
<h2 class="anchored" data-anchor-id="exp028">exp028: a small network, measured</h2>
<p>The page above argued that the experiment worth running was accuracy against speed, not accuracy alone. This is that experiment.</p>
<p><strong>Protocol</strong>, fixed before the final arms and not varied: every score is the full BGSage benchmark, n = 14,693, with no subsampling anywhere; every comparison is paired on identical decisions and bootstrapped over the 500 generating games; the paired resolution is about 0.09 PR, and effects below it are reported as <em>not resolved</em>, which is not the same as a null. Training data is the same 43 M GNU Backgammon 2-ply labels ep22 was distilled from.</p>
<section id="the-architecture-and-what-the-inputs-cost" class="level3">
<h3 class="anchored" data-anchor-id="the-architecture-and-what-the-inputs-cost">The architecture, and what the inputs cost</h3>
<p>Distilling those labels into a network shaped after PureTD’s <code>[512, 512, 256, 256]</code> gives a curve that is monotone in capacity:</p>
<table class="caption-top table">
<caption>Every row is the full benchmark. These arms ran under a constant learning rate, later shown to leave about 0.2 PR unclaimed, so they order the configurations correctly but none of them is converged.</caption>
<thead>
<tr class="header">
<th>configuration</th>
<th style="text-align: right;">PR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MLP [256], 624 inputs</td>
<td style="text-align: right;">5.40</td>
</tr>
<tr class="even">
<td>MLP [256,256], 624 inputs</td>
<td style="text-align: right;">2.99</td>
</tr>
<tr class="odd">
<td>MLP [512,512], 624 inputs</td>
<td style="text-align: right;">2.31</td>
</tr>
<tr class="even">
<td>MLP [512,512,256,256], 624 inputs</td>
<td style="text-align: right;">1.93</td>
</tr>
<tr class="odd">
<td>…dropping the handcrafted channels, 408 inputs</td>
<td style="text-align: right;">1.74</td>
</tr>
<tr class="even">
<td>…de-broadcast to 201 inputs</td>
<td style="text-align: right;">1.68</td>
</tr>
</tbody>
</table>
<p>Two input results are worth separating. Dropping the nine handcrafted channels <em>improved</em> PR by 0.19 while removing compute — confirming PureTD’s claim that expert features are unnecessary. But the mechanism is duplication rather than the features themselves: channels 8 to 25 are all constant across the board, so a convolution receives them as planes and a flattened network receives 24 identical copies of each. De-broadcasting to one value per scalar channel gives 201 inputs, which is the size PureTD uses, and buys another 0.10.</p>
<p>More data bought nothing: 24 M to 43 M positions moved PR by 0.04, inside the noise. That measurement was made under the constant-LR schedule, so it is worth repeating rather than treating as settled.</p>
</section>
<section id="two-hypotheses-tested" class="level3">
<h3 class="anchored" data-anchor-id="two-hypotheses-tested">Two hypotheses, tested</h3>
<p>With capacity, inputs and data explored, two candidates remained. Four arms, identical but for one variable each, all at the same 20-epoch budget:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>arm</th>
<th style="text-align: right;">PR at epoch 20</th>
<th style="text-align: right;">paired vs reference</th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>reference (constant LR, six-outcome head)</td>
<td style="text-align: right;">1.632</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>scalar head, squared error on equity</td>
<td style="text-align: right;"><strong>1.458</strong></td>
<td style="text-align: right;">+0.174 [+0.085, +0.264]</td>
<td style="text-align: left;">real</td>
</tr>
<tr class="odd">
<td>cosine learning-rate decay</td>
<td style="text-align: right;"><strong>1.420</strong></td>
<td style="text-align: right;">+0.213 [+0.127, +0.302]</td>
<td style="text-align: left;">real</td>
</tr>
<tr class="even">
<td>both</td>
<td style="text-align: right;"><strong>1.368</strong></td>
<td style="text-align: right;">+0.264 [+0.174, +0.356]</td>
<td style="text-align: left;">real</td>
</tr>
</tbody>
</table>
<p><strong>Both hypotheses are confirmed</strong>, each worth about 0.2 PR. The learning rate had been fixed at 1e-3 for the whole of every previous run, and the training target had been cross-entropy over six outcomes rather than squared error on the quantity move selection actually ranks.</p>
<p><strong>They do not add.</strong></p>
<p>Independent effects would have given 1.245; the combined arm reached <strong>1.368</strong>. That prediction was written into the run script before the arm started. Against cosine alone the combination is +0.051 [-0.035, +0.136] — <em>not resolved</em> — while against the scalar head alone it is +0.090 [+0.009, +0.170], <em>real</em>. So the schedule does most of the work and the two were largely repairing the same deficiency.</p>
</section>
<section id="convergence-had-to-be-measured-repeatedly" class="level3">
<h3 class="anchored" data-anchor-id="convergence-had-to-be-measured-repeatedly">Convergence had to be measured, repeatedly</h3>
<p>The reference arm was <strong>still improving at epoch 20</strong>: each five-epoch step was individually below the resolution limit, but epochs 10 to 20 accumulate to a real gain.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>arm</th>
<th style="text-align: right;">epochs 10 → 20</th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>reference (constant LR, six-outcome head)</td>
<td style="text-align: right;">+0.128 [+0.032, +0.225]</td>
<td style="text-align: left;">real</td>
</tr>
<tr class="even">
<td>scalar head, squared error on equity</td>
<td style="text-align: right;">+0.055 [-0.017, +0.129]</td>
<td style="text-align: left;">not resolved</td>
</tr>
<tr class="odd">
<td>cosine learning-rate decay</td>
<td style="text-align: right;">+0.252 [+0.182, +0.322]</td>
<td style="text-align: left;">real</td>
</tr>
<tr class="even">
<td>both</td>
<td style="text-align: right;">+0.057 [-0.003, +0.119]</td>
<td style="text-align: left;">not resolved</td>
</tr>
</tbody>
</table>
<p>This is why the protocol above insists convergence is measured rather than inferred. Training loss cannot see it — the reference network and a far weaker one produce indistinguishable loss curves. Nor can adjacent epoch comparisons, which read <em>not resolved</em> three times in a row on a curve that was genuinely still descending. Only the longer interval showed it.</p>
</section>
<section id="where-it-leaves-the-architecture" class="level3">
<h3 class="anchored" data-anchor-id="where-it-leaves-the-architecture">Where it leaves the architecture</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>engine</th>
<th style="text-align: right;">value MACs</th>
<th style="text-align: right;">PR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PureTD (see note)</td>
<td style="text-align: right;">0.561 M</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td>Raccoon ep22, ResNet 10x256</td>
<td style="text-align: right;">285 M</td>
<td style="text-align: right;">0.950</td>
</tr>
<tr class="odd">
<td>GNU Backgammon, 1-ply</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1.206</td>
</tr>
<tr class="even">
<td><strong>This MLP, best configuration</strong></td>
<td style="text-align: right;"><strong>0.563 M</strong></td>
<td style="text-align: right;"><strong>1.368</strong></td>
</tr>
<tr class="odd">
<td>GNU Backgammon, 0-ply</td>
<td style="text-align: right;">0.033 M</td>
<td style="text-align: right;">2.14</td>
</tr>
</tbody>
</table>
<p>A network doing <strong>500 times less arithmetic than ep22</strong> reaches PR 1.368, against ep22’s 0.950. It beats GNU Backgammon’s own evaluator comfortably and still loses to GNU Backgammon at 1-ply.</p>
<p><strong>On the PureTD comparison, two qualifications.</strong> Their 0.94 is XG++ Performance Rating on <em>cubeful</em> money; ours is this benchmark’s PR on <em>cubeless checker play</em>. The two scales agree closely where they can be compared — GNU Backgammon at 0-ply is 2.18 on theirs and 2.14 on ours, at 1-ply 1.21 against 1.206 — which is why they are shown together, but they are not the same measurement. And while <strong>capacity and inference cost are matched</strong> (562 k parameters against 565 k, 0.561 M MACs against 0.563 M), <strong>training compute is not</strong>: 200 M self-play games over about 65 hours on a 64-core workstation with a GPU, against roughly 38 core-hours per arm here with no GPU. Two orders of magnitude.</p>
<p>That distinction decides what to try next. The remaining difference is either the <strong>method</strong> — on-policy TD with exact Bellman backups over all 21 rolls, rather than regressing a fixed teacher — or simply <strong>scale</strong>. The evidence against pure scale is that more data bought nothing, but that was measured under the broken schedule. Running the best configuration far longer separates the two for one arm’s cost, before committing to an RL pipeline that would take weeks.</p>
</section>
</section>
<section id="what-this-page-does-not-say" class="level2">
<h2 class="anchored" data-anchor-id="what-this-page-does-not-say">What this page does not say</h2>
<ul>
<li><strong>It does not say the network is bad.</strong> It is more accurate per position than GNU Backgammon’s by a wide margin. The question is the price.</li>
<li><strong>The projected rows above are arithmetic, not accuracy.</strong> exp028 measured the accuracy separately; see <a href="#exp028">that section</a>.</li>
<li><strong>exp028’s arms are compared at a fixed budget, not at their endpoints.</strong> The cosine arm is converged by construction, since its learning rate reaches zero; the constant-rate arm was still improving when it stopped. “Better at 20 epochs” is a weaker claim than “reaches a better endpoint”.</li>
<li><strong>It is one machine.</strong> A four-core desktop processor with no GPU. A graphics card changes Raccoon’s throughput far more than GNU Backgammon’s, because batched convolutions suit one and a per-position network does not. That changes the arithmetic for training and offline analysis; it does not change what a browser or a phone can run.</li>
<li><strong>GNU Backgammon’s figure is single-position and single-threaded.</strong> It has headroom of its own that this comparison does not give it.</li>
<li><strong>It retracts no published result.</strong> Raccoon does beat GNU Backgammon at matched depth on the benchmark. This page adds the axis those results were silent on.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/research\.raccoonbg\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Tekst og tal</strong> · CVR 34101302 · Denmark</p>
</div>   
    <div class="nav-footer-center">
<p><a href="mailto:hello@raccoonbg.com">hello@raccoonbg.com</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/lassehjorthmadsen/raccoon">GitHub</a> · <a href="https://github.com/lassehjorthmadsen/raccoon/blob/main/LICENSE">MIT licence</a></p>
</div>
  </div>
</footer>




</body></html>