<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Raccoon Self-Play Analysis – Raccoon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c98d9d0b3b0a085d3ddf71e6e91476d8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Raccoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-concepts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Concepts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-concepts">    
        <li>
    <a class="dropdown-item" href="./mcts_explained.html">
 <span class="dropdown-text">MCTS Explained</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./architecture.html">
 <span class="dropdown-text">Architecture</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-training" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Training</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-training">    
        <li>
    <a class="dropdown-item" href="./training_parameters.html">
 <span class="dropdown-text">Parameters</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./training_analysis.html">
 <span class="dropdown-text">Self-Play Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pretraining_analysis.html">
 <span class="dropdown-text">Supervised &amp; Expert Iteration</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./gcp_guide.html"> 
<span class="menu-text">Developer</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reference/index.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#how-to-read-the-results" id="toc-how-to-read-the-results" class="nav-link active" data-scroll-target="#how-to-read-the-results">How to read the results</a></li>
  <li><a href="#the-experiments-at-a-glance" id="toc-the-experiments-at-a-glance" class="nav-link" data-scroll-target="#the-experiments-at-a-glance">The experiments at a glance</a></li>
  <li><a href="#exp000" id="toc-exp000" class="nav-link" data-scroll-target="#exp000">exp000 — pipeline validation</a></li>
  <li><a href="#exp001" id="toc-exp001" class="nav-link" data-scroll-target="#exp001">exp001 — more compute per iteration</a></li>
  <li><a href="#exp002" id="toc-exp002" class="nav-link" data-scroll-target="#exp002">exp002 — smaller replay buffer</a></li>
  <li><a href="#exp003" id="toc-exp003" class="nav-link" data-scroll-target="#exp003">exp003 — Dirichlet exploration noise</a></li>
  <li><a href="#exp004" id="toc-exp004" class="nav-link" data-scroll-target="#exp004">exp004 — value bootstrapping and LR decay</a></li>
  <li><a href="#exp005" id="toc-exp005" class="nav-link" data-scroll-target="#exp005">exp005 — 800-simulation search</a></li>
  <li><a href="#exp006" id="toc-exp006" class="nav-link" data-scroll-target="#exp006">exp006 — 2000 more iterations</a></li>
  <li><a href="#exp007" id="toc-exp007" class="nav-link" data-scroll-target="#exp007">exp007 — self-play from the v5 supervised seed</a></li>
  <li><a href="#cross-experiment-trends" id="toc-cross-experiment-trends" class="nav-link" data-scroll-target="#cross-experiment-trends">Cross-experiment trends</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#what-happened-next" id="toc-what-happened-next" class="nav-link" data-scroll-target="#what-happened-next">What happened next</a></li>
  <li><a href="#exp010" id="toc-exp010" class="nav-link" data-scroll-target="#exp010">exp010 — TD(λ) self-play from a distilled seed</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Raccoon Self-Play Analysis</h1>
<p class="subtitle lead">The self-play track: AlphaZero from scratch, exp000–exp007</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This page documents the <strong>self-play track</strong>: eight experiments (exp000–exp007) testing whether AlphaZero-style self-play — a ResNet policy-value network trained on its own MCTS games — can reach GNUBG-competitive backgammon at this project’s compute scale (a single T4 GPU or a desktop CPU).</p>
<p><strong>The track’s conclusion, up front: it cannot.</strong> Every self-play checkpoint loses 97–100% of its games against GNUBG 2-ply, at −2.2 to −2.5 points per game. Two levers produced statistically significant improvement — 800-simulation search (exp005) and sheer iteration count (exp006) — but at a rate that would need on the order of 17,000 iterations to close the gap. The bottleneck is the <em>quality</em> of the self-play training signal, not the amount of training. That conclusion motivated the pivot to supervised distillation from GNUBG, documented in the <a href="./pretraining_analysis.html">supervised &amp; expert-iteration track</a>, which produced every subsequent strength gain. The final experiment here (exp007) connects the two tracks: pure self-play from a strong supervised seed <em>destroys</em> the seed rather than improving it.</p>
<p>Each experiment below gets one section: motivation, setup, results, interpretation. Results are computed from the experiment logs at render time.</p>
<section id="how-to-read-the-results" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-the-results">How to read the results</h2>
<ul>
<li><strong>Strength is measured in points per game (ppg)</strong> under cubeless money rules: a plain win scores 1, a gammon 2, a backgammon 3. Strength claims come from head-to-head play, never from loss curves.</li>
<li><strong>Arena evals</strong> pit two checkpoints against each other with MCTS at equal simulation counts. <strong>GNUBG evals</strong> play a checkpoint against the <code>gnubg-nn</code> engine at <code>level=world</code>, which the adapter maps to full-width <strong>2-ply</strong> — genuine “World class” checker play. (Early versions of these pages mislabeled this opponent “0-ply”; the underlying evals were always 2-ply.)</li>
<li><strong>Sampling noise is large.</strong> The per-game equity SD is ~1.8, so a 100-game match has a standard error of ~0.18 ppg; differences under ~0.35 ppg at n=100 are not statistically significant. Several per-experiment results below are explicitly “n.s.” for this reason.</li>
<li><strong>Loss curves are fitting metrics, not strength metrics.</strong> Policy loss is cross-entropy against MCTS visit distributions; value loss is MSE against blended game outcomes. Both measure how well the network fits its own self-play targets — a moving, self-generated distribution. This track repeatedly found the two diverging from strength, in both directions.</li>
</ul>
</section>
<section id="the-experiments-at-a-glance" class="level2">
<h2 class="anchored" data-anchor-id="the-experiments-at-a-glance">The experiments at a glance</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 37%">
<col style="width: 4%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Experiment</th>
<th style="text-align: left;">Configuration</th>
<th style="text-align: left;">Iters</th>
<th style="text-align: left;">Period</th>
<th style="text-align: left;">Headline result</th>
<th style="text-align: left;">Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">exp000</td>
<td style="text-align: left;">25 sims, 10 games/iter, 100k buffer</td>
<td style="text-align: left;">499</td>
<td style="text-align: left;">2026-04-11 → 2026-04-12</td>
<td style="text-align: left;">0-10 vs GNUBG (n=10)</td>
<td style="text-align: left;">Pipeline works; play weak</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp001</td>
<td style="text-align: left;">200 sims, 50 games/iter, 500k buffer</td>
<td style="text-align: left;">283</td>
<td style="text-align: left;">2026-04-13 → 2026-04-25</td>
<td style="text-align: left;">−2.32 ppg vs GNUBG; no within-run gain</td>
<td style="text-align: left;">More compute/iter ≠ progress</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp002</td>
<td style="text-align: left;">200 sims, 50 games/iter, 50k buffer</td>
<td style="text-align: left;">148</td>
<td style="text-align: left;">2026-04-27 → 2026-04-29</td>
<td style="text-align: left;">−2.30 ppg vs GNUBG; loses to exp001</td>
<td style="text-align: left;">Buffer size not the bottleneck</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp003</td>
<td style="text-align: left;">100 sims, 25 games/iter, 25k buffer, Dirichlet</td>
<td style="text-align: left;">138</td>
<td style="text-align: left;">2026-04-30 → 2026-05-03</td>
<td style="text-align: left;">iter_220 lost to iter_150 (−0.43)</td>
<td style="text-align: left;">Dirichlet noise didn’t help</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp004</td>
<td style="text-align: left;">100 sims, 25 games/iter, 25k buffer, Dirichlet, bootstrap α=0.5, LR decay</td>
<td style="text-align: left;">264</td>
<td style="text-align: left;">2026-05-03 → 2026-05-06</td>
<td style="text-align: left;">No detectable strength change</td>
<td style="text-align: left;">Value targets not the bottleneck</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp005</td>
<td style="text-align: left;">800 sims, 25 games/iter, 25k buffer, Dirichlet, bootstrap α=0.5</td>
<td style="text-align: left;">448</td>
<td style="text-align: left;">2026-05-04 → 2026-05-28</td>
<td style="text-align: left;">+0.38 ppg in 109 iters (p≈0.035)</td>
<td style="text-align: left;">800 sims: best self-play lever</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exp006</td>
<td style="text-align: left;">exp000 settings, resumed from iter_0498</td>
<td style="text-align: left;">2000</td>
<td style="text-align: left;">2026-05-07 → 2026-05-13</td>
<td style="text-align: left;">+0.27 ppg over 2000 iters (p≈0.024)</td>
<td style="text-align: left;">Plateau slow, not absolute — too slow</td>
</tr>
<tr class="even">
<td style="text-align: left;">exp007</td>
<td style="text-align: left;">800 sims, 8 games/iter, 25k buffer, 10×256 net, v5 supervised seed</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">2026-06-09 → 2026-06-14</td>
<td style="text-align: left;">Regressed −1.74 ppg vs its seed</td>
<td style="text-align: left;">Self-play destroys a strong seed</td>
</tr>
</tbody>
</table>
<p>All experiments use the default 6×128 ResNet except exp007 (10×256). exp000–exp002 and exp005 ran on a T4 GPU spot VM; exp003, exp004, exp006, and exp007 ran on desktop CPUs. The Iters column counts logged training iterations — exp003 resumed from an existing checkpoint at iter 148, and exp006 continued exp000’s counter from 499.</p>
</section>
<section id="exp000" class="level2">
<h2 class="anchored" data-anchor-id="exp000">exp000 — pipeline validation</h2>
<p><strong>Motivation.</strong> First end-to-end run: does the full pipeline hold up — the 26-channel encoder, GPU training, spot-VM preemption recovery — and what does baseline learning look like at minimal settings?</p>
<p><strong>Setup.</strong> 25 sims, 10 games/iter, 100k replay buffer, 499 iterations on the T4.</p>
<p><strong>Results.</strong></p>
<div id="3d7d260d" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0498 vs iter_0290  (n=50 @100 sims): 24-26, +0.060 ppg
gnubg  iter_0498 vs GNUBG 2-ply  (n=10 @200 sims): 0-10, -2.500 ppg</code></pre>
</div>
</div>
<p>Policy loss fell steadily from ~6.5 to ~1.77; value loss drifted slightly <em>up</em> (~0.097 → ~0.112). Self-play games showed a persistent <strong>+0.3 ppg bias toward player 0</strong> across all 500 iterations, even though the opening roll is verified 50/50 and random-vs-random play scores +0.04 ± 0.04 over 3000 games (statistically zero).</p>
<p><strong>Interpretation.</strong> The pipeline works, but the play is weak (0-10 vs GNUBG, ~34% of self-play games ending in gammon). The player-0 bias is not an engine bug: a small asymmetry in the raw network gets amplified by shallow 25-sim search and then reinforced by training on the resulting games. It shrank to ~+0.08 in exp001’s 200-sim setting, confirming the diagnosis — a useful thermometer for whether search depth is adequate to correct the raw network.</p>
</section>
<section id="exp001" class="level2">
<h2 class="anchored" data-anchor-id="exp001">exp001 — more compute per iteration</h2>
<p><strong>Motivation.</strong> Does 8× the MCTS simulations and 5× the games per iteration translate into faster learning?</p>
<p><strong>Setup.</strong> 200 sims, 50 games/iter, 500k buffer, fresh start, 283 iterations. ~27× slower per iteration than exp000 (~37.5 vs ~1.4 min).</p>
<p><strong>Results.</strong></p>
<div id="8e354f7f" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0112 vs iter_0498  (n=50 @100 sims): 32-18, +0.440 ppg
arena  iter_0282 vs iter_0260  (n=50 @100 sims): 27-23, +0.120 ppg
gnubg  iter_0112 vs GNUBG 2-ply  (n=50 @200 sims): 1-49, -2.220 ppg
gnubg  iter_0282 vs GNUBG 2-ply  (n=50 @100 sims): 0-50, -2.320 ppg</code></pre>
</div>
</div>
<p>Policy loss dropped early (~4.4 → ~2.0) then flattened; value loss rose clearly (~0.105 → ~0.140). iter_112 beat exp000’s final checkpoint (+0.44 ppg), but the within-experiment check — iter_282 vs iter_260, the clean test of continuing progress — showed nothing (+0.12 ppg, n.s.), and GNUBG performance did not improve between iter_112 (−2.22) and iter_282 (−2.32) despite 170 more iterations.</p>
<p><strong>Interpretation.</strong> The cross-experiment win over exp000 only shows “more compute + more training beats less”; the flat within-run strength and flat GNUBG results show exp001 itself had plateaued. The rising value loss is <em>not</em> masking hidden improvement — no improvement is visible in head-to-head play either.</p>
</section>
<section id="exp002" class="level2">
<h2 class="anchored" data-anchor-id="exp002">exp002 — smaller replay buffer</h2>
<p><strong>Motivation.</strong> exp001’s 500k buffer holds ~100 iterations of positions, so the network fits a mix of old (weaker) and new play. Does a 50k buffer — cycling in ~10 iterations, always training on fresh data — fix the rising value loss and the plateau?</p>
<p><strong>Setup.</strong> exp001’s config with <code>--replay-size 50000</code>, fresh start, 148 iterations.</p>
<p><strong>Results.</strong></p>
<div id="74e09c69" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0147 vs iter_0125  (n=50 @100 sims): 26-24, +0.300 ppg
arena  iter_0147 vs iter_0282  (n=50 @100 sims): 20-30, -0.440 ppg
gnubg  iter_0147 vs GNUBG 2-ply  (n=50 @100 sims): 0-50, -2.300 ppg</code></pre>
</div>
</div>
<p>The fitting side behaved exactly as hoped: faster initial descent, lower minima (value loss bottomed at ~0.103 vs exp001’s ~0.105 floor), less late drift. Strength did not follow: the within-run check was null (+0.30 ppg, n.s.), GNUBG result identical to exp001 (0-50, −2.30), and exp001’s iter_282 beat exp002’s final checkpoint head-to-head (−0.44 ppg).</p>
<p><strong>Interpretation.</strong> Replay-buffer staleness affects loss curves but was not the strength bottleneck. Better fitting metrics, same weak play — the first clear instance of a pattern that recurs throughout this track.</p>
</section>
<section id="exp003" class="level2">
<h2 class="anchored" data-anchor-id="exp003">exp003 — Dirichlet exploration noise</h2>
<p><strong>Motivation.</strong> Standard AlphaZero adds Dirichlet noise at the MCTS root to keep exploration alive. Was exploration collapse causing the plateau?</p>
<p><strong>Setup.</strong> 100 sims, 25 games/iter, 25k buffer, Dirichlet α=0.3 / ε=0.25, resumed from a trained checkpoint at iter 148; abandoned at iter 284. First experiment to log MCTS visit entropy.</p>
<p><strong>Results.</strong></p>
<div id="a69dfdaf" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0220 vs iter_0150  (n=100 @50 sims): 40-60, -0.430 ppg
arena  iter_0280 vs iter_0150  (n=100 @50 sims): 48-52, -0.130 ppg</code></pre>
</div>
</div>
<p>Visit entropy sat flat at ~1.37 nats throughout — for context, a uniform distribution over a typical ~25 legal moves would be ~3.2 nats, so visits were already quite peaked, and Dirichlet noise neither collapsed nor diversified them. Strength went <em>backwards</em>: iter_220 lost to iter_150 outright (−0.43 ppg), and the end-of-run checkpoint was still level-at-best (−0.13, n.s.).</p>
<p><strong>Interpretation.</strong> Exploration was not collapsing, and keeping it alive did not improve the policy prior. 130 iterations with noise produced zero improvement — the plateau is not an exploration problem.</p>
</section>
<section id="exp004" class="level2">
<h2 class="anchored" data-anchor-id="exp004">exp004 — value bootstrapping and LR decay</h2>
<p><strong>Motivation.</strong> Self-play value labels are discrete terminal outcomes (±1/3, ±2/3, ±1) — noisy and extreme. Does blending in the smoother MCTS root Q (<code>--value-bootstrap-alpha 0.5</code>) fix the value head, and does an LR schedule reduce late oscillation?</p>
<p><strong>Setup.</strong> 100 sims, 25 games/iter, 25k buffer, Dirichlet noise, bootstrap α=0.5, LR ×0.1 at iter 200; fresh start, 264 iterations on CPU.</p>
<p><strong>Results.</strong></p>
<div id="65288cdd" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0180 vs iter_0100  (n=50 @100 sims): 26-24, +0.020 ppg
arena  iter_0260 vs iter_0200  (n=50 @100 sims): 27-23, +0.120 ppg
arena  iter_0260 vs iter_0200  (n=50 @100 sims): 21-29, -0.320 ppg</code></pre>
</div>
</div>
<p>Value loss came out ~3× lower than exp001/exp002 (0.038–0.053 vs 0.105–0.140) — as expected, since the targets are smoother. Strength was unchanged: no detectable gain from iter_100 to iter_180 (+0.02, n.s.) nor across the LR decay (iter_260 vs iter_200: −0.10 combined over 100 games, n.s.). Gammon/backgammon rates were among the <em>highest</em> of any run (<sub>39%/</sub>29%).</p>
<p><strong>Interpretation.</strong> Lower MSE on smoother targets does not mean a better value function. Neither bootstrapping nor LR decay moved play quality; value-target noise was not the binding constraint.</p>
</section>
<section id="exp005" class="level2">
<h2 class="anchored" data-anchor-id="exp005">exp005 — 800-simulation search</h2>
<p><strong>Motivation.</strong> If self-play target quality is the bottleneck, deeper search at training time should produce qualitatively better MCTS policy targets. Scale simulations 8× over exp004 and keep everything else.</p>
<p><strong>Setup.</strong> 800 sims, 25 games/iter, 25k buffer, Dirichlet, bootstrap α=0.5, on the T4 (~79 min/iter). The run splits into three phases: a clean phase (iters 1–109), a destabilized phase after a hardware restart (110–173), and a long watchdog-driven extension (173–447). Total ~459 GPU-hours over May 4–28.</p>
<p><strong>Results.</strong></p>
<div id="f6dcf7b6" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_0109 vs iter_0040  (n=100 @100 sims): 58-42, +0.380 ppg
arena  iter_0447 vs iter_0109  (n=100 @100 sims): 52-48, +0.050 ppg
gnubg  iter_0109 vs GNUBG 2-ply  (n=100 @100 sims): 0-100, -2.520 ppg</code></pre>
</div>
</div>
<p>The clean phase produced the best learning signal of the whole track: the fastest policy-loss decline of any experiment, and the self-play backgammon rate fell from 41% to 27% — the sharpest game-quality improvement seen anywhere. The arena confirms it was real strength: <strong>iter_0109 beat iter_0040 by +0.380 ppg (58/100, p≈0.035)</strong> — a statistically significant gain in just 69 iterations, where exp001–exp004 found nothing.</p>
<p>Then the confounds hit. A spot-VM restart at iter 110 cold-started the replay buffer, and an LR schedule bug-fix cut the learning rate to 1e-4 at iter 115 (and 1e-5 at iter 155) right on top of it. Fitting metrics unravelled: policy loss climbed from ~1.7 back past 3.1 — <em>above</em> its random-init starting point — and the self-play backgammon rate jumped back to 44–48%. A local watchdog then auto-resumed the run through ~14 further preemptions to iter 447, with lr pinned at 1e-5; the metrics never recovered over those 290 iterations.</p>
<p>But the strength did not go anywhere: <strong>iter_0447 vs iter_0109 came out 52-48, +0.050 ppg (n.s.)</strong> — the network’s play was fully preserved across a 338-iteration stretch in which every fitting metric said it was degrading. Against GNUBG, iter_0109 still lost 0-100 (−2.52 ppg).</p>
<p><strong>Interpretation.</strong> Two findings. First, <strong>800-sim search is the strongest self-play lever found</strong> — the only intervention to produce a significant within-run gain, and quickly. Second, the extension is this track’s cleanest demonstration that <strong>loss does not track strength</strong>: the lr=1e-5 phase diffused the policy distribution, which made self-play games look worse on every counting metric (both sides play the same diffuse policy against each other — a coupling artifact), yet eval-time MCTS recovered the same play quality from the noisier prior. Metrics moved a lot; the player didn’t move at all.</p>
</section>
<section id="exp006" class="level2">
<h2 class="anchored" data-anchor-id="exp006">exp006 — 2000 more iterations</h2>
<p><strong>Motivation.</strong> A clean falsification test: does sheer iteration count eventually break the plateau, with everything else held fixed?</p>
<p><strong>Setup.</strong> Resumed exp000’s final checkpoint with identical hyperparameters (25 sims, no noise, no bootstrap, no schedule) for 2000 further iterations (499 → 2498), on the iMac CPU (~4.1 min/iter).</p>
<p><strong>Results.</strong></p>
<div id="725b0aa3" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>arena  iter_2498 vs iter_0498  (n=200 @100 sims): 116-84, +0.270 ppg</code></pre>
</div>
</div>
<p>Slow, directionally consistent improvement: backgammon rate 15% → 11%, gammon rate 32% → 28%, policy loss 1.70 → 1.50 over the warm phase. The head-to-head confirms it: <strong>iter_2498 beat iter_0498 by +0.270 ppg (116/200, p≈0.024)</strong> — the first statistically significant gain of the track (exp005’s came later chronologically).</p>
<p><strong>Interpretation.</strong> The plateau is slow, not absolute — but the rate settles the question. At +0.27 ppg per 2000 iterations, closing the ~2.3 ppg gap to GNUBG would take roughly <strong>17,000 more iterations</strong> of identical training. Iteration count alone is not a viable path.</p>
</section>
<section id="exp007" class="level2">
<h2 class="anchored" data-anchor-id="exp007">exp007 — self-play from the v5 supervised seed</h2>
<p><strong>Motivation.</strong> The <a href="./pretraining_analysis.html">supervised track</a> produced v5: a 10×256 net distilled from GNUBG 4-ply analysis that beats this track’s best checkpoint (exp005 iter_0447) 93-7 and reaches −1.59 ppg vs GNUBG. The question this whole track was building toward: does high-sim self-play <em>climb above</em> that seed — or regress it toward the self-play signal-quality ceiling?</p>
<p><strong>Setup.</strong> 800 sims, 8 games/iter, 50 iterations, lr 5×10⁻⁴, bootstrap α=0.5, Dirichlet noise, 25k buffer, warm-started from v5. iMac CPU, ~5.5 days.</p>
<p><strong>Results.</strong> It regressed, completely:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Opponent</th>
<th style="text-align: left;">Result</th>
<th style="text-align: left;">Equity</th>
<th style="text-align: left;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">v5 seed (its own starting point)</td>
<td style="text-align: left;">10-90</td>
<td style="text-align: left;">-1.740</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">iter_0447 (best self-play net)</td>
<td style="text-align: left;">51-49</td>
<td style="text-align: left;">+0.000</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GNUBG 2-ply</td>
<td style="text-align: left;">1-99</td>
<td style="text-align: left;">-2.240</td>
<td style="text-align: left;">100</td>
</tr>
</tbody>
</table>
<p>Fifty iterations took a network that dominated iter_0447 93-7 (+1.98 ppg) to dead parity with it (51-49), losing 10-90 (−1.74 ppg) to its own starting point; the GNUBG result fell from −1.59 back to −2.24 ppg — nearly the pre-pivot level. Meanwhile the <em>fitting</em> metrics looked fine: policy loss fell cleanly (2.94 → ~1.93 in six iterations, then stable) as the network successfully adapted to its self-play targets.</p>
<p><strong>Interpretation.</strong> Two mechanisms, both structural:</p>
<ol type="1">
<li><strong>Signal-quality ceiling.</strong> For self-play to improve a seed, MCTS must generate targets <em>better than the current prior</em>. MCTS(v5) at 800 sims reflects a player that loses 92% of its games to GNUBG 2-ply; training on those targets teaches the network to imitate a weaker player than the GNUBG 4-ply teacher that made the seed. The 25k buffer fully cycles in ~30 iterations, after which no trace of the supervised signal remains.</li>
<li><strong>Value-target mismatch.</strong> The v5 value head was calibrated to GNUBG <em>money equities</em> — smooth probability-weighted expectations. Self-play feeds it 50/50 blends of discrete terminal outcomes and MCTS Q — same numeric range, very different distribution — and pulled it steadily off calibration (value loss 0.022 → 0.028 over the run).</li>
</ol>
<p>One thing did <em>not</em> regress: the architecture. Even after full erosion of the supervised signal, the 10×256 net sat at parity with iter_0447 rather than below it. The training signal, not capacity, was the problem — and the fix (keep the expert in the loop, on the learner’s own positions) became <a href="./pretraining_analysis.html#exp008">exp008 in the supervised track</a>.</p>
</section>
<section id="cross-experiment-trends" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="cross-experiment-trends">Cross-experiment trends</h2>
<div id="971769e3" class="cell page-columns page-full" data-execution_count="11">
<div class="cell-output cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="training_analysis_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img column-page-right"></p>
</figure>
</div>
</div>
</div>
<div id="bbe4081e" class="cell page-columns page-full" data-execution_count="12">
<div class="cell-output cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="training_analysis_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img column-page-right"></p>
</figure>
</div>
</div>
</div>
<p>Three observations tie the track together:</p>
<ul>
<li><strong>Game quality never approaches strong play.</strong> Strong-vs-strong backgammon produces ~15–20% gammons and ~1% backgammons; self-play here runs 30–48% and 11–48% respectively. Half or more of self-play games end in gammon/backgammon — the fingerprint of players who leave checkers stranded and walk into large losses. Only exp005’s clean phase and exp006’s slow drift bend the curves at all.</li>
<li><strong>Loss is not strength — in either direction.</strong> exp002’s better loss curves bought nothing; exp004’s 3×-lower value loss bought nothing; exp005’s metric “collapse” cost nothing; exp007’s clean loss descent accompanied a −1.74 ppg regression. The only trustworthy test is a head-to-head arena at equal search.</li>
<li><strong>Compute cost.</strong> Self-play dominates wall time everywhere; SGD is ~3 s/iter on the GPU (200–500 s on CPU). exp001 cost ~27× exp000 per iteration; exp005 averaged ~61 min/iter on the T4 and ~459 GPU-hours total.</li>
</ul>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<ol type="1">
<li><strong>Pure self-play from random init plateaus far below GNUBG at this scale.</strong> Every checkpoint from exp000–exp006 scores −2.2 to −2.5 ppg (0–3% wins) against GNUBG 2-ply, and most interventions produced no within-run strength gain at all (<a href="#exp001">exp001</a>–<a href="#exp004">exp004</a>).</li>
<li><strong>Buffer size, exploration noise, value bootstrapping, and LR schedules were all ruled out</strong> as the binding constraint. Each moved fitting metrics; none moved play (<a href="#exp002">exp002</a>, <a href="#exp003">exp003</a>, <a href="#exp004">exp004</a>).</li>
<li><strong>Search depth at training time is the one self-play lever that worked</strong>: 800-sim MCTS produced a significant +0.38 ppg in 69 iterations (<a href="#exp005">exp005</a>). Iteration count also works, but ~25× slower per iteration of progress (<a href="#exp006">exp006</a>) — the combined rate math (~17k iterations to parity) rules out self-play-only scaling.</li>
<li><strong>Loss curves repeatedly misled in both directions</strong> — the decisive test is always a same-conditions arena match (<a href="#exp005">exp005</a>, <a href="#exp007">exp007</a>).</li>
<li><strong>Self-play destroys a strong supervised seed.</strong> MCTS under a GNUBG-losing prior generates targets weaker than the seed’s teacher, and discrete outcome targets decalibrate a money-equity value head; 50 iterations erased a +1.98 ppg advantage (<a href="#exp007">exp007</a>). Improving on a strong seed requires keeping a stronger-than-self signal in the loop.</li>
</ol>
</section>
<section id="what-happened-next" class="level2">
<h2 class="anchored" data-anchor-id="what-happened-next">What happened next</h2>
<p>The pivot this track motivated is documented in the <a href="./pretraining_analysis.html">supervised &amp; expert-iteration track</a>: distill GNUBG analysis into the network (stages v1–v5), then keep the GNUBG oracle in the loop on the learner’s own positions (exp008 DAgger, the Phase A consolidation, and exp009, a 25-round scale-up). That track broke the −1.6 ppg wall and holds the current best result (~−0.37 ppg vs GNUBG 2-ply, exp009 round 6), though it plateaued ~0.4 ppg short of parity against its fixed 2-ply teacher.</p>
<p>Beyond DAgger — which converges to its teacher by construction — the leading candidate for surpassing GNUBG is <strong>TD(λ) self-play from the distilled seed</strong>: TD-Gammon-style 1-ply value learning is ~20 value evals per decision instead of 100–800 MCTS sims, has no teacher ceiling, and avoids both exp007 failure modes (no MCTS policy targets, no discrete-outcome value drift — the value head bootstraps toward the next position’s own equity estimate). Deeper-ply distillation was priced out as an alternative: GNUBG 3-ply labels cost ~53× 2-ply per label for a teacher we intend to outgrow anyway. exp010 is the first test of it.</p>
</section>
<section id="exp010" class="level2">
<h2 class="anchored" data-anchor-id="exp010">exp010 — TD(λ) self-play from a distilled seed</h2>
<p><strong>Motivation.</strong> Conclusion 5 is that <em>MCTS</em> self-play destroys a strong seed. TD(λ) self-play should not: it regresses the value head toward the next position’s own equity estimate — not discrete terminal outcomes, not MCTS-visit targets — so neither exp007 mechanism applies. TD-Gammon proved this exact recipe reaches world class in backgammon. The question is whether it lifts <em>our</em> strong seed, and how far.</p>
<p><strong>Setup.</strong> Warm-start from <a href="./pretraining_analysis.html#exp009">exp009</a> round_06 (10×256, 26-channel — the project’s best distilled net). Play 1-ply-greedy self-play (the dice supply exploration), compute forward-view TD(λ) targets (λ=0.7), and regress the <strong>value head only</strong> (policy head frozen). Local on the iMac CPU, ~150 games/batch across 3 workers, conservative lr 10⁻⁴, keep-best by the fixed external reference below (<code>scripts/train_td.py</code>, <code>raccoon/train/td_selfplay.py</code>).</p>
<p><strong>The eval trap, and the fix.</strong> The first cut scored each batch against the <em>frozen seed</em> and read +1.9 ppg after one batch — implausible, and exactly conclusion 4 restated: a self-play net can beat its own seed while getting no stronger absolutely. Diagnostics confirmed the metric was hollow — the arena was not buggy (seed vs itself ≈ 0) and the win was not seed-specific (the net beat an <em>independent</em> exp009 checkpoint, round_25, equally, +1.95) — but the exp009 nets simply <strong>play 1-ply badly</strong>: their value heads were trained for MCTS, so “who is better at 1-ply greedy” is not “who is stronger.” Switching the reference to <strong>GNUBG at 0-ply</strong> — a fixed opponent the net never trains against, ~0.007 ppg weaker than 2-ply but ~100× cheaper and local via <code>gnubg_nn</code> — makes the number honest.</p>
<p><strong>Results.</strong></p>
<div id="341a76e7" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="training_analysis_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Two facts, against the honest metric:</p>
<ol type="1">
<li><strong>TD self-play <em>works</em> — it improves the seed, where MCTS self-play destroyed it.</strong> The seed plays 1-ply at −2.30 ppg vs GNUBG-0-ply; TD hauls it to ~−0.3 (best-of-batch −0.08) in the first few hundred games. This is the first self-play result on the project to <em>lift</em> a strong seed rather than wreck it — the value-only bootstrap from a money-calibrated head is the difference from exp007.</li>
<li><strong>But it plateaus fast, ~0.3 ppg short of 0-ply.</strong> The gain is banked by batch 2; batches 2–29 oscillate around −0.3 (n=60 eval, SE ~0.23) with no sustained climb. A few hundred games saturate the 1-ply value quality; more do not compound — a plateau after <em>hundreds</em> of games, not thousands, points to a recipe/capacity limit, not a data-volume one.</li>
</ol>
<p><strong>Interpretation.</strong> TD(λ) self-play is validated as a direction — the first method here to lift a strong seed via self-play — but on this recipe it stops ~0.3 short of even 0-ply parity, far from surpassing it. Reaching then surpassing 0-ply likely needs one of: a less greedy recipe (the run was pure argmax; temperature/exploration is untested), a stronger 1-ply starting point (distill <em>to</em> 0-ply parity first, then TD from there — the seed’s −2.30 start capped the ceiling), or the value-head changes tracked in the <a href="./pretraining_analysis.html#open-questions">pretraining track’s open questions</a>. The eval-metric episode also re-confirms conclusion 4 with force: <strong>a self-play loop must be scored against a fixed external reference, never its own seed.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lassehjorthmadsen\.github\.io\/raccoon\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>