<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Variance-Reduced Rollouts – Raccoon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e3adbaa939bcd423dddc8c8a834270b4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Variance-Reduced Rollouts – Raccoon">
<meta property="og:description" content="How Raccoon measures a 0.05-point-per-game edge without playing hundreds of thousands of games — and the evidence it isn’t cheating">
<meta property="og:image" content="https://research.raccoonbg.com/variance_reduction_files/figure-html/cell-7-output-1.png">
<meta property="og:site_name" content="Raccoon">
<meta property="og:image:height" content="587">
<meta property="og:image:width" content="947">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Raccoon</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-concepts" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Concepts</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-concepts">    
        <li>
    <a class="dropdown-item" href="./mcts_explained.html">
 <span class="dropdown-text">MCTS Explained</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./architecture.html">
 <span class="dropdown-text">Architecture</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-training" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Training</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-training">    
        <li>
    <a class="dropdown-item" href="./training_parameters.html">
 <span class="dropdown-text">Parameters</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./training_analysis.html">
 <span class="dropdown-text">Self-Play Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pretraining_analysis.html">
 <span class="dropdown-text">Supervised &amp; Expert Iteration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./variance_reduction.html">
 <span class="dropdown-text">Variance-Reduced Rollouts</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./gcp_guide.html"> 
<span class="menu-text">Developer</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reference/index.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-problem-in-numbers" id="toc-the-problem-in-numbers" class="nav-link active" data-scroll-target="#the-problem-in-numbers">The problem, in numbers</a></li>
  <li><a href="#the-method" id="toc-the-method" class="nav-link" data-scroll-target="#the-method">The method</a></li>
  <li><a href="#how-raccoon-implements-it" id="toc-how-raccoon-implements-it" class="nav-link" data-scroll-target="#how-raccoon-implements-it">How Raccoon implements it</a></li>
  <li><a href="#is-it-unbiased" id="toc-is-it-unbiased" class="nav-link" data-scroll-target="#is-it-unbiased">Is it unbiased?</a></li>
  <li><a href="#how-much-does-it-buy" id="toc-how-much-does-it-buy" class="nav-link" data-scroll-target="#how-much-does-it-buy">How much does it buy?</a></li>
  <li><a href="#exp019" id="toc-exp019" class="nav-link" data-scroll-target="#exp019">exp019 — does <code>exp018/ep22</code> beat GNUBG-0-ply?</a></li>
  <li><a href="#exp020" id="toc-exp020" class="nav-link" data-scroll-target="#exp020">exp020 — the doubles execution bug</a></li>
  <li><a href="#what-this-does-and-does-not-change" id="toc-what-this-does-and-does-not-change" class="nav-link" data-scroll-target="#what-this-does-and-does-not-change">What this does and does not change</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Variance-Reduced Rollouts</h1>
<p class="subtitle lead">How Raccoon measures a 0.05-point-per-game edge without playing hundreds of thousands of games — and the evidence it isn’t cheating</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Raccoon is a backgammon engine, and the only claim that ultimately matters about one is <em>does it win?</em> So its strength is settled by playing games against a reference opponent — here GNU Backgammon — and reporting the average margin in <strong>points per game (ppg)</strong> under cubeless money scoring: a plain win counts 1, a gammon 2, a backgammon 3. Both sides play at <strong>0-ply</strong>, meaning each ranks its legal moves by a static evaluation of the resulting position, with no further search.</p>
<p>That is the honest way to measure an engine, and it is also where the project kept hitting a wall: <strong>backgammon between two strong engines is almost entirely dice</strong>. A single game’s result swings by more than a point, while the difference we need to resolve is around 0.05. Separating a real edge that small from dice noise takes tens of thousands of games — and to say it <em>precisely</em>, hundreds of thousands.</p>
<p>This page documents the tool that removes most of that noise, the argument for why it does not distort the answer, and a demonstration that it behaves as claimed. It then puts it to work twice: <a href="#exp019">exp019</a>, the first head-to-head measurement of <code>exp018/ep22</code>, the project’s strongest network — and <a href="#exp020">exp020</a>, which chases down a discrepancy exp019 exposed and finds a real bug in how the engine plays doubles. The second would not have been findable without the first: at the old resolution, the effect was invisible.</p>
<p>The technique is not new — it is what eXtreme Gammon, GNU Backgammon and BGSage all do in their rollouts, and this project pre-registered it as future work after a cheaper shortcut turned out to be biased. What is new here is the implementation, and the evidence that it works.</p>
<section id="the-problem-in-numbers" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-in-numbers">The problem, in numbers</h2>
<p>A backgammon result is worth ±1 (plain win), ±2 (gammon) or ±3 (backgammon). Two near-equal players trade those outcomes almost at random, so over the 6,000 games played for <a href="#exp019">exp019</a> the per-game result has a standard deviation of <strong>1.37</strong> — some 27 times the effect we are trying to detect. The 95% confidence interval on the mean shrinks only as 1/√n:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>games</th>
<th>95% CI on raw ppg</th>
<th>wall-clock on 3 CPU workers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100</td>
<td>±0.269</td>
<td>3 min</td>
</tr>
<tr class="even">
<td>1,000</td>
<td>±0.085</td>
<td>33 min</td>
</tr>
<tr class="odd">
<td>6,000</td>
<td>±0.035</td>
<td>3.3 h</td>
</tr>
<tr class="even">
<td>100,000</td>
<td>±0.009</td>
<td>2 days</td>
</tr>
<tr class="odd">
<td>254,434</td>
<td>±0.005</td>
<td>6 days</td>
</tr>
</tbody>
</table>
<p>The project’s standard benchmark, n=6,000, buys ±0.035. Against a hypothesised edge of +0.05 that is a 2σ test with roughly 55% power — barely better than a coin flip on whether a real effect shows up at all. And reaching ±0.005, the precision actually achieved below, would take about <strong>254,434 games</strong>: 42× the compute, and the bottom row of that table.</p>
<p>So the question is not how to buy more games. It is whether the same games can be made to say more.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A correction found along the way: the per-game SD is 1.36, not 1.8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This project has assumed a per-game equity SD of <strong>1.8</strong> since its earliest benchmarks, and <code>scripts/eval_gnubg0.py</code> hard-coded it. Measuring it directly here shows that 1.8 is the <strong>variance</strong>, not the standard deviation: over 1,000 games the outcome distribution is -3: 0.6%, -2: 12.7%, -1: 33.1%, +1: 40.3%, +2: 12.7%, +3: 0.6%, whose variance is 1.85 — and whose standard deviation is therefore <strong>1.36</strong>.</p>
<p>The consequence is that every raw-ppg confidence interval the project has published is about <strong>1.32× too wide</strong> — n=6,000 gives ±0.034, not the ±0.046 previously quoted. Every such interval was therefore <em>conservative</em>, so no earlier conclusion is overturned; the affected results (for instance <a href="./pretraining_analysis.html#exp011b">exp011b</a>’s −0.053 ± 0.046, which becomes −0.053 ± 0.034) get stronger, not weaker. <code>eval_gnubg0.py</code> now computes the interval from the sample instead of assuming a constant.</p>
<p>One caveat on generalising it: this SD is measured at <em>near-parity</em>. A weaker network losing many gammons has a wider outcome distribution, which is the most likely origin of the 1.8 figure in the first place.</p>
</div>
</div>
</div>
</section>
<section id="the-method" class="level2">
<h2 class="anchored" data-anchor-id="the-method">The method</h2>
<p>They can, because most of that variance is <em>identifiable</em>. When a player rolls double sixes and hits, the result swings for a reason we can point at, and — crucially — for a reason we can put a number on <strong>before knowing how the game turns out</strong>.</p>
<p>At every pre-roll position <span class="math inline">\(s\)</span>, before the dice are thrown, define</p>
<p><span class="math display">\[h(s, d) \;=\; \text{equity after best play of roll } d, \text{ from a fixed player's point of view}\]</span></p>
<p><span class="math display">\[m(s) \;=\; \sum_d p(d)\, h(s, d) \qquad\qquad \text{luck} \;=\; h(s, d_{\text{actual}}) - m(s)\]</span></p>
<p><span class="math inline">\(m(s)\)</span> is what the position was worth <em>before</em> the roll: the average over all 21 distinct rolls, doubles weighted 1/36 and non-doubles 2/36. (The opening roll is the one exception — doubles are re-rolled there, so it averages over 30 equally likely outcomes instead, and the position is symmetric, so that average is exactly zero.) The luck of the roll that actually came up is how much better or worse than that average it was. Accumulate this over <strong>both</strong> players’ rolls for a whole game — a good roll for the opponent is bad luck for us, with the sign flipped — and report</p>
<p><span class="math display">\[\text{vr} \;=\; \text{raw game result} \;-\; \textstyle\sum_t \text{luck}_t\]</span></p>
<section id="a-worked-example-the-opening-roll" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-example-the-opening-roll">A worked example: the opening roll</h3>
<p>The clearest case is the very first roll, because the position before it is symmetric and therefore worth exactly zero to both players. Whatever the roll turns out to be worth is <em>pure</em> luck. Here is what Raccoon’s control variate says about it, from the roller’s point of view:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>best openers</th>
<th>luck</th>
<th>worst openers</th>
<th>luck</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3-1</td>
<td><strong>+0.160</strong></td>
<td>2-1</td>
<td><strong>−0.006</strong></td>
</tr>
<tr class="even">
<td>4-2</td>
<td>+0.114</td>
<td>4-1</td>
<td>−0.003</td>
</tr>
<tr class="odd">
<td>6-1</td>
<td>+0.091</td>
<td>5-1</td>
<td>+0.001</td>
</tr>
</tbody>
</table>
<p>Win the opening roll with 3-1 and you bank about a sixth of a point before playing a single checker; the estimator hands that back. Win it with 2-1 and you have gained nothing at all — after your reply the opponent is on roll, and that is worth about as much as your move was.</p>
<p>This is also a free correctness check, because backgammon players already know the answer: 3-1, 4-2 and 6-1 — making the 5-point, the 4-point and the bar-point — are the three best opening rolls, and the 1-plays that neither point nor prime are the weakest. Nothing in the implementation was tuned to produce that ordering; it falls out of GNUBG’s evaluation. And the 30 values average to zero to twelve decimal places, as symmetry demands.</p>
</section>
<section id="why-this-doesnt-bias-the-answer" class="level3">
<h3 class="anchored" data-anchor-id="why-this-doesnt-bias-the-answer">Why this doesn’t bias the answer</h3>
<p>The obvious worry is that we are adjusting results using an estimate, and estimates are wrong. The reason it is safe is that the correction has <strong>mean exactly zero, by construction</strong>:</p>
<p><span class="math display">\[\mathbb{E}\big[\text{luck}_t \,\big|\, \text{history}\big] \;=\; \sum_d p(d)\, h(s_t, d) \;-\; m(s_t) \;=\; 0\]</span></p>
<p>because <span class="math inline">\(m(s_t)\)</span> <em>is</em> that sum. This holds for every roll regardless of what <span class="math inline">\(h\)</span> is, so the accumulated correction is a mean-zero martingale, and subtracting it cannot move the expectation of the estimator. As David Montgomery put it in <a href="https://bkgm.com/articles/GOL/Feb00/var.htm">the canonical explanation of the technique</a>:</p>
<blockquote class="blockquote">
<p>The luck associated with a roll […] averages zero. That’s the way averages work. […] Subtracting zero can’t change the expected value of a rollout. No matter how poorly a program understands a position, luck estimates will still average zero.</p>
</blockquote>
<p>A bad evaluator makes the technique <em>less useful</em> — the correction correlates less with the result, so less variance is removed — but never makes it <em>wrong</em>. That is an unusually forgiving property, and it is the whole reason this is worth doing.</p>
</section>
<section id="the-rule-that-makes-it-self-consistent" class="level3">
<h3 class="anchored" data-anchor-id="the-rule-that-makes-it-self-consistent">The rule that makes it self-consistent</h3>
<p>There is one way to break it, and this project has already broken it once.</p>
<p><span class="math inline">\(h\)</span> must be the same function on both legs of the subtraction, and in particular <strong>it must not depend on the move actually played</strong>. Raccoon always uses GNUBG’s 0-ply best-play value for whoever is on roll — whatever either side actually does, and at whatever ply they think. If Raccoon blunders, no luck term changes; the cost lands in the raw result and in the next pre-roll position, which is exactly where it belongs.</p>
<p>An earlier metric in this project, “error-rate ppg”, violated this. It charged the network for the equity its chosen move conceded, against a pre-roll value that was not that quantity’s own dice-average. The implicit luck term was therefore not zero-mean, and the metric read <strong>−0.128</strong> where the truth was about <strong>−0.05</strong>: a bias of ~0.07 ppg, larger than the effects it was being used to measure. It was dropped in July 2026 and the correct construction noted as future work. This page is that future work.</p>
<p>The same trap is visible in other engines. BGSage evaluates the <em>played</em> move on the actual leg against the <em>1-ply-best</em> move in the mean; when its decision ply exceeds its variance-reduction ply those differ, leaving a small residual bias it polices with a paired t-test. Raccoon’s formulation closes that gap by never letting the played move enter the control variate at all.</p>
</section>
</section>
<section id="how-raccoon-implements-it" class="level2">
<h2 class="anchored" data-anchor-id="how-raccoon-implements-it">How Raccoon implements it</h2>
<p>The estimator lives in <a href="https://github.com/lassehjorthmadsen/raccoon/blob/main/raccoon/eval/luck.py"><code>raccoon/eval/luck.py</code></a>, the match loop in <a href="https://github.com/lassehjorthmadsen/raccoon/blob/main/raccoon/eval/vr_arena.py"><code>raccoon/eval/vr_arena.py</code></a>, and the driver in <code>scripts/eval_gnubg_vr.py</code>. Four implementation decisions are worth recording, because three of them were bugs first.</p>
<p><strong>The 21-roll sweep is native, and it is nearly free.</strong></p>
<p>The obvious route — loop over every legal move of every roll and ask GNUBG to evaluate each resulting position — costs about <strong>260 ms</strong> per pre-roll position, which would have made variance reduction roughly thirteen times more expensive than the game it is measuring. Going through <code>gnubg_nn.best_move</code>, which generates and ranks a whole roll (all four half-moves of a double included) inside C, costs <strong>~2.6 ms</strong> for the same 21-roll sweep, and agrees with the slow route exactly.</p>
<p>Over the 56 pre-roll positions of an average game that is ~0.15 s of extra work against a game that costs ~6.2 s to play: a <strong>~2% overhead</strong> for a 42-fold gain in statistical efficiency. (End-to-end wall-clock on the two demonstration arms — identical games, differing only in whether the correction was computed — came out at 6.19 s and 6.16 s per game, in the same range; those runs share a desktop with other work, so the arithmetic above is the more reliable figure.)</p>
<p><strong>Terminal rolls need their exact value.</strong> The adapter’s <code>candidate_equities</code> reports a flat <code>+3.0</code> for any move that ends the game — correct for <em>ranking</em> moves, since a win is a win, but catastrophic here: it would score every game-ending roll as a backgammon and inject a large spurious luck term at the end of every game. The sweep instead classifies the finished position properly into 1.0 / 2.0 / 3.0.</p>
<p><strong>GNUBG’s own move-list equities are not trustworthy in races.</strong> <code>best_move</code> returns a detail tuple with probabilities and an equity, and using them directly looked natural. On a bear-off position it reported <code>P(win) = 1.0</code> and equity <code>0.912</code> for a position that <code>probabilities()</code> scores at <code>0.982</code> with the opponent still winning 5.7% of the time. So <code>best_move</code> is used for <strong>move generation only</strong>; the position it lands on is reconstructed from the returned position key and re-evaluated through the same <code>probabilities()</code> call the rest of the project uses. With that fix the fast route agrees with the slow one <strong>exactly</strong> — 2,160 of 2,160 rolls across 60 real pre-roll positions, doubles and game-ending rolls included.</p>
<p><strong>The control variate is 0-ply, and must be.</strong> <code>best_move</code> segfaults at ply ≥ 1 on real bear-off boards, so anything deeper is refused outright rather than risked mid-run. This costs nothing: evaluating each roll’s best reply <em>is</em> one ply of lookahead, so a 0-ply leaf already yields a 1-ply pre-roll mean — the same depth GNUBG and BGSage use for their own variance reduction. The opponent’s playing strength is a separate setting and can be anything.</p>
<p>One more property matters for how the demonstration below is framed: <strong>the control variate touches no randomness</strong>. It reads GNUBG through a pure C path and draws the roll from the same call on the same distribution whether or not it is enabled. Turning variance reduction on therefore plays <em>identical games</em> from the same seed — asserted in <code>tests/test_luck.py</code>.</p>
</section>
<section id="is-it-unbiased" class="level2">
<h2 class="anchored" data-anchor-id="is-it-unbiased">Is it unbiased?</h2>
<p>Three checks — two exact, one empirical.</p>
<p><strong>The zero-mean property is asserted directly, in CI.</strong> <code>test_luck_is_zero_mean_exact</code> enumerates every outcome of real pre-roll positions through the production code path and checks that the probability-weighted luck sums to zero to within 1e-9, from both players’ perspectives. This is the property everything rests on, so it is tested rather than reasoned about. Two supporting tests cover the ways it can silently break: the chance-action-to-dice table is verified against OpenSpiel’s own labels at both node sizes, and the fast sweep is verified against OpenSpiel’s move generation roll by roll.</p>
<p><strong>The opening position gives a free exact check</strong>, as shown <a href="#a-worked-example-the-opening-roll">above</a>: its pre-roll mean is zero to twelve decimal places even though individual opening rolls are worth up to +0.16, and the ranking of those rolls matches established backgammon theory. A sign error, a mis-mapped dice table or a perspective flip would all show up here immediately, so this is asserted as a test too.</p>
<p><strong>Empirically, the correction has no detectable mean.</strong></p>
<p>Over the 6,000 games of <a href="#exp019">exp019</a> the accumulated luck averages <strong>-0.0028 ± 0.0345</strong> points per game (t = -0.16) — consistent with zero, as it must be. Equivalently: the raw and variance-reduced estimates of the same quantity, on the same games, are <strong>+0.0102</strong> and <strong>+0.0129</strong>, and they differ by exactly that mean luck.</p>
<p><strong>What is missing, on the record.</strong> The strongest possible check would have been external: re-measure <code>exp011b/ep3</code>, the one checkpoint with a published raw answer (−0.053 ± 0.046 at n=6,000), and confirm the variance-reduced estimate lands inside that interval with a far tighter one. That run was considered and deliberately skipped to save an overnight slot. The evidence above is solid but all internal, and this remains the first follow-up if the result below ever looks surprising.</p>
</section>
<section id="how-much-does-it-buy" class="level2">
<h2 class="anchored" data-anchor-id="how-much-does-it-buy">How much does it buy?</h2>
<p>Two independent sets of matches, played with the same network against the same opponent: twenty matches of fifty games with variance reduction <strong>off</strong>, then twenty more with it <strong>on</strong>, on different dice. Nothing is shared between the two sets — they are separate samples of the same process, which is legitimate precisely because enabling the correction does not change how the games are played.</p>
<div id="66010ee7" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>matches</th>
<th>mean of match results</th>
<th>95% CI</th>
<th>SD across matches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>no variance reduction</td>
<td>20</td>
<td>+0.0720</td>
<td>±0.0962</td>
<td><strong>0.2195</strong></td>
</tr>
<tr class="even">
<td>variance reduced</td>
<td>20</td>
<td>+0.0034</td>
<td>±0.0124</td>
<td><strong>0.0283</strong></td>
</tr>
</tbody>
</table>
<p>The two arms disagree entirely on how confidently they speak: the spread across matches is <strong>7.8× narrower</strong>, which at equal precision is worth <strong>60× as many games</strong>. Twenty matches is a thin basis for a ratio, so that figure carries a bootstrap 95% interval of [4.8×, 12.4×]. The picture is the point here; the number comes from the 6,000-game run below, where the same ratio is <strong>6.51×</strong> (42× the games).</p>
<p>They also agree on the answer — the arm means differ by +0.0686 ± 0.0970, which is consistent with zero. That is a weak statement rather than a strong one, and worth being explicit about: the interval is wide almost entirely because of the raw arm, which is exactly the problem being solved. It rules out a gross bias, not a subtle one; the sharp unbiasedness evidence is the exact zero-mean property above.</p>
<section id="why-it-works-this-well" class="level3">
<h3 class="anchored" data-anchor-id="why-it-works-this-well">Why it works this well</h3>
<div id="8b572b81" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The left panel is the mechanism: accumulated luck explains <strong>97.6%</strong> of the variance in the raw result (r = 0.988), and the cloud sits on the 45° line rather than merely near it. Backgammon between two strong engines really is mostly a dice-reading exercise, and a one-ply lookahead reads the dice well enough to account for nearly all of it. What survives the subtraction is the part that is actually about skill.</p>
<p>That the relationship sits on the diagonal is itself a calibration check. Fitting the regression-optimal coefficient — the β that would minimise variance in <code>raw − β·luck</code> — gives <strong>β̂ = 0.995</strong>, within a few thousandths of the 1.0 the estimator uses. (The estimator keeps β = 1 deliberately: any <em>fixed</em> coefficient stays exactly unbiased, whereas one fitted on the same sample does not.)</p>
<p>The right panel is the practical consequence. Both estimators are computed from the same 6,000 games and converge on the same answer, but not at the same speed: the variance-reduced estimate is already tighter after <strong>142 games</strong> than the raw one is after all 6,000.</p>
</section>
</section>
<section id="exp019" class="level2">
<h2 class="anchored" data-anchor-id="exp019">exp019 — does <code>exp018/ep22</code> beat GNUBG-0-ply?</h2>
<p><strong>Motivation.</strong> <code>exp018/ep22</code> is the project’s best network, and on the static <a href="./pretraining_analysis.html#exp018">BGSage benchmark</a> it is already past GNUBG-0-ply — PR 0.950 over 14,693 checker decisions, rollout-tier MSE 0.00190 over ~149k candidates, both better than the 0-ply reference. But a static benchmark scores move <em>choices</em> against a fixed position set; it does not play games. The exp018 write-up flagged the gap explicitly: a raw-ppg confirmation at matched search was still outstanding. Until now it was not affordable.</p>
<p><strong>Setup.</strong> <code>exp018-distill/ep22</code> (10×256, six-outcome value head) playing 0-ply greedy value lookahead against GNUBG at 0-ply, cubeless money scoring, seats alternated. Primary metric fixed in advance in <code>experiments/pipeline_exp019.sh</code>: <strong>variance-reduced ppg, n = 6,000 games</strong>, 95% CI from the empirical SD of the per-game variance-reduced values. One arm only — <code>ep22</code> was selected on the BGSage benchmark, an independent metric on independent data, so this is a clean confirmation with no winner’s-curse correction needed, and no epoch sweep was run on this metric.</p>
<p><strong>Results.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>estimator</th>
<th>ppg vs GNUBG-0-ply</th>
<th>95% CI</th>
<th>interval</th>
<th>per-game SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>raw (unbiased ruler)</td>
<td>+0.0102</td>
<td>±0.0348</td>
<td>[-0.025, +0.045]</td>
<td>1.374</td>
</tr>
<tr class="even">
<td><strong>variance reduced</strong></td>
<td><strong>+0.0129</strong></td>
<td><strong>±0.0053</strong></td>
<td>[+0.0076, +0.0183]</td>
<td>0.211</td>
</tr>
</tbody>
</table>
<p>n = 6,000 games, 3,022 wins (50.4%). Supporting diagnostics: mean luck -0.0028 (t = -0.16), corr(raw, luck) = 0.988, β̂ = 0.995, SD ratio 6.51× (42× the games).</p>
<p><strong>Interpretation.</strong> The variance-reduced interval [+0.0076, +0.0183] excludes zero (z = +4.8), so on this evidence <code>ep22</code> <strong>beats</strong> GNUBG-0-ply in head-to-head play. The raw estimator, on the <em>very same games</em>, cannot resolve it at all: +0.0102 ± 0.0348, an interval spanning both a meaningful edge and a meaningful deficit — consistent with the variance-reduced value, as it must be, since the two differ by exactly the mean luck. That contrast is the point of this page: matching this precision by brute force would have taken roughly 254,434 games, 42× what was actually played.</p>
<p>The remaining caveats are unchanged. This is 0-ply against 0-ply and cubeless, so it says nothing yet about GNUBG at 2-ply, and nothing about cube handling.</p>
<p>It does, however, settle a question the project has carried since the distillation track began. The static <a href="./pretraining_analysis.html#exp018">BGSage benchmark</a> had already put <code>ep22</code> past GNUBG-0-ply on move-selection error and on value accuracy; play now agrees on the <strong>direction</strong>. A network distilled from GNUBG has passed its own teacher at matched search, over the board and not merely on a scorecard.</p>
<p>The two do <em>not</em> agree on the <strong>size</strong> of the edge, which is the subject of the next section.</p>
<section id="cross-check-what-the-static-benchmark-predicted" class="level3">
<h3 class="anchored" data-anchor-id="cross-check-what-the-static-benchmark-predicted">Cross-check: what the static benchmark predicted</h3>
<p>The <a href="./pretraining_analysis.html#exp015">BGSage benchmark</a> scores an engine’s move choices against rollout-quality references and reports <strong>PR</strong> — mean equity error per checker decision, ×500. Because that is an error <em>rate</em> in points, it makes a falsifiable prediction about points per game, and this is the first time the project has been able to test it.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>PR (n = 14,693)</th>
<th>equity error per decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GNUBG, 0-ply</td>
<td>2.145</td>
<td>0.00429</td>
</tr>
<tr class="even">
<td><code>exp018/ep22</code></td>
<td>0.950</td>
<td>0.00190</td>
</tr>
<tr class="odd">
<td><strong>difference</strong></td>
<td><strong>1.195</strong></td>
<td><strong>0.00239</strong></td>
</tr>
</tbody>
</table>
<p>A game runs 56.1 rolls, so each side makes about 28 checker decisions. If error rates simply accumulated, ep22’s advantage would be 0.00239 × 28 ≈ <strong>+0.067 ppg</strong>. Measured: <strong>+0.0129 ± 0.0053</strong>.</p>
<p><strong>Those do not agree</strong> — the measured edge falls short of the predicted one by 0.054 ppg, about 20 standard errors. Both numbers are sound on their own terms, so the discrepancy is real and worth naming rather than smoothing over. Two explanations are available, and they are testable:</p>
<ol type="1">
<li><p><strong>The benchmark’s positions are not the positions that arise in this matchup.</strong> BGSage’s set comes from Sage 3-ply self-play. An error rate measured there need not transfer to the distribution generated by ep22 playing GNUBG, and a rate advantage concentrated in positions that rarely occur here would buy little.</p></li>
<li><p><strong>The network cannot execute a doubles turn as well as it can evaluate one.</strong> This is the more specific candidate, and the arithmetic fits. On the benchmark every candidate is a <em>complete</em> move, and the network scores the finished position. In play, OpenSpiel splits a double into two consecutive decisions, and <code>raccoon/train/lookahead.py</code> ranks the first half by the static value of the <em>intermediate</em> position — a position the value head never saw in training, having been trained on pre-roll positions only. It then picks the second half greedily. GNUBG, through <code>candidate_equities</code>, recurses and optimises all four half-moves jointly. So on doubles the two engines are not playing by the same rule, and only one of them is handicapped.</p>
<p>Doubles are 1/6 of turns, or about 4.7 per player per game. Absorbing the 0.054 ppg shortfall would take a loss of only <strong>0.012 points per doubles turn</strong> — an entirely ordinary cost for greedy-decomposed play against joint optimisation over four half-moves.</p></li>
</ol>
<p>Explanation 2 predicts something checkable, and <a href="#exp020">exp020</a> below checks it: if the two-step path is really conceding equity, then replacing it with joint enumeration should recover points <em>without touching the weights</em> — a <strong>strength bug</strong>, not a measurement artefact, and one that would convert a benchmark advantage the network already has into points it does not currently collect.</p>
<p><strong>Conclusion.</strong></p>
<blockquote class="blockquote">
<p>Does <code>exp018/ep22</code> beat GNUBG-0-ply? → <strong>Yes</strong>: ep22 = <strong>+0.0129 ± 0.0053</strong> (variance-reduced ppg vs GNUBG-0-ply, n=6,000).</p>
</blockquote>
<p>That number stands as measured, but it is <strong>not</strong> the current engine’s strength. <a href="#exp020">exp020</a> below found a bug in how it executed doubles; the same weights, playing correctly, score considerably higher.</p>
</section>
</section>
<section id="exp020" class="level2">
<h2 class="anchored" data-anchor-id="exp020">exp020 — the doubles execution bug</h2>
<blockquote class="blockquote">
<p><strong>Hypothesis.</strong> Raccoon’s greedy two-step doubles execution is a strength bug, and fixing it collects ppg the static benchmark says the network has already earned.</p>
</blockquote>
<p>When you roll a double in backgammon you play <strong>four</strong> half-moves, not two. OpenSpiel models that by splitting the turn into two consecutive decisions by the same player, two half-moves each, with no dice roll in between. That is a reasonable way to keep the action space small, and it quietly created an asymmetry in the arena.</p>
<p>GNUBG’s side handled it correctly. <code>candidate_equities</code> <strong>recurses</strong>: it scores each half-1 option by the best half-2 continuation available after it, so all four half-moves are chosen together.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> child.current_player() <span class="op">==</span> me:</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Doubles half-1 still pending a half-2 by the same player. Our</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># equity for this half-1 action is the best over the half-2 subgame.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    my_equity <span class="op">=</span> <span class="bu">max</span>(eq <span class="cf">for</span> _, eq <span class="kw">in</span> candidate_equities(child, ply))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Raccoon’s side did not. It ranked half-1 by the static value of the <strong>intermediate</strong> position — the board halfway through its own turn — and then chose half-2 greedily. Worse, the value head cannot evaluate such a position even in principle: <code>encode_pre_roll</code> hands it over with the dice cleared and the mid-doubles flag off, which says <em>“you are about to roll”</em> about a position where the mover still owes two half-moves of a known die. The network was never trained on anything like it, and could not have been — <code>gen_gnubg_selfplay.py</code> writes one record per turn at the start-of-turn pre-roll and skips mid-doubles states outright, so none of the 40M distilled positions is one.</p>
<p>Doubles are 1/6 of rolls, and about four fifths of them leave enough legal play to need both decisions — measured below at 3.79 such turns per game. On every one of those the two engines were not playing by the same rule, and only one of them was handicapped.</p>
<p>None of this shows up on the BGSage benchmark, where every candidate is a <em>complete</em> move and the network simply scores the finished position. That is precisely why the benchmark could rate <code>ep22</code> above GNUBG-0-ply while play did not: the benchmark measures the value function, and the bug is in the search around it.</p>
<section id="what-it-costs" class="level3">
<h3 class="anchored" data-anchor-id="what-it-costs">What it costs</h3>
<p>The fix is to give Raccoon the same recursion GNUBG already had, so both sides optimise the whole turn. That is a pure inference-time change: identical weights, identical benchmark score, different search. Before running it over 6,000 games, the cost of the old path was measured directly. At every turn, both arms are played out on clones from the same position and the resting positions compared:</p>
<p><span class="math display">\[\text{concession} = \mathrm{eq}_{\text{GNUBG}}(\text{final}_{\text{joint}}) - \mathrm{eq}_{\text{GNUBG}}(\text{final}_{\text{greedy}})\]</span></p>
<p>Both finals come from the <strong>same network</strong>, so this isolates how the value function is <em>searched</em> from how good it is. GNUBG at 2-ply prices the difference, and only when the two arms actually disagree — when they land on the same position the concession is exactly zero. The games play the greedy arm, so the sample is the exp019 playing distribution.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>games</td>
<td>1,500</td>
</tr>
<tr class="even">
<td>net turns scored</td>
<td>41,626</td>
</tr>
<tr class="odd">
<td>of which two-step doubles turns</td>
<td>5,685 (3.79/game)</td>
</tr>
<tr class="even">
<td>greedy and joint pick different moves</td>
<td><strong>15.9%</strong> of them</td>
</tr>
<tr class="odd">
<td>mean concession when they differ</td>
<td><strong>+0.0624</strong></td>
</tr>
<tr class="even">
<td>mean concession per doubles turn</td>
<td><strong>+0.00911 ± 0.00111</strong></td>
</tr>
<tr class="odd">
<td><strong>implied cost</strong></td>
<td><strong>+0.0345 ± 0.0042 ppg</strong></td>
</tr>
<tr class="even">
<td>same, judged at 0-ply instead of 2-ply</td>
<td>+0.0326 ppg</td>
</tr>
</tbody>
</table>
<p>The two engines agree on most doubles turns; the damage is concentrated in the 16% where they do not, and there it averages +0.062 — blunder-sized. Set against the 0.054 ppg shortfall exp019 could not explain, this accounts for <strong>64%</strong> of it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The control that makes this measurable
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A concession this small is only worth reporting if the machinery producing it is known to be right. The check is built in: <strong>non-doubles turns</strong>. A turn that needs one OpenSpiel action has one leaf per legal action, so both arms enumerate the identical set and <em>must</em> agree — exactly, not approximately. Any non-zero concession there would be a harness bug (a bad resting signature, a sign error, a mis-priced terminal), and it would be indistinguishable from a real effect if it went unnoticed.</p>
<p>Over <strong>35,941</strong> non-doubles turns in this run: <strong>0 disagreements</strong>, maximum absolute concession <strong>0.0e+00</strong>. The same property is pinned at the <code>child_values</code> level in <code>tests/test_doubles.py</code>, so it cannot regress silently.</p>
<p>Note also what the arithmetic does <em>not</em> depend on. Because every non-doubles turn scores exactly zero, the total concession per game is the same number whether or not a turn is classified as doubles correctly — the headline is robust to that judgement call, and only the per-turn averages above use it.</p>
</div>
</div>
</div>
</section>
<section id="does-fixing-it-collect-the-points" class="level3">
<h3 class="anchored" data-anchor-id="does-fixing-it-collect-the-points">Does fixing it collect the points?</h3>
<p>That is a question about ppg, so it needs the tool this page is about: the same variance-reduced measurement as exp019, same opponent, same n, same seeds — changing only how the network executes a double.</p>
<p>The baseline arm is exp019’s published result rather than a fresh run, which is only legitimate if the refactor left the old path untouched. It did: over 277 real decisions the rewritten greedy path chooses the same action <em>index</em> as the pre-exp020 implementation, 277/277 — not merely the same resulting position. The leaf deduplication that makes joint enumeration affordable is invisible to the arm that does not use it.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>engine</th>
<th>doubles execution</th>
<th>VR ppg vs GNUBG-0-ply</th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>exp019 baseline</td>
<td>greedy two-step</td>
<td>+0.0129</td>
<td>±0.0053</td>
</tr>
<tr class="even">
<td><strong>exp020</strong></td>
<td><strong>joint over four half-moves</strong></td>
<td><strong>+0.0461</strong></td>
<td><strong>±0.0047</strong></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td><strong>+0.0331 gain</strong></td>
<td>z = +9.14</td>
</tr>
</tbody>
</table>
<p>Both arms: n = 6,000 games, identical weights, identical seeds. The two estimates are independent samples, so the CI on the difference is computed unpaired — the conservative choice, since shared dice can only help.</p>
<p>The gain is real: executing a doubles turn jointly rather than greedily is worth <strong>+0.0331 ppg</strong>, with the weights untouched. <code>ep22</code>’s PR is still 0.95 — that metric scores complete moves and never enters this code path — so the network did not get stronger. It stopped throwing points away on 1/6 of its turns. Free, and invisible to every benchmark the project runs.</p>
<p>Set against the 0.054 ppg the benchmark seemed to promise and play did not deliver, this recovers <strong>61%</strong>.</p>
<p>And the two halves of the experiment agree. Stage 1 added up equity conceded at individual decisions and predicted a cost of +0.0345 ± 0.0042 ppg. Stage 2 measured the change in who actually won, and got +0.0331. Those are different quantities computed from different games by different means — a sum of per-decision GNUBG equity errors on one side, a difference of variance-reduced game outcomes on the other — and they land 0.0014 apart. That agreement is the strongest evidence on this page that both instruments are working.</p>
<p><strong>+0.021 ppg still separates the two.</strong> To know whether that gap is real rather than two noisy numbers disagreeing, the prediction needs an error bar of its own — which exp019 never gave it. Scoring both engines on the same 14,693 benchmark decisions and differencing them <strong>per decision</strong> (paired, so the position-to-position variation cancels) gives a predicted <strong>+0.0670 ± 0.0059</strong> against a measured +0.0461 ± 0.0047. The residual is <strong>+0.0210 ± 0.0076</strong>, z = 5.44. It is real.</p>
<p>It is also not something more games can settle. <strong>61% of that interval’s variance comes from the benchmark prediction, not from the play measurement</strong> — tripling to n=18,000 would tighten the residual only from ±0.0076 to ±0.0065, and even <em>infinitely</em> many games would only reach ±0.0059. The bottleneck is on the benchmark’s side.</p>
<p>So the residue stands as the other exp019 explanation predicted: BGSage’s positions come from Sage 3-ply self-play, and an error-rate advantage measured there need not transfer intact to the distribution <code>ep22</code> generates against GNUBG. Testing <em>that</em> needs a different experiment — scoring both engines on positions drawn from their own head-to-head games — not a longer run of this one.</p>
<p>One assumption underneath all of it deserves naming: converting an error <em>rate</em> into points per game assumes per-decision equity errors accumulate linearly into the final result. That is a model, not an identity. exp020 happens to calibrate it — stage 1 summed per-decision errors over real games and predicted +0.0345, stage 2 measured +0.0331 in outcomes, so the assumption is good to about 4% over this range. Applying that same correction to the benchmark’s 0.0670 would move it by under 0.003 and leave the residual intact.</p>
<div id="37b85085" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="variance_reduction_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Where the points went. The benchmark’s prediction, the engine as exp019 measured it, and the same engine with doubles executed jointly — same weights, same opponent, same 6,000 seeds.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-this-means-for-the-projects-older-numbers" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means-for-the-projects-older-numbers">What this means for the project’s older numbers</h3>
<p>Every head-to-head ppg the project has ever reported was measured with the greedy path, so every one of them understates the network that produced it — including <a href="#exp019">exp019</a>’s own +0.0129 and <a href="./pretraining_analysis.html">exp011b</a>’s −0.053 ± 0.034.</p>
<p>They are not being retroactively restated here, for two reasons. They are correct as <em>measurements of the engine at the time</em> — the games really were played that way — and the conclusions drawn from them (which checkpoint beat which) compared arms that all shared the handicap, so those comparisons stand. Nor is the correction a constant: it depends on how well a net’s value function handles mid-turn positions, so <code>ep22</code>’s +0.0331 cannot simply be added to a weaker checkpoint’s score. What can be said is the direction — <strong>every historical ppg is a lower bound</strong> — and that any future comparison against one of them should either re-measure the baseline or note the asymmetry.</p>
<p>The static <a href="./pretraining_analysis.html">BGSage</a> numbers are untouched. PR and value-head MSE score complete moves against fixed references and never enter this code path — which is exactly why the disagreement between the two families of metric was the clue worth chasing.</p>
<p><strong>Conclusion.</strong></p>
<blockquote class="blockquote">
<p>Is Raccoon’s two-step doubles execution a strength bug worth fixing? → <strong>Yes</strong>: joint enumeration is worth <strong>+0.0331 ppg</strong> (z = +9.14), taking <code>ep22</code> from +0.0129 ± 0.0053 to <strong>+0.0461 ± 0.0047</strong> (variance-reduced ppg vs GNUBG-0-ply, n=6,000 each, identical weights).</p>
</blockquote>
</section>
</section>
<section id="what-this-does-and-does-not-change" class="level2">
<h2 class="anchored" data-anchor-id="what-this-does-and-does-not-change">What this does and does not change</h2>
<p>Variance reduction is a <strong>measurement</strong> tool, not a strength gain. It does not alter a single move; the network that plays is the network that plays. What it changes is the price of knowing how good that network is: the project’s established rulers stay valid, but a comparison that used to need tens of thousands of games now needs a few thousand.</p>
<p>The strength gain in <a href="#exp020">exp020</a> is not an exception to that — it came from the <em>measuring</em>. A 0.05 ppg discrepancy between benchmark and play is invisible at ±0.035; it only became a question worth asking once the interval was ±0.005, and only then did anyone go looking at the code that answers it. Sharper instruments find bugs, which is a large part of why they are worth building.</p>
<p>Two limitations worth stating. First, the estimator is unbiased but its <em>variance reduction</em> is only as good as the control variate — a position class GNUBG’s 0-ply evaluator reads poorly is a class where less noise gets removed, silently. Second, none of this helps against a slow opponent: the cost of measuring GNUBG at 2-ply is dominated by GNUBG’s own thinking time, not by the estimator, though the same 6,000 games would now say a great deal more than they used to.</p>
<p>Left on the table, in rough order of value: the external unbiasedness control against <code>exp011b/ep3</code>; a 2-ply opponent, now finally affordable in information terms; and stratified opening rolls, an orthogonal and completely free further reduction, deliberately left out here so it would not confound the comparison. The doubles-execution question is no longer on this list — <a href="#exp020">exp020</a> settles it below.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>David Montgomery, <a href="https://bkgm.com/articles/GOL/Feb00/var.htm"><em>Variance Reduction</em></a>, GammOnLine, February 2000 — the canonical explanation, and the source of the zero-mean argument quoted above.</li>
<li>GNU Backgammon, <code>rollout.c</code> (<code>BasicCubefulRollout</code>) — accumulates <code>arMean − aaar[actual]</code> over all 36 rolls (30 for the opening) for both players, and applies it to the trial’s outcome, exactly as here.</li>
<li><a href="https://www.gnu.org/software/gnubg/manual/html_node/Rollouts-in-GNU-Backgammon.html">GNU Backgammon manual, <em>Rollouts</em></a> — variance reduction and the separate technique of quasi-random dice.</li>
<li>BGSage, <code>ROLLOUT.md</code> §4 and <code>cpp/src/rollout.cpp</code> — a production implementation with per-branch cubeful variance reduction; its measured 6.5× reduction in standard error on cubeless equity is the closest published comparison to the figure obtained here.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/research\.raccoonbg\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Tekst og tal</strong> · CVR 34101302 · Denmark</p>
</div>   
    <div class="nav-footer-center">
<p><a href="mailto:hello@raccoonbg.com">hello@raccoonbg.com</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lassehjorthmadsen/raccoon/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/lassehjorthmadsen/raccoon">GitHub</a> · <a href="https://github.com/lassehjorthmadsen/raccoon/blob/main/LICENSE">MIT licence</a></p>
</div>
  </div>
</footer>




</body></html>