{
  "hash": "eb3b3de5187a5bb8be05f3072475ab14",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Doubling Cube\"\nsubtitle: \"Janowski's model, measured against 33,395 rolled-out equities — and what Raccoon built from it.\"\ntoc-depth: 2\njupyter: python3\n---\n\n\n\n\nRick Janowski's cube-life-index model is how a cubeless evaluation becomes a cube\ndecision. GNU Backgammon and eXtreme Gammon both ship it, and the constant they use —\n$x = 0.68$ for contact positions — has stood essentially unchanged for as long\nas they have shipped it. Janowski's own 1993 paper does not give 0.68; he\nestimates $x$ at between $\\tfrac12$ and $\\tfrac34$, \"with $\\tfrac23$ being a\nnormal value\". The 0.68 is GNU Backgammon's. It is rarely *measured*, because measuring it needs observed cubeful\nequities for a large and varied set of real positions.\n\nThose observations were already on disk. The BGSage money benchmark rolled\npositions out to completion with the cube live, recording for each candidate a\n**measured cubeful equity** next to the cubeless probabilities for the same\nposition — and the cube sits in a different place across them, which is what\nmakes the model separable. This page tests it on 33,395 of those, then reports what happened when Raccoon\nimplemented it: [exp024](#exp024-results) measures the model,\n[exp025](#exp025-results) ships it into move selection and measures what that\nbuys, and [exp026](#exp026-results) plays it against real GNU Backgammon.\n\n**The short answer is that the model is in good shape and the conventional\nconstant survives.** Two of the three equity formulas are correct at $x = 0.68$\nto within 0.018 of a point. The third, for a centred cube, wants a much higher\nindex — but adopting it buys nothing where the parameter is actually read, and we\ncannot explain it, so we are not acting on it. What *is* worth fixing is\nstructural: use the piecewise form, respect the provable bounds, and floor $W$ and\n$L$ at one point.\n\nTwo numbers this page used to report were wrong, and both errors are the same\nkind, so they are worth stating rather than quietly correcting. Reference quality\nis recorded in **two** fields, not one: filtering on `eval_level` alone admitted\ntruncated rollouts whose leaves call Janowski. Against references that include\nthem, retuning the index looks worth **+1.167 ± 0.271** cube PR. Against\nreferences that are actually measurements it is worth **+0.128 ± 1.242** —\nnothing. [The measurement\nsection](#how-to-measure-it) sets out the filter that separates them.\n\nEverything here is money play with the Jacoby rule and beavers on, matching the\nbenchmark. Match play, where the score moves every take point, is out of scope and\nis not calibrated by anything below.\n\n\n\n## The model is three formulas\n\nA network evaluates a position *cubelessly*: six probabilities for winning or\nlosing a plain game, a gammon, or a backgammon, if the game were played out with\nno cube. Under real rules that game never happens. Janowski's model says what\nthose probabilities are worth once the cube is on the table.\n\nIt starts by compressing the outcome distribution into two numbers — the average\nvalue of a win and of a loss:\n\n$$W=\\frac{\\sum_i i \\cdot P(\\text{win } i)}{P(\\text{win})}\n\\qquad\nL=\\frac{\\sum_i i \\cdot P(\\text{lose } i)}{P(\\text{lose})}$$\n\nA gammonless position has $W = L = 1$. Two extremes can then be solved exactly. A\n**dead cube** can never be turned again, so the game plays out at the current\nstake and a take risks $2L-1$ to gain $2W+1$ — the familiar 25% take point. A\n**live cube** is redoubled at exactly the right moment every time, which adds a\nconstant bonus and gives the continuous model's 20%. Real positions sit between,\nat a fraction $x$ — the **cube life index**, 0 for dead, 1 for live.\n\nWhat matters below is that the model then produces **three different equity\nformulas, one per cube location** (Janowski's equations 5–7):\n\n$$E_O = C_V\\left[p(W + L + 0.5x) - L\\right] \\qquad \\text{we own the cube}$$\n\n$$E_U = C_V\\left[p(W + L + 0.5x) - L - 0.5x\\right] \\qquad \\text{opponent owns it}$$\n\n$$E_C = \\frac{4C_V}{4-x}\\left[p(W + L + 0.5x) - L - 0.25x\\right] \\qquad \\text{centred}$$\n\nEvery take point, cash point and doubling point in the paper is derived by setting\ntwo of these equal. So the model stands or falls on them, and — crucially — **they\ncan fail independently**. That is what makes the measurement below possible, and\nit is not something a cube decision can reveal: a double compares only two\nlocations at a time.\n\nOne property of $x$ matters later: it describes **the position, not the cube**.\nJanowski names three things that set it — how far the position is from the\noptimal doubling point, how wide the doubling window is, and how volatile the\nposition is — and states that the cube-ownership bonus is \"proportional to the\ndegree of cube-life of the position (and inversely proportional to its long-term\nvolatility)\", with $x = 0$ at maximum volatility and $x = 1$ at zero volatility.\nHe does not derive a value for it; he writes that \"finding accurate values for\n$x$ is a difficult, almost impossible, task\" and estimates typical ones. All\nthree factors are properties of the position, and a position has the same three\nwhoever holds the cube, so $x$ cannot legitimately depend on where the cube\nsits.\n\n::: {#74b2fef8 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Janowski's three formulas in a gammonless position (W = L = 1) at the published index x = 0.68 — pure theory, no data. Read the y-axis carefully: these curves give the equity of NOT turning the cube, which is what the formulas are defined to produce. Above the cash point that is the wrong quantity to act on — you double, your opponent passes, and gammonless the position is worth exactly +1 (dash-dotted). The gap between the blue curve and that ceiling is not an error in the formula; it is the difference between holding the cube and using it.](cube_files/figure-html/cell-3-output-1.png){}\n:::\n:::\n\n\n> What is Janowski's model? → **Three equity formulas sharing one parameter**, one\n> per cube location, from which every take point and doubling point is derived.\n> They can be wrong independently, and $x$ is meant to describe the position, not\n> the cube's location.\n\n## What the engines ship, and what to ship\n\nThree implementation decisions, all settled before any fitting. Each is either\nprovable or measurable, so none of them costs a parameter.\n\n### Use the piecewise form, not equations 5–7\n\nEquations 5–7 are linear in $p$, so they run straight past the values a game can\nactually pay. GNU Backgammon and BGSage instead pin the live-cube equity at the\nfour points where it is known — $-L$ at $p = 0$, $-1$ at the take point, $+1$ at\nthe cash point, $+W$ at $p = 1$ — and interpolate linearly between them,\nflattening the outer segments to $\\pm 1$ under Jacoby. That is a *substitution*\nfor equation (7), not an approximation of it.\n\nIt is also more accurate. On owned cubes the piecewise form reaches RMSE\n0\\.0177 against 0.022–0.027 for the\nalgebra, and its fitted indices sit close to the convention rather than\nscattering. `raccoon/cube/janowski.py` implements the piecewise form.\n\n### The bounds are provable, so they should never be fitted\n\nIf you double and your opponent takes, they took because taking beat passing *for\nthem*, so you collect less than $+1$; if they pass you collect exactly $+1$. No\ndoubling line pays more than a point. Undoubled you cannot collect more than the\nnatural size of the win. So\n\n$$-L \\;\\le\\; E \\;\\le\\; \\max(1, W) = W$$\n\nand under Jacoby with the cube centred this tightens to $\\pm 1$, since an\nundoubled gammon counts one anyway. The measured rollouts respect it. The\npiecewise form satisfies it by construction — both the dead and the live branch\nlie inside the bounds, so any blend of them does too — which is a second reason to\nprefer it over the algebra, which breaks the bound by up to a full point. We pin\nthis as a property test rather than enforcing it with a clamp, so a change that\nbreaks it fails loudly instead of being silently patched over.\n\n### Floor $W$ and $L$ at one point\n\nNot a defensive nicety; the labels violate it. Variance reduction reports\ncorrected means rather than counts, so a rare outcome can come back very slightly\nnegative, and $W = 1 + (P_{gw} + P_{bgw}) / P_{win}$ divides that by a win\nprobability that can be minute. Across this benchmark that produces **550 rows\nwith $W < 1$, ten of them below zero, and a worst case of $-5.29$** — which would\nput the take point and both envelope endpoints through the floor. A win cannot be\nworth less than a point. Flooring inside `compute_wl` repairs every consumer at\nonce.\n\n> What should the implementation look like before any tuning? → **Piecewise\n> interpolation, bounds as a test rather than a clamp, and $W, L \\ge 1$.** All\n> three are free: no parameter, no fitting, no benchmark needed.\n\n## How to measure it {#how-to-measure-it}\n\nCube models are usually argued about rather than measured, because the references\nare hard to come by. This benchmark has them — but most of its entries cannot\njudge a Janowski variant, and it takes two fields to tell which can.\n\n### It takes two fields to identify a measurement\n\n`eval_level` records how a reference was produced; `tier` records how much effort\nthe decision earned. Neither is sufficient alone, because BGSage gives\n*truncated* rollouts the same `Rollout` label as full ones. Crossed:\n\n| reference | `tier` | `eval_level` | cube entries | rolled-out candidates |\n|---|---|---|---:|---:|\n| played to completion | `rollout` | `Rollout` | **282** | **33,395** |\n| truncated at 3-ply | `3T` | `Rollout` | 418 | 9,241 |\n| 3-ply search | `3P` | `3-ply` | 1,496 | — |\n\nOnly the first row is an observed average. The truncated rollouts stop at a\ncubeful 3-ply evaluation that calls Janowski at its own leaves, and the 3-ply\nreferences are that same search all the way down — so scoring a Janowski variant\nagainst either is scoring it partly against itself.\n\nThe bias does not show up where you would look for it. Pooled cube PR barely\nmoves — 2.353 over all references against 2.259 over the measured ones — because\nthe contaminated groups pull in opposite directions: the model scores an\nimplausible 0.649 against the 3-ply references it half-agrees with, and 7.726\nagainst the truncated ones, which are the hardest decisions in the benchmark. The\nlevel looks fine. What breaks is every *comparison* made on it:\n\n| references | baseline | one refitted index | paired gain |\n|---|---:|---:|---:|\n| all 2,196 entries | 2.353 | 1.185 | **+1.167 ± 0.271** |\n| the 282 measured ones | 2.259 | 2.130 | **+0.128 ± 1.242** |\n\nDeeper cubeful search sees cube value a static evaluation cannot — market losers,\nmostly — so a larger $x$ lets a 0-ply model imitate a 3-ply one. Refitting against\nsearch-derived references buys depth, not accuracy, and it does not survive\ncontact with a real payoff.\n\n### The checker rollouts are the instrument, not the cube decisions\n\nThe benchmark's *cube* entries look like the natural place to test a cube model,\nbut only 282 of them are measured, and a cube decision structurally cannot\nseparate the three formulas — it compares two locations at a time. The *checker*\ncandidates can. Every one carries a measured cubeful equity beside the cubeless\nprobabilities for the same position, and the parent decision records where the\ncube sat, so each formula is testable on its own against\n33\\,395 observations.\n\nTwo properties of these positions carry into every conclusion below. They are\n**post-move** positions, so the opponent is on roll — the formulas do not model\nwhose turn it is, so we evaluate from the on-roll player's side and negate. And\nthe cube decisions taken *during* each rollout come from a bot that also uses\nJanowski, so these measure equity under Janowski-quality cube play rather than\noptimal cube play.\n\n### The references have a noise floor\n\nEvery rolled-out candidate carries a standard error, so the benchmark can be\nasked how well it knows its own answer:\n\nAcross 5,651 rolled-out decisions the median standard error on the gap between the best move and the runner-up is **0.0033** of a point. **32%** of those decisions have their best move within one standard error of the second-best, and 51% within two.\n\n\nThat noise is fixed and identical for every engine scored, so comparisons stay\nfair. But it puts a floor under achievable PR, and it is why a near-parity engine\ncannot be separated on move accuracy alone — a third of the closest decisions in\nthe benchmark do not have a knowable right answer.\n\n### Compare like with like, or the model is charged for an option\n\nJanowski's formulas give the **no-double** equity — what a position is worth if\nthe cube stays put — while a rollout reference always includes the option to\ndouble. Comparing the two directly charges the formula for an option it was never\nasked to price. Since these are post-move positions the option belongs to the\n*opponent*, so the matching quantity is $\\min(\\text{ND}, \\max(\\text{DT}, -1))$: a\nminimum over their choice, a maximum over ours. Getting that backwards inflates\nthe centred error by half. Four positions checked by hand in GNU Backgammon\nconfirm the distinction — its *No double* line reproduces `cl2cf_money` closely\nand its *optimal* line matches the rollout.\n\n> Can Janowski be measured with what we already have? → **Yes — on 33,395 observed\n> cubeful equities**, spanning all three cube locations, at zero play cost. But\n> only an eighth of the benchmark's cube entries can judge it, and a pooled score\n> hides that: the level looks normal while every comparison built on it inflates.\n\n## What the measurement says\n\n| formula | cube location | n | bias at 0.68 | RMSE at 0.68 | best $x$ | RMSE there |\n|---|---|---:|---:|---:|---:|---:|\n| $E_O$ | we own the cube | 14,813 | +0.0007 | 0.0179 | 0.710 | 0.0177 |\n| $E_C$ | cube centred | 10,677 | +0.0135 | 0.0430 | 0.925 | 0.0307 |\n| $E_U$ | opponent owns it | 7,905 | +0.0025 | 0.0162 | 0.720 | 0.0155 |\n\n\n**$E_O$ and $E_U$ are right, and the published constant is right for them.** Bias\nunder 0.003 of a point across\n22\\,718 positions, RMSE under\n0.018, and freely fitted indices of 0\\.71 and\n0\\.72 — close to each other and close to\n0.68, which is what a genuine property of the position should look like. Refitting\nmoves their RMSE by about 1%.\n\n**$E_C$ is the outlier.** Nineteen times the bias, more than twice the RMSE, and\nit wants 0\\.925 — a nearly perfect cube.\nEven there it stays worse than the other two are for free.\n\nAn independent check that the method is sound rather than the model being\nuniformly bad: let the index float against the take/pass line alone, told nothing\nabout what it should be.\n\nAcross all 282 measured cube positions the take/pass index comes out at **0.700**, against GNU Backgammon's published 0.68. Within pure races it comes out at 0.515, against GNUBG's documented 0.60 race constant.\n\n\nThe measurement reproduces both published constants without being told either.\n\n::: {#67b3b3b1 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Model minus rollout for each formula, at the published index. Zero is agreement; below zero the model says a position is worth less than it proved to be. Two panels are a narrow band about zero; the centred panel is more than twice as wide and visibly tilted — high on the left, low on the right.](cube_files/figure-html/cell-7-output-1.png){}\n:::\n:::\n\n\nAverages hide where the failures are. Binning the same errors by observed equity,\nwith intervals clustered on the checker decision — candidates within one decision\nare the same position played different ways, and clustering roughly doubles the\nintervals against treating them as independent:\n\n::: {#5ffcc286 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![Bin means with 95% intervals, clustered on the checker decision. Marker area is proportional to the number of positions in the bin, so the thin tails do not read as loudly as the dense middle. E_O tracks zero until the position is nearly won, then sags through the run-up to a cashing decision and recovers once the cash is banked. E_C is off in both directions and crosses zero near even money. E_U sits on zero wherever it has weight.](cube_files/figure-html/cell-8-output-1.png){}\n:::\n:::\n\n\n**$E_U$ is correct wherever it has weight** — on zero from about $-0.2$ equity\nupward. **$E_O$ is correct until the position is nearly won**, then sags through\nthe band where a cashing decision is live and snaps back above $+1.0$. That band\nis thin, which is why the aggregate barely notices it. **$E_C$ is wrong in both\ndirections** — positive when the position is losing, negative when it is winning,\ncrossing zero near even equity. A residual that changes sign cannot be removed by\nany constant, any index, or any offset.\n\nThe $E_O$ sag has a mechanism worth naming, because it is a *modelling* choice\nrather than a measurement question. The model blends a dead branch with a live\nbranch in fixed proportion, $(1-x)E_{\\text{dead}} + xE_{\\text{live}}$. As a\nposition approaches its cash point the live branch has reached its ceiling of\n$+1$ while the dead branch is still only $2p-1$, so the blend drags the answer\ndown by roughly $(1-x)$ times the gap between them. But a position near its cash\npoint does not *need* future cube efficiency — you double and your opponent\npasses. A fixed weight is defensible in the middle of the range and not near the\nboundary.\n\n::: {#f3f76281 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![The same errors split by BGSage's game-plan classification. The centred series is the widest in every panel, so this is not a quirk of one position type, and the same tilt appears in each. Per-plan centred RMSE is in the panel titles.](cube_files/figure-html/cell-9-output-1.png){}\n:::\n:::\n\n\n> Where is the model weak? → **Only in the centred formula**, and everywhere in its\n> range rather than in one position type or one game plan. The other two are\n> correct at the published constant.\n\n## Why we are not acting on the centred index\n\nA centred cube fits at 0\\.925 — almost a\nperfect cube. The result is robust: it survives clustered bootstrapping, disjoint\nhalves of the games, and every formulation of the Jacoby handling we tried, and it\nreproduces on the benchmark's own cube entries, which need no perspective flip at\nall. It is also the case where $x$ matters most. And we still cannot explain it.\n\nTwo honest readings remain, and this data cannot separate them. Either an initial\ndouble really is more efficient than a redouble — both players can pick their\nmoment, and a full ladder of recubes lies ahead — or the centred formula is\nmissing something structural that $x$ absorbs. The second is the better bet given\nthe sign change above, since no constant can produce one.\n\nWhat settles the *practical* question is that adopting it buys nothing.\n\n### The index is read for move selection, not for takes\n\nEverything above is an *estimation* metric: every candidate weighted equally,\nscored on how close the model lands. That is not how the parameter earns its keep.\nOver 500 games the benchmark asks:\n\n| question | times in 500 games | relative frequency |\n|---|---:|---:|\n| which move? (every turn) | 14,693 | 22.5× |\n| should I double? (every turn with cube access) | 2,189 | 3.4× |\n| should I take? (only when actually doubled) | 653 | 1.0× |\n\n\nSo the index is read for move selection roughly **22 times as often** as for a\ntake decision — and move selection only cares about the *ranking* of candidates\nwithin one position, where an error common to all of them cancels. A change can\nlook valuable on RMSE and be worth nothing here. On the\n5\\,695 measured decisions that offer a real choice:\n\n| setting | picks the best move | mean cubeful equity lost |\n|---|---:|---:|\n| published x = 0.68 | 88.0% | 0.00053 |\n| centred 0.925, owned 0.68 | 87.6% | 0.00060 |\n| one refitted index (0.800) | 88.0% | 0.00053 |\n\n\nRetuning moves this by a fraction of a percentage point, and the centred refit\nmakes it slightly *worse*. There is no case for shipping it.\n\n> Should the centred index be changed? → **No.** It is a real and unexplained\n> feature of the data, but acting on it costs accuracy where the parameter is\n> actually read. Keep 0.68 and record the anomaly as open.\n\n## exp024, re-scored {#exp024-results}\n\n**Hypothesis.** Janowski's functional form is adequate and its published cube-life\nindex is simply mis-set: re-fitting $x$ recovers the cube-decision error that\n$x = 0.68$ leaves.\n\n**Primary metric.** Cube PR on the BGSage money benchmark — mean equity thrown\naway per decision, times 500 — restricted to the 282 positions whose references\nwere played to completion, n = 432 sub-decisions, fed the benchmark's own\nreference probabilities so the net's evaluation error is out of the comparison.\nVariants are fitted on half the *games* and confirmed on the held-out half, and\ncompared to the baseline paired.\n\n| variant | cube PR | paired vs baseline | coherent? |\n|---|---:|---:|:--|\n| $x = 0.68$ (published) | 2.259 ± 0.488 | — | yes |\n| 0.68 contact / 0.60 race | 2.228 ± 0.489 | +0.031 ± 0.112 | yes |\n| one refitted index | 2.130 ± 1.140 | +0.128 ± 1.242 | yes |\n| refitted per cube state | 1.306 ± 0.326 | +0.953 ± 0.528 | **no** (93% violations) |\n| 0.68 plus a fitted shift | 2.138 ± 0.477 | +0.121 ± 0.190 | yes |\n| $x = 0$ (dead cube) | 5.566 ± 1.657 | -3.307 ± 1.647 | **no** (94% violations) |\n| $x = 1$ (live cube) | 6.680 ± 1.950 | -4.422 ± 2.058 | yes |\n\n\nNothing beats the published constant. The two fitted variants land about 0.12\nlower with intervals many times that wide, the race split is inside noise, and the\ndead and live envelopes are far worse — which is the sanity check that the model\nis doing real work between them.\n\n**The coherence gate matters more than the PR column.** For any one position\n$E_O \\ge E_C \\ge E_U$ must hold: owning the cube cannot be worth less than it\nbeing centred, which cannot be worth less than the opponent owning it. Nothing in\nthe fitting enforces that, because each entry is *either* centred *or* owned, so\nthe three lines are fitted on disjoint position sets. The per-state fit scores best\non PR and drives the owned-cube index to 0.42 against the 0.71 the equity data\ngives, inverting the ordering on\n93%\nof positions. PR cannot see that, because each scored decision involves only one\ncube location. A mis-set constant cannot produce an impossible ordering; a\nmis-specified form can.\n\n**Power, stated rather than assumed.** 432 sub-decisions cannot resolve a small\nchange: the paired interval on the refitted index is ±1.242, so this test would\nmiss anything under about a point of PR. It is a null in the sense of *no evidence\nof benefit*, not proof of no effect. The move-selection comparison above, at\n5\\,695 decisions, is the better-powered instrument\nand agrees.\n\n### Where Raccoon's own evaluations land\n\n| probabilities | cube PR (n = 432) |\n|---|---:|\n| benchmark reference (the model alone) | 2.259 ± 0.488 |\n| Raccoon exp018/ep22 | 2.684 ± 0.622 |\n| GNUBG 0-ply | 2.658 ± 0.638 |\n\n\nRaccoon's net and GNUBG at 0-ply are indistinguishable on cube decisions, and both\nsit a little above what the model reaches on perfect probabilities — the cost of\nevaluation error rather than of cube modelling.\n\n> Is the cube-life index mis-set? → **No.** Against references that are\n> measurements, no variant beats $x = 0.68$ (best: one refitted index, **+0.128 ±\n> 1.242** paired, n = 432). The earlier **+3.206** came from references produced by\n> a search that uses Janowski at its own leaves.\n\n## What Raccoon built\n\nexp024 left the cube specified but unbuilt: the shipped net already emitted the\nsix-outcome distribution, `raccoon/cube/janowski.py` was written and tested, and\nnothing in the playing path referenced it. exp025 closed that gap.\n\n**The model, settled and unchanged.** Piecewise dead/live blend; $x = 0.68$ for\ncontact and $0.60$ in races; one index for all three cube locations, never one per\nlocation; $W$ and $L$ floored at 1; the $[-L, W]$ bound as a test. Nothing was\nrefitted.\n\n**Two pieces of perspective logic**, both in `raccoon/cube/state.py`, both easy to\nget silently wrong and therefore both pinned by tests. `CubeState` translates\nbetween seat indices, which a game loop speaks, and the `CENTERED`/`PLAYER`/\n`OPPONENT` labels, which Janowski speaks. And `flip_label` records the rule that\n**changing perspective flips the cube owner as well as the sign of the equity** —\nnegating alone hands the opponent your cube ownership, and nothing about the\nresulting number looks wrong.\n\n**Cube-aware checker play came first**, not the double/take decision, because the\nmodel is read for move selection roughly 22 times as often. `child_cubeful_values`\nin `raccoon/train/lookahead.py` shares its enumeration, doubles handling and leaf\ndedup with the cubeless `child_values` through a common `enumerate_leaves`, so the\ntwo rankings cannot drift apart. The regression test that matters is an identity:\nat $x = 0$ with no Jacoby, `cl2cf_money` *is* `cubeless_equity`, so the cubeful\npath must reproduce the shipping cubeless one to the last bit on real positions.\n\n**The prize was already measured.** A *perfect cubeless* player throws away\n\n**PR 0.336 ± 0.042** on the cubeful metric, with cubeless-best and cubeful-best differing on 992 of 14,693 decisions (6.8%). It concentrates exactly where the cube is most alive — PR 0.553 with the cube centred against 0.145 when the opponent owns it — and is nearly absent in pure races (0.046).\n\n\nThat floor is what a player with *perfect* probabilities leaves behind. The\nquestion exp025 asks is how much of it a real net, carrying its own evaluation\nerror, actually claims.\n\n## exp025, cube-aware checker play {#exp025-results}\n\n\n\n**Hypothesis.** Ranking candidate moves by Janowski cubeful equity instead of\ncubeless equity reduces the cubeful move-selection error of the shipped net\n(exp018/ep22).\n\n**Primary metric.** Cubeful PR on all\n14\\,693 BGSage checker decisions — mean cubeful equity thrown\naway per decision, times 500 — scored against each candidate's `equity` field\nrather than its `cubeless_equity`, which is the same reference the cube-blind\nfloor above is measured on. The two arms are compared **paired**, with the\ninterval bootstrapped over the 499 generating games.\n\n**Why paired, and why it is not optional.** The arms agree on the great majority\nof decisions — the rankings differ on only\n376 of them\n(2\\.6%) — so their per-decision errors\nare identical almost everywhere and an unpaired comparison of two PR numbers has\nan interval far wider than the effect. Both errors are therefore taken off the\n*same* six-outcome forward pass: for an `outcomes6` head the value head's equity\nis exactly `cubeless_equity` of its own distribution, so the arms are paired by\nconstruction rather than by re-running and hoping the passes matched. The\nseparately-run cubeless arm reproduces the derived one to rounding, which is the\ncheck that the shortcut is sound.\n\n| cube position | n | cubeless ranking | cubeful ranking | gain | 95% CI |\n|---|---:|---:|---:|---:|:--|\n| all decisions | 14,693 | 1.382 | 1.307 | **+0.075** | [+0.025, +0.126] |\n| we own the cube | 4,015 | 1.149 | 1.155 | **-0.007** | [-0.055, +0.040] |\n| cube centred | 5,657 | 1.851 | 1.655 | **+0.196** | [+0.079, +0.316] |\n| opponent owns it | 5,021 | 1.039 | 1.037 | **+0.003** | [-0.034, +0.041] |\n\n\n**The gain is real and small.** Cubeful ranking is worth\n\\+0\\.075 PR with the interval clear of zero. Against the\n0\\.336 floor that is about\n22% of the available prize — the rest\nis eaten by the net's own evaluation error, which is the thing that decides *which*\ncandidate the cube term is applied to. The rankings differ on\n2\\.6% of decisions against the\n6\\.8% on which a perfect player's would.\n\n**All of it sits in one bucket, and it is the tainted one.** The gain is confined\nto a centred cube; with the cube owned by either side it is indistinguishable from\nzero. That is where exp024 said the cube-blindness lives, so the sign is\nunsurprising — but a centred cube is also exactly where the Jacoby rule bites, and\nthe benchmark was generated with Jacoby **on** while Raccoon's target is money\nwithout it. Scoring here therefore models Jacoby to match the references, and the\nJacoby-clean owned-cube buckets are the ones showing no effect. **This is weaker\nevidence for the target game than the interval suggests**, and it is the first\nthing a follow-up should attack.\n\n**No head-to-head, deliberately.** The natural completion is \"and it beats GNUBG\nat cubeful money\". It is not here because there was no honest opponent to hand.\n`gnubg-nn` — the package every other Raccoon number is measured against — cannot\nmake a money cube decision at all (`evaluate_cube_decision` raises *Not\nimplemented for money*; the binding covers match play only), and it ranks checker\nplays cubelessly. Bolting our own Janowski layer onto its probabilities gives a\nmatch in which **both sides share one cube model**, while real GNU Backgammon uses\nthe closed form only as a leaf evaluator inside a cubeful search that makes cube\ndecisions at every node. That opponent is weaker than real GNUBG precisely on the\ncube, so a win against it would not be the `goal.md` criterion. The real opponent\ndoes exist — `/usr/games/gnubg` answers money cube decisions and cube-aware\nchecker play at about 71 ms per 2-ply decision — and wiring it up is exp026.\n\n**Supporting, and demarcated.** The cubeful arena built along the way\n(`raccoon/eval/cube_arena.py`) established that the dice-luck control variate\nsurvives a live cube: scaling each luck term by the cube value at its own roll\nkeeps it unbiased (mean luck $t = +0.26$ over 600 games), and using a *cubeful*\n$h$ rather than a cube-scaled cubeless one cuts the standard deviation 7.32× against\n5.24×, at $\\hat\\beta = 1.017$. That is a property of the estimator, which exp026\nreuses. The ppg those games implied was deliberately never read, and is reported\nnowhere.\n\n> Is cube-aware checker ranking worth anything? → **Yes, but little of what was\n> available.** Cubeful ranking beats cubeless ranking by\n> \\+0\\.075 PR (95% CI\n> \\[\\+0\\.025\\, \\+0\\.126\\],\n> n = 14\\,693, bootstrapped over\n> 499 games) — about\n> 22% of the cube-blind floor, and all\n> of it with the cube centred.\n\n## exp026, against the real GNU Backgammon {#exp026-results}\n\n\n\nexp025 measured the cube on a static benchmark and reported no head-to-head,\nbecause there was no opponent that could play one. This experiment supplies the\nopponent and runs the match.\n\n### The package cannot play a cubeful game; the binary can\n\nEvery Raccoon result before this was measured against `gnubg-nn`, the Python\npackage that wraps GNU Backgammon's networks. It cannot make a money cube\ndecision at all — `evaluate_cube_decision` raises *Not implemented for money*,\nits binding covering match play only — and it ranks checker plays on cubeless\nequity. Supplying the missing half with our own Janowski layer produces a match\nin which **both sides use the same cube model**, while real GNU Backgammon uses\nthe closed form only at the leaves of a search that decides the cube at every\nnode. That opponent is weaker than the real one on exactly the quantity a cube\nexperiment measures.\n\nThe installed `gnubg` binary does the whole job. `raccoon/eval/gnubg_cli.py`\ndrives it as an oracle: it is asked what to play or what to do with the cube, and\nnothing else, so Raccoon keeps running the game and rolling the dice — which is\nwhat allows the variance-reduced estimator to intercept every pre-roll state.\nPositions are set by named commands (`set board` with GNU Backgammon's own\nPosition ID, then `set turn`, `set dice`, `set cube value`, `set cube owner`)\nrather than by the FIBS `board:` line, which is about fifty unlabelled integers\nwhose field order we could not obtain from any reachable copy of the\nspecification.\n\nTwo checks stand behind every number below. The Position ID GNU Backgammon\nechoes back must equal the one sent, which tests the encoding against itself and\nso does not depend on either engine's evaluation. And every move it returns is\nconverted to a resulting board that must match one of the mover's legal turn\noutcomes, so a notation error stops the run instead of silently playing a\ndifferent move; this was exercised over whole games, 105 turns with no\nmismatches, including bar entries, hits, bear-offs, doubles and dances.\n\n### The two GNU Backgammons are different networks, and it does not matter\n\nThey ship different weights. The topology is identical — six networks, race\n214-128-5, crashed and contact 250-128-5, and three pruning networks — but the\ntrained values differ: the package's file declares itself version 1.01, the\nbinary expects 1.00, rejects it, and rejects its contents even when the version\nstring is changed. Their 0-ply probabilities differ by up to about 0.003.\n\nSince every earlier Raccoon number was measured against the package, they were\nplayed against each other, cubeless, at 0-ply, which is the setting exp019 and\nexp020 used:\n\nThe binary scores **-0.0026 ± 0.0047** ppg against the package (n = 6,000, variance-reduced). The interval covers zero and excludes anything larger than about 0.005 ppg either way.\n\n\nThe two are the same opponent at the precision that matters, an order of\nmagnitude below exp020's +0.0472 edge, so earlier results can be quoted\nalongside this one without a correction term.\n\n### Hypothesis, metric and power\n\n**Hypothesis.** The shipped net (exp018/ep22) with the Janowski cube layer wins\nat non-Jacoby cubeful money against real GNU Backgammon at 2-ply.\n\n**Primary metric.** Variance-reduced cubeful ppg from Raccoon's point of view,\nseats alternating, 95% interval.\n\n**Power.** A 600-game pilot read only the standard deviations; its ppg was never\nexamined and is not reported.\n\nIt gave sd_raw 2.907 and sd_vr 0.433, the latter within a thousandth of the 0.434 exp025 measured against the stand-in — the estimator does not depend on which opponent it watches. n was then fixed at 7,206 for a half-width of 0.01 ppg, matching the precision exp019 and exp020 reached, and not revisited.\n\n\n### What Raccoon fielded, and what it did not\n\n**Raccoon selected moves by 0-ply cubeful lookahead — no search — while GNU\nBackgammon searched two plies for both its checker play and its cube.** The\nconfiguration played here is materially weaker than the engine can field, on\nboth halves of the game, and the result has to be read that way.\n\nFor checker play the gap is measured. On the BGSage benchmark's checker\ndecisions, ep22 with depth-2 expectimax scores PR 0.426 against GNU Backgammon\n2-ply's 0.588 (exp021, n = 2,000); the 0-ply selection used here scores about\n1.03 on the same positions. Raccoon's checker play beats GNU Backgammon's at\nmatched depth and was not used.\n\nThe reason is cost, not choice. On this machine depth-2 search runs at 29.3\nseconds per decision and depth-1 at 4.25, against roughly 0.01 for 0-ply. At\nabout sixty decisions per game, a 7,206-game match at depth 2 would take on the\norder of a thousand hours against the 4.4 hours this run took. The cheapest\nsettings exp023 found without measurable strength loss still cost about 1,000\nevaluations per decision, which is roughly 2.5 minutes per game.\n\nSo this number bounds one configuration, not the engine: **0-ply checker play and\na root-only cube, against 2-ply checker play and a cubeful search.** Both\ndimensions were conceded. It does not establish that GNU Backgammon is stronger\nthan Raccoon.\n\n### Result\n\n| quantity | value |\n|---|---:|\n| **variance-reduced ppg** | **-0.0375 ± 0.0109** |\n| raw ppg | +0.0616 ± 0.0703 |\n| games | 7,206 |\n| games won | 3,557 (49.4%) |\n| standard deviation, raw / reduced | 3.046 / 0.473 (6.45x) |\n| cube turned | 5,045 of 7,206 games |\n| games ending in a pass | 43.4% |\n| Raccoon doubled | 4,589 of 98,067 opportunities (4.7%) |\n| Raccoon took | 2,850 of 4,565 offers (62.4%) |\n| gnubg subprocess restarts | 0 |\n\n\n**Raccoon loses, and the interval is clear of zero.** Read against the two\ncomparable numbers on the same network, the result is consistent rather than\nsurprising: Raccoon beats GNU Backgammon at 0-ply and loses to it at 2-ply.\n\n| comparison | opponent | cube | result |\n|---|---|---|---|\n| exp020 | GNUBG 0-ply (package) | none | **+0.0472 ± 0.0027** |\n| exp011b | GNUBG 2-ply (package), net ep3 | none | −0.064 ± 0.046 |\n| **exp026** | **GNUBG 2-ply (binary)** | **live** | **see above** |\n\n`goal.md` asks for a positive average win against GNU Backgammon at world class\nsettings with the interval above zero. **It is not met by this configuration**,\nwhich is the only claim the run supports.\n\n### The luck diagnostic, and why the result stands\n\nAccumulated dice luck averaged +0.0991 over the run (t = +2.87), where zero is expected. This does **not** bias the estimate: `vr = raw - luck` and the luck terms have mean zero by construction whatever a given sample does, so the reduced mean estimates the same quantity the raw mean does. What a large value says is that the dice in this sample favoured Raccoon by about 0.10 ppg, which is exactly the variance the estimator removes — the raw and reduced figures differ by precisely that amount.\n\nThe nominal significance of that t is unreliable, because luck is scaled by the cube value and is therefore heavy-tailed: the median absolute luck is 1.88, the 99th percentile 8.52, the maximum 44.65. The 111 games reaching a cube of 8 or more carry a mean luck of +2.17 against +0.07 for the rest. Dropping them does not change the conclusion: the reduced mean over the remaining 7,095 games is -0.0356.\n\n\n### What this does not separate\n\nThe result is a single number for two changes at once — Raccoon's checker play\nagainst a 2-ply opponent, and Raccoon's cube against a cubeful one. There is no\nmatching cubeless measurement of ep22 against the binary at 2-ply, so the deficit\ncannot be attributed. If ep22 is close to −0.037 cubeless at 2-ply, the cube\nlayer costs little and the gap is checker play; if it is near zero cubeless, the\ncube accounts for the whole of it. Those point at different next experiments —\nbetter evaluation, or cubeful search on our side — and this experiment cannot\nchoose between them.\n\n> Does Raccoon, playing 0-ply with a root-only cube, beat real GNU Backgammon\n> searching two plies with a cubeful cube? → **No.** ep22 with the Janowski cube\n> layer scores\n> \\-0\\.0375 ± 0\\.0109 ppg\n> (variance-reduced, n = 7\\,206), against\n> **+0.0472 ± 0.0027** for the same network against GNU Backgammon at 0-ply\n> cubeless. The deficit is not yet split between checker play and the cube.\n\n## What this page does not establish\n\n* **The population is not the target.** These are 500 games of one engine playing\n  itself. An index fitted here describes how efficiently *that bot* uses the cube,\n  on the positions its own style produces.\n* **The references are not optimal cubeful equity.** The payoff is empirical, but\n  the cube decisions taken during each rollout come from a bot that also bottoms\n  out in Janowski. Policy error can only lower realised equity, so this understates\n  what a better model could reach rather than overstating it.\n* **The benchmark is played under Jacoby, and Raccoon's target is not.** The\n  project aims at money game *without* Jacoby, as the stepping stone to match play\n  (`goal.md`). Jacoby zeroes gammons while the cube is centred, so on those\n  positions the reference engine plays boldly — it leaves the cubeless-best move\n  25.2% of the time against 10.7% with the cube owned, giving up five times as much\n  cubeless equity and trading away gammon wins as readily as it accepts gammon\n  losses, since the rule makes both worthless. That is 38.5% of the benchmark's\n  checker decisions, and it taints the labels rather than just the target: the\n  rollout continuations behind them were played bold too. Regenerating without\n  Jacoby means rebuilding every tier from new games, so we report the Jacoby-clean\n  owned-cube subset alongside the full number instead.\n* **Nothing here transfers to match play** beyond that: score-dependent take points,\n  no beavers, and Janowski in match-winning-chance space are all uncalibrated here.\n* **No position is observed at two cube locations**, so the ordering constraint is\n  a model check and can never be validated against data.\n* **The benchmark's cube positions are selected for being non-trivial**, so an\n  index fitted on them is tuned for close decisions and should not be quoted as a\n  general-purpose constant.\n* **Coordinate descent on a grid** finds a coordinate-wise minimum, not a certified\n  global one.\n* **exp025's gain is measured entirely under Jacoby.** It lands wholly in the\n  centred-cube bucket, which is the one the rule alters and the one whose rollout\n  continuations were played boldly because of it. The Jacoby-clean owned-cube\n  decisions show no effect at all, so the result transfers to non-Jacoby money by\n  assumption, not by measurement.\n* **exp026 fielded Raccoon's weakest configuration.** It played 0-ply checker\n  selection and a root-only cube against 2-ply checker play and a cubeful search.\n  ep22 with depth-2 search beats GNU Backgammon 2-ply on the benchmark's checker\n  decisions (PR 0.426 against 0.588, exp021), and that search was not used,\n  because at 29.3 seconds per decision a match of this size is not affordable on\n  this hardware. The number bounds a configuration, not the engine.\n* **exp026 is a single number covering two changes.** It moves checker play and\n  the cube together, with no matching cubeless measurement at the same depth, so\n  the deficit cannot be split between them.\n* **The opponent changed between exp020 and exp026** — from the `gnubg-nn`\n  package to the installed binary. They were measured against each other and are\n  indistinguishable, but that measurement was made cubeless at 0-ply, not at the\n  2-ply setting exp026 runs.\n\n## Still open\n\n* **The centred index.** Two readings, no way to separate them here; it needs a\n  reference not generated by a 0.68 policy.\n* **Whether an index per cube *value* is real.** A centred cube is always a 1-cube\n  here, so cube value and cube location tell the same story and cannot be told\n  apart.\n* **Volatility measured rather than proxied — but it is only one of three\n  factors.** Janowski ties $x$ inversely to volatility, and volatility can be\n  measured directly: the spread of the 0-ply value over the 21 next rolls,\n  reusing `raccoon/eval/luck.py` and the roll table in\n  `raccoon/search/expectimax.py`. Note before building it that volatility is the\n  third of the three factors he names, and that the two constants actually in use\n  do not follow from it alone — a race is *less* volatile than a contact position\n  yet gets the *lower* index (0.60 against 0.68). His second factor, the width of\n  the doubling window, explains that ordering and volatility does not, so a\n  volatility-only measurement would model part of $x$ and miss the part that\n  distinguishes the two cases we already treat differently. A cheap proxy does not\n  work either: the residual correlates with contact at only $-0.15$, with no\n  monotone trend, which\n  is precisely why the direct measurement is the experiment worth running.\n* **Cubeful search.** GNUBG does not use the closed form as its cube engine — it\n  uses it as a leaf evaluator inside a search that makes cube decisions at every\n  node. The gap that refitting appeared to close against 3-ply references *is* that\n  search, and running it is the principled way to close it. This is also why a\n  Janowski-only opponent cannot stand in for GNUBG: it is weaker than the real\n  thing on exactly the dimension being tested.\n* **Splitting exp026's deficit between checker play and the cube.** The single\n  most useful next measurement: ep22 against the binary at 2-ply, **cubeless**, on\n  the same estimator. It decides whether the next experiment should improve\n  evaluation or add cubeful search, and the harness for it already exists.\n* **Cubeful search on Raccoon's side.** GNU Backgammon decides the cube inside\n  its 2-ply search while Raccoon applies the closed form once at the root, so\n  Raccoon is the weaker side on cube decisions by construction. exp026 measures\n  what the whole gap costs; it does not say how much of it this accounts for.\n* **BGSage as an opponent.** `../bgsage` exposes a money `cube_action` behind a\n  C++ extension that is not built here, and is the stronger target. It reuses\n  exp026's harness, but \"beats GNU Backgammon\" and \"beats BGSage\" are separate\n  questions and get separate experiments.\n\n## References\n\n* Rick Janowski, *Take-Points in Money Games*\n  ([PDF](https://bkgm.com/articles/Janowski/cubeformulae.pdf)) — the cube-life\n  index, equations (5)–(7) for the three cube locations, the refined model of\n  Appendix 2, and the Jacoby factors of Appendix 3.\n* Keeler and Spencer, *Optimal Doubling in Backgammon* (1975)\n  ([online](https://bkgm.com/articles/KeelerSpencer/OptimalDoublingInBackgammon/index.html))\n  — the continuous model behind the live-cube take point.\n* [`raccoon/cube/janowski.py`](https://github.com/lassehjorthmadsen/raccoon/blob/main/raccoon/cube/janowski.py)\n  — the model, ported from the paper and cross-checked against its worked examples\n  and against GNU Backgammon.\n* [`experiments/pipeline_exp024.sh`](https://github.com/lassehjorthmadsen/raccoon/blob/main/experiments/pipeline_exp024.sh)\n  — every number on this page, reproducible end to end.\n\n",
    "supporting": [
      "cube_files"
    ],
    "filters": [],
    "includes": {}
  }
}